// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/crypto/v1/key_service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.threadline.proto.threadline.crypto.v1;

@kotlin.jvm.JvmName("-initializedecideTargetedRecoveryCaseRequest")
public inline fun decideTargetedRecoveryCaseRequest(block: com.threadline.proto.threadline.crypto.v1.DecideTargetedRecoveryCaseRequestKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.crypto.v1.DecideTargetedRecoveryCaseRequest =
  com.threadline.proto.threadline.crypto.v1.DecideTargetedRecoveryCaseRequestKt.Dsl._create(com.threadline.proto.threadline.crypto.v1.DecideTargetedRecoveryCaseRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `threadline.crypto.v1.DecideTargetedRecoveryCaseRequest`
 */
public object DecideTargetedRecoveryCaseRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.threadline.proto.threadline.crypto.v1.DecideTargetedRecoveryCaseRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.threadline.proto.threadline.crypto.v1.DecideTargetedRecoveryCaseRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.threadline.proto.threadline.crypto.v1.DecideTargetedRecoveryCaseRequest = _builder.build()

    /**
     * `string recovery_case_id = 1 [json_name = "recoveryCaseId"];`
     */
    public var recoveryCaseId: kotlin.String
      @kotlin.jvm.JvmName("getRecoveryCaseId")
        get() = _builder.recoveryCaseId
      @kotlin.jvm.JvmName("setRecoveryCaseId")
        set(value) {
        _builder.recoveryCaseId = value
      }
    /**
     * `string recovery_case_id = 1 [json_name = "recoveryCaseId"];`
     */
    public fun clearRecoveryCaseId() {
      _builder.clearRecoveryCaseId()
    }

    /**
     * `bool approved = 2 [json_name = "approved"];`
     */
    public var approved: kotlin.Boolean
      @kotlin.jvm.JvmName("getApproved")
        get() = _builder.approved
      @kotlin.jvm.JvmName("setApproved")
        set(value) {
        _builder.approved = value
      }
    /**
     * `bool approved = 2 [json_name = "approved"];`
     */
    public fun clearApproved() {
      _builder.clearApproved()
    }

    /**
     * `.threadline.type.v1.EncryptedField note = 3 [json_name = "note"];`
     */
    public var note: com.threadline.proto.threadline.type.v1.EncryptedField
      @kotlin.jvm.JvmName("getNote")
        get() = _builder.note
      @kotlin.jvm.JvmName("setNote")
        set(value) {
        _builder.note = value
      }
    /**
     * `.threadline.type.v1.EncryptedField note = 3 [json_name = "note"];`
     */
    public fun clearNote() {
      _builder.clearNote()
    }
    /**
     * `.threadline.type.v1.EncryptedField note = 3 [json_name = "note"];`
     * @return Whether the note field is set.
     */
    public fun hasNote(): kotlin.Boolean {
      return _builder.hasNote()
    }

    public val DecideTargetedRecoveryCaseRequestKt.Dsl.noteOrNull: com.threadline.proto.threadline.type.v1.EncryptedField?
      get() = _builder.noteOrNull

    /**
     * `string decision_id = 4 [json_name = "decisionId"];`
     */
    public var decisionId: kotlin.String
      @kotlin.jvm.JvmName("getDecisionId")
        get() = _builder.decisionId
      @kotlin.jvm.JvmName("setDecisionId")
        set(value) {
        _builder.decisionId = value
      }
    /**
     * `string decision_id = 4 [json_name = "decisionId"];`
     */
    public fun clearDecisionId() {
      _builder.clearDecisionId()
    }

    /**
     * `bytes case_binding_hash = 5 [json_name = "caseBindingHash"];`
     */
    public var caseBindingHash: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getCaseBindingHash")
        get() = _builder.caseBindingHash
      @kotlin.jvm.JvmName("setCaseBindingHash")
        set(value) {
        _builder.caseBindingHash = value
      }
    /**
     * `bytes case_binding_hash = 5 [json_name = "caseBindingHash"];`
     */
    public fun clearCaseBindingHash() {
      _builder.clearCaseBindingHash()
    }

    /**
     * `bytes decision_signature = 6 [json_name = "decisionSignature"];`
     */
    public var decisionSignature: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getDecisionSignature")
        get() = _builder.decisionSignature
      @kotlin.jvm.JvmName("setDecisionSignature")
        set(value) {
        _builder.decisionSignature = value
      }
    /**
     * `bytes decision_signature = 6 [json_name = "decisionSignature"];`
     */
    public fun clearDecisionSignature() {
      _builder.clearDecisionSignature()
    }

    /**
     * `string approver_device_id = 7 [json_name = "approverDeviceId"];`
     */
    public var approverDeviceId: kotlin.String
      @kotlin.jvm.JvmName("getApproverDeviceId")
        get() = _builder.approverDeviceId
      @kotlin.jvm.JvmName("setApproverDeviceId")
        set(value) {
        _builder.approverDeviceId = value
      }
    /**
     * `string approver_device_id = 7 [json_name = "approverDeviceId"];`
     */
    public fun clearApproverDeviceId() {
      _builder.clearApproverDeviceId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.threadline.proto.threadline.crypto.v1.DecideTargetedRecoveryCaseRequest.copy(block: `com.threadline.proto.threadline.crypto.v1`.DecideTargetedRecoveryCaseRequestKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.crypto.v1.DecideTargetedRecoveryCaseRequest =
  `com.threadline.proto.threadline.crypto.v1`.DecideTargetedRecoveryCaseRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.threadline.proto.threadline.crypto.v1.DecideTargetedRecoveryCaseRequestOrBuilder.noteOrNull: com.threadline.proto.threadline.type.v1.EncryptedField?
  get() = if (hasNote()) getNote() else null

