// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/crypto/v1/key_service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.threadline.proto.threadline.crypto.v1;

@kotlin.jvm.JvmName("-initializegetTargetedRecoveryCapabilitiesResponse")
public inline fun getTargetedRecoveryCapabilitiesResponse(block: com.threadline.proto.threadline.crypto.v1.GetTargetedRecoveryCapabilitiesResponseKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.crypto.v1.GetTargetedRecoveryCapabilitiesResponse =
  com.threadline.proto.threadline.crypto.v1.GetTargetedRecoveryCapabilitiesResponseKt.Dsl._create(com.threadline.proto.threadline.crypto.v1.GetTargetedRecoveryCapabilitiesResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `threadline.crypto.v1.GetTargetedRecoveryCapabilitiesResponse`
 */
public object GetTargetedRecoveryCapabilitiesResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.threadline.proto.threadline.crypto.v1.GetTargetedRecoveryCapabilitiesResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.threadline.proto.threadline.crypto.v1.GetTargetedRecoveryCapabilitiesResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.threadline.proto.threadline.crypto.v1.GetTargetedRecoveryCapabilitiesResponse = _builder.build()

    /**
     * `bool explicit_protected_targets = 1 [json_name = "explicitProtectedTargets"];`
     */
    public var explicitProtectedTargets: kotlin.Boolean
      @kotlin.jvm.JvmName("getExplicitProtectedTargets")
        get() = _builder.explicitProtectedTargets
      @kotlin.jvm.JvmName("setExplicitProtectedTargets")
        set(value) {
        _builder.explicitProtectedTargets = value
      }
    /**
     * `bool explicit_protected_targets = 1 [json_name = "explicitProtectedTargets"];`
     */
    public fun clearExplicitProtectedTargets() {
      _builder.clearExplicitProtectedTargets()
    }

    /**
     * `uint32 contract_version = 2 [json_name = "contractVersion"];`
     */
    public var contractVersion: kotlin.Int
      @kotlin.jvm.JvmName("getContractVersion")
        get() = _builder.contractVersion
      @kotlin.jvm.JvmName("setContractVersion")
        set(value) {
        _builder.contractVersion = value
      }
    /**
     * `uint32 contract_version = 2 [json_name = "contractVersion"];`
     */
    public fun clearContractVersion() {
      _builder.clearContractVersion()
    }

    /**
     * `.threadline.crypto.v1.RecoveryProtocolFloor protocol_floor = 3 [json_name = "protocolFloor"];`
     */
    public var protocolFloor: com.threadline.proto.threadline.crypto.v1.RecoveryProtocolFloor
      @kotlin.jvm.JvmName("getProtocolFloor")
        get() = _builder.protocolFloor
      @kotlin.jvm.JvmName("setProtocolFloor")
        set(value) {
        _builder.protocolFloor = value
      }
    /**
     * `.threadline.crypto.v1.RecoveryProtocolFloor protocol_floor = 3 [json_name = "protocolFloor"];`
     */
    public fun clearProtocolFloor() {
      _builder.clearProtocolFloor()
    }
    /**
     * `.threadline.crypto.v1.RecoveryProtocolFloor protocol_floor = 3 [json_name = "protocolFloor"];`
     * @return Whether the protocolFloor field is set.
     */
    public fun hasProtocolFloor(): kotlin.Boolean {
      return _builder.hasProtocolFloor()
    }

    public val GetTargetedRecoveryCapabilitiesResponseKt.Dsl.protocolFloorOrNull: com.threadline.proto.threadline.crypto.v1.RecoveryProtocolFloor?
      get() = _builder.protocolFloorOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.threadline.proto.threadline.crypto.v1.GetTargetedRecoveryCapabilitiesResponse.copy(block: `com.threadline.proto.threadline.crypto.v1`.GetTargetedRecoveryCapabilitiesResponseKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.crypto.v1.GetTargetedRecoveryCapabilitiesResponse =
  `com.threadline.proto.threadline.crypto.v1`.GetTargetedRecoveryCapabilitiesResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.threadline.proto.threadline.crypto.v1.GetTargetedRecoveryCapabilitiesResponseOrBuilder.protocolFloorOrNull: com.threadline.proto.threadline.crypto.v1.RecoveryProtocolFloor?
  get() = if (hasProtocolFloor()) getProtocolFloor() else null

