// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: threadline/crypto/v1/key_service.proto
//
package com.threadline.proto.threadline.crypto.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

/**
 *  MembershipService orders membership changes and authorizes a Committer
 *  Device to produce the corresponding MLS Commit.
 *
 *  The control plane owns the ordering of membership changes and holds no group
 *  keys. Concurrent changes are resolved by the sequence assigned here, not by
 *  whichever Commit lands first. The resulting opaque MlsWireMessage is sent
 *  through threadline.message.v1.MessageService.SendEvent, the single durable
 *  sequencing path; this service deliberately does not create a second write
 *  or ACK path.
 */
public interface MembershipServiceClientInterface {
  /**
   *  Records a membership change and returns an authorization naming the
   *  Committer Device, the expected Epoch and the KeyPackages to consume. The
   *  response contains no key material.
   */
  public suspend fun authorizeMembershipChange(request: AuthorizeMembershipChangeRequest, headers: Headers = emptyMap()): ResponseMessage<AuthorizeMembershipChangeResponse>

  /**
   *  Returns pending authorizations for the calling Device, so a Device that was
   *  offline picks up work it was elected to commit.
   */
  public suspend fun listPendingAuthorizations(request: ListPendingAuthorizationsRequest, headers: Headers = emptyMap()): ResponseMessage<ListPendingAuthorizationsResponse>
}
