// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/crypto/v1/recovery.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.threadline.proto.threadline.crypto.v1;

@kotlin.jvm.JvmName("-initializerecoveryScope")
public inline fun recoveryScope(block: com.threadline.proto.threadline.crypto.v1.RecoveryScopeKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.crypto.v1.RecoveryScope =
  com.threadline.proto.threadline.crypto.v1.RecoveryScopeKt.Dsl._create(com.threadline.proto.threadline.crypto.v1.RecoveryScope.newBuilder()).apply { block() }._build()
/**
 * ```
 * RecoveryScope is one explicit Group/Epoch/time slice. Scopes cannot be
 * inferred from tenant membership, and an empty scope list is invalid. For v1
 * N-1 dual-write compatibility, every scope in one Case has exactly the same
 * Epoch bounds and TimeRange; heterogeneous bounds fail closed and are never
 * widened into a union.
 * ```
 *
 * Protobuf type `threadline.crypto.v1.RecoveryScope`
 */
public object RecoveryScopeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.threadline.proto.threadline.crypto.v1.RecoveryScope.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.threadline.proto.threadline.crypto.v1.RecoveryScope.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.threadline.proto.threadline.crypto.v1.RecoveryScope = _builder.build()

    /**
     * `string e2ee_group_id = 1 [json_name = "e2eeGroupId"];`
     */
    public var e2EeGroupId: kotlin.String
      @kotlin.jvm.JvmName("getE2EeGroupId")
        get() = _builder.e2EeGroupId
      @kotlin.jvm.JvmName("setE2EeGroupId")
        set(value) {
        _builder.e2EeGroupId = value
      }
    /**
     * `string e2ee_group_id = 1 [json_name = "e2eeGroupId"];`
     */
    public fun clearE2EeGroupId() {
      _builder.clearE2EeGroupId()
    }

    /**
     * `uint64 first_epoch = 2 [json_name = "firstEpoch"];`
     */
    public var firstEpoch: kotlin.Long
      @kotlin.jvm.JvmName("getFirstEpoch")
        get() = _builder.firstEpoch
      @kotlin.jvm.JvmName("setFirstEpoch")
        set(value) {
        _builder.firstEpoch = value
      }
    /**
     * `uint64 first_epoch = 2 [json_name = "firstEpoch"];`
     */
    public fun clearFirstEpoch() {
      _builder.clearFirstEpoch()
    }

    /**
     * `uint64 last_epoch = 3 [json_name = "lastEpoch"];`
     */
    public var lastEpoch: kotlin.Long
      @kotlin.jvm.JvmName("getLastEpoch")
        get() = _builder.lastEpoch
      @kotlin.jvm.JvmName("setLastEpoch")
        set(value) {
        _builder.lastEpoch = value
      }
    /**
     * `uint64 last_epoch = 3 [json_name = "lastEpoch"];`
     */
    public fun clearLastEpoch() {
      _builder.clearLastEpoch()
    }

    /**
     * `.threadline.type.v1.TimeRange time_range = 4 [json_name = "timeRange"];`
     */
    public var timeRange: com.threadline.proto.threadline.type.v1.TimeRange
      @kotlin.jvm.JvmName("getTimeRange")
        get() = _builder.timeRange
      @kotlin.jvm.JvmName("setTimeRange")
        set(value) {
        _builder.timeRange = value
      }
    /**
     * `.threadline.type.v1.TimeRange time_range = 4 [json_name = "timeRange"];`
     */
    public fun clearTimeRange() {
      _builder.clearTimeRange()
    }
    /**
     * `.threadline.type.v1.TimeRange time_range = 4 [json_name = "timeRange"];`
     * @return Whether the timeRange field is set.
     */
    public fun hasTimeRange(): kotlin.Boolean {
      return _builder.hasTimeRange()
    }

    public val RecoveryScopeKt.Dsl.timeRangeOrNull: com.threadline.proto.threadline.type.v1.TimeRange?
      get() = _builder.timeRangeOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ProtectedTargetsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Exact object identities or bounded History ranges authorized inside this
     * Group/Epoch/time slice. Current v1 requires a non-empty list. Entries are
     * unique and sorted: objects by kind wire number then resource_id; History
     * by Group ID, first_epoch, then last_epoch. An object must match exactly;
     * an envelope History range must be contained by an approved target.
     * ```
     *
     * `repeated .threadline.crypto.v1.RecoveryProtectedScope protected_targets = 5 [json_name = "protectedTargets"];`
     */
     public val protectedTargets: com.google.protobuf.kotlin.DslList<com.threadline.proto.threadline.crypto.v1.RecoveryProtectedScope, ProtectedTargetsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.protectedTargetsList
      )
    /**
     * ```
     * Exact object identities or bounded History ranges authorized inside this
     * Group/Epoch/time slice. Current v1 requires a non-empty list. Entries are
     * unique and sorted: objects by kind wire number then resource_id; History
     * by Group ID, first_epoch, then last_epoch. An object must match exactly;
     * an envelope History range must be contained by an approved target.
     * ```
     *
     * `repeated .threadline.crypto.v1.RecoveryProtectedScope protected_targets = 5 [json_name = "protectedTargets"];`
     * @param value The protectedTargets to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addProtectedTargets")
    public fun com.google.protobuf.kotlin.DslList<com.threadline.proto.threadline.crypto.v1.RecoveryProtectedScope, ProtectedTargetsProxy>.add(value: com.threadline.proto.threadline.crypto.v1.RecoveryProtectedScope) {
      _builder.addProtectedTargets(value)
    }
    /**
     * ```
     * Exact object identities or bounded History ranges authorized inside this
     * Group/Epoch/time slice. Current v1 requires a non-empty list. Entries are
     * unique and sorted: objects by kind wire number then resource_id; History
     * by Group ID, first_epoch, then last_epoch. An object must match exactly;
     * an envelope History range must be contained by an approved target.
     * ```
     *
     * `repeated .threadline.crypto.v1.RecoveryProtectedScope protected_targets = 5 [json_name = "protectedTargets"];`
     * @param value The protectedTargets to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignProtectedTargets")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.threadline.proto.threadline.crypto.v1.RecoveryProtectedScope, ProtectedTargetsProxy>.plusAssign(value: com.threadline.proto.threadline.crypto.v1.RecoveryProtectedScope) {
      add(value)
    }
    /**
     * ```
     * Exact object identities or bounded History ranges authorized inside this
     * Group/Epoch/time slice. Current v1 requires a non-empty list. Entries are
     * unique and sorted: objects by kind wire number then resource_id; History
     * by Group ID, first_epoch, then last_epoch. An object must match exactly;
     * an envelope History range must be contained by an approved target.
     * ```
     *
     * `repeated .threadline.crypto.v1.RecoveryProtectedScope protected_targets = 5 [json_name = "protectedTargets"];`
     * @param values The protectedTargets to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllProtectedTargets")
    public fun com.google.protobuf.kotlin.DslList<com.threadline.proto.threadline.crypto.v1.RecoveryProtectedScope, ProtectedTargetsProxy>.addAll(values: kotlin.collections.Iterable<com.threadline.proto.threadline.crypto.v1.RecoveryProtectedScope>) {
      _builder.addAllProtectedTargets(values)
    }
    /**
     * ```
     * Exact object identities or bounded History ranges authorized inside this
     * Group/Epoch/time slice. Current v1 requires a non-empty list. Entries are
     * unique and sorted: objects by kind wire number then resource_id; History
     * by Group ID, first_epoch, then last_epoch. An object must match exactly;
     * an envelope History range must be contained by an approved target.
     * ```
     *
     * `repeated .threadline.crypto.v1.RecoveryProtectedScope protected_targets = 5 [json_name = "protectedTargets"];`
     * @param values The protectedTargets to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllProtectedTargets")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.threadline.proto.threadline.crypto.v1.RecoveryProtectedScope, ProtectedTargetsProxy>.plusAssign(values: kotlin.collections.Iterable<com.threadline.proto.threadline.crypto.v1.RecoveryProtectedScope>) {
      addAll(values)
    }
    /**
     * ```
     * Exact object identities or bounded History ranges authorized inside this
     * Group/Epoch/time slice. Current v1 requires a non-empty list. Entries are
     * unique and sorted: objects by kind wire number then resource_id; History
     * by Group ID, first_epoch, then last_epoch. An object must match exactly;
     * an envelope History range must be contained by an approved target.
     * ```
     *
     * `repeated .threadline.crypto.v1.RecoveryProtectedScope protected_targets = 5 [json_name = "protectedTargets"];`
     * @param index The index to set the value at.
     * @param value The protectedTargets to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setProtectedTargets")
    public operator fun com.google.protobuf.kotlin.DslList<com.threadline.proto.threadline.crypto.v1.RecoveryProtectedScope, ProtectedTargetsProxy>.set(index: kotlin.Int, value: com.threadline.proto.threadline.crypto.v1.RecoveryProtectedScope) {
      _builder.setProtectedTargets(index, value)
    }
    /**
     * ```
     * Exact object identities or bounded History ranges authorized inside this
     * Group/Epoch/time slice. Current v1 requires a non-empty list. Entries are
     * unique and sorted: objects by kind wire number then resource_id; History
     * by Group ID, first_epoch, then last_epoch. An object must match exactly;
     * an envelope History range must be contained by an approved target.
     * ```
     *
     * `repeated .threadline.crypto.v1.RecoveryProtectedScope protected_targets = 5 [json_name = "protectedTargets"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearProtectedTargets")
    public fun com.google.protobuf.kotlin.DslList<com.threadline.proto.threadline.crypto.v1.RecoveryProtectedScope, ProtectedTargetsProxy>.clear() {
      _builder.clearProtectedTargets()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.threadline.proto.threadline.crypto.v1.RecoveryScope.copy(block: `com.threadline.proto.threadline.crypto.v1`.RecoveryScopeKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.crypto.v1.RecoveryScope =
  `com.threadline.proto.threadline.crypto.v1`.RecoveryScopeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.threadline.proto.threadline.crypto.v1.RecoveryScopeOrBuilder.timeRangeOrNull: com.threadline.proto.threadline.type.v1.TimeRange?
  get() = if (hasTimeRange()) getTimeRange() else null

