// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/capability/v1/capability.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.capability.v1;

@com.google.protobuf.Generated
public interface CapabilityGrantOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threadline.capability.v1.CapabilityGrant)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string capability_grant_id = 1 [json_name = "capabilityGrantId"];</code>
   * @return The capabilityGrantId.
   */
  java.lang.String getCapabilityGrantId();
  /**
   * <code>string capability_grant_id = 1 [json_name = "capabilityGrantId"];</code>
   * @return The bytes for capabilityGrantId.
   */
  com.google.protobuf.ByteString
      getCapabilityGrantIdBytes();

  /**
   * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <pre>
   * The Task this Grant serves. A Grant is always Task-bound; there is no
   * standing Grant.
   * </pre>
   *
   * <code>string task_id = 3 [json_name = "taskId"];</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <pre>
   * The Task this Grant serves. A Grant is always Task-bound; there is no
   * standing Grant.
   * </pre>
   *
   * <code>string task_id = 3 [json_name = "taskId"];</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <pre>
   * The Run, when the Grant is narrowed to a single execution attempt.
   * </pre>
   *
   * <code>string run_id = 4 [json_name = "runId"];</code>
   * @return The runId.
   */
  java.lang.String getRunId();
  /**
   * <pre>
   * The Run, when the Grant is narrowed to a single execution attempt.
   * </pre>
   *
   * <code>string run_id = 4 [json_name = "runId"];</code>
   * @return The bytes for runId.
   */
  com.google.protobuf.ByteString
      getRunIdBytes();

  /**
   * <pre>
   * The Actor authorized to act, normally an Agent Actor.
   * </pre>
   *
   * <code>.threadline.type.v1.ActorRef grantee = 5 [json_name = "grantee"];</code>
   * @return Whether the grantee field is set.
   */
  boolean hasGrantee();
  /**
   * <pre>
   * The Actor authorized to act, normally an Agent Actor.
   * </pre>
   *
   * <code>.threadline.type.v1.ActorRef grantee = 5 [json_name = "grantee"];</code>
   * @return The grantee.
   */
  com.threadline.proto.threadline.type.v1.ActorRef getGrantee();
  /**
   * <pre>
   * The Actor authorized to act, normally an Agent Actor.
   * </pre>
   *
   * <code>.threadline.type.v1.ActorRef grantee = 5 [json_name = "grantee"];</code>
   */
  com.threadline.proto.threadline.type.v1.ActorRefOrBuilder getGranteeOrBuilder();

  /**
   * <pre>
   * The Human whose authority is being delegated. The Grant cannot exceed what
   * this Actor could do themselves.
   * </pre>
   *
   * <code>.threadline.type.v1.ActorRef initiator = 6 [json_name = "initiator"];</code>
   * @return Whether the initiator field is set.
   */
  boolean hasInitiator();
  /**
   * <pre>
   * The Human whose authority is being delegated. The Grant cannot exceed what
   * this Actor could do themselves.
   * </pre>
   *
   * <code>.threadline.type.v1.ActorRef initiator = 6 [json_name = "initiator"];</code>
   * @return The initiator.
   */
  com.threadline.proto.threadline.type.v1.ActorRef getInitiator();
  /**
   * <pre>
   * The Human whose authority is being delegated. The Grant cannot exceed what
   * this Actor could do themselves.
   * </pre>
   *
   * <code>.threadline.type.v1.ActorRef initiator = 6 [json_name = "initiator"];</code>
   */
  com.threadline.proto.threadline.type.v1.ActorRefOrBuilder getInitiatorOrBuilder();

  /**
   * <code>repeated .threadline.capability.v1.Capability capabilities = 7 [json_name = "capabilities"];</code>
   * @return A list containing the capabilities.
   */
  java.util.List<com.threadline.proto.threadline.capability.v1.Capability> getCapabilitiesList();
  /**
   * <code>repeated .threadline.capability.v1.Capability capabilities = 7 [json_name = "capabilities"];</code>
   * @return The count of capabilities.
   */
  int getCapabilitiesCount();
  /**
   * <code>repeated .threadline.capability.v1.Capability capabilities = 7 [json_name = "capabilities"];</code>
   * @param index The index of the element to return.
   * @return The capabilities at the given index.
   */
  com.threadline.proto.threadline.capability.v1.Capability getCapabilities(int index);
  /**
   * <code>repeated .threadline.capability.v1.Capability capabilities = 7 [json_name = "capabilities"];</code>
   * @return A list containing the enum numeric values on the wire for capabilities.
   */
  java.util.List<java.lang.Integer>
  getCapabilitiesValueList();
  /**
   * <code>repeated .threadline.capability.v1.Capability capabilities = 7 [json_name = "capabilities"];</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of capabilities at the given index.
   */
  int getCapabilitiesValue(int index);

  /**
   * <code>.threadline.capability.v1.ResourceScope scope = 8 [json_name = "scope"];</code>
   * @return Whether the scope field is set.
   */
  boolean hasScope();
  /**
   * <code>.threadline.capability.v1.ResourceScope scope = 8 [json_name = "scope"];</code>
   * @return The scope.
   */
  com.threadline.proto.threadline.capability.v1.ResourceScope getScope();
  /**
   * <code>.threadline.capability.v1.ResourceScope scope = 8 [json_name = "scope"];</code>
   */
  com.threadline.proto.threadline.capability.v1.ResourceScopeOrBuilder getScopeOrBuilder();

  /**
   * <code>.threadline.capability.v1.GrantState state = 9 [json_name = "state"];</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <code>.threadline.capability.v1.GrantState state = 9 [json_name = "state"];</code>
   * @return The state.
   */
  com.threadline.proto.threadline.capability.v1.GrantState getState();

  /**
   * <code>.google.protobuf.Timestamp issued_at = 10 [json_name = "issuedAt"];</code>
   * @return Whether the issuedAt field is set.
   */
  boolean hasIssuedAt();
  /**
   * <code>.google.protobuf.Timestamp issued_at = 10 [json_name = "issuedAt"];</code>
   * @return The issuedAt.
   */
  com.google.protobuf.Timestamp getIssuedAt();
  /**
   * <code>.google.protobuf.Timestamp issued_at = 10 [json_name = "issuedAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getIssuedAtOrBuilder();

  /**
   * <pre>
   * Grants are short-lived by design. An expired Grant is not renewed in place;
   * a new one is issued and audited.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expires_at = 11 [json_name = "expiresAt"];</code>
   * @return Whether the expiresAt field is set.
   */
  boolean hasExpiresAt();
  /**
   * <pre>
   * Grants are short-lived by design. An expired Grant is not renewed in place;
   * a new one is issued and audited.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expires_at = 11 [json_name = "expiresAt"];</code>
   * @return The expiresAt.
   */
  com.google.protobuf.Timestamp getExpiresAt();
  /**
   * <pre>
   * Grants are short-lived by design. An expired Grant is not renewed in place;
   * a new one is issued and audited.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expires_at = 11 [json_name = "expiresAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpiresAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp revoked_at = 12 [json_name = "revokedAt"];</code>
   * @return Whether the revokedAt field is set.
   */
  boolean hasRevokedAt();
  /**
   * <code>.google.protobuf.Timestamp revoked_at = 12 [json_name = "revokedAt"];</code>
   * @return The revokedAt.
   */
  com.google.protobuf.Timestamp getRevokedAt();
  /**
   * <code>.google.protobuf.Timestamp revoked_at = 12 [json_name = "revokedAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getRevokedAtOrBuilder();

  /**
   * <pre>
   * Unique value binding this Grant to one issuance. It prevents transcript
   * substitution but is not a replay cache: use-time Core state recheck is what
   * rejects a captured Grant after revocation.
   * </pre>
   *
   * <code>bytes nonce = 13 [json_name = "nonce"];</code>
   * @return The nonce.
   */
  com.google.protobuf.ByteString getNonce();

  /**
   * <pre>
   * Policy version that authorized issuance, retained so a decision stays
   * explainable after policy changes.
   * </pre>
   *
   * <code>string policy_version = 14 [json_name = "policyVersion"];</code>
   * @return The policyVersion.
   */
  java.lang.String getPolicyVersion();
  /**
   * <pre>
   * Policy version that authorized issuance, retained so a decision stays
   * explainable after policy changes.
   * </pre>
   *
   * <code>string policy_version = 14 [json_name = "policyVersion"];</code>
   * @return The bytes for policyVersion.
   */
  com.google.protobuf.ByteString
      getPolicyVersionBytes();

  /**
   * <pre>
   * Control plane Ed25519 signature over the immutable v1 signed projection.
   * The projection includes fields 1-8, 10-11, 13-14 and 16-19; it excludes
   * mutable lifecycle fields 9 and 12 and these signature bytes. See
   * docs/architecture/capability-grant-signature-contract.md. connectord and
   * locald verify the signature locally before honoring the Grant, so a
   * compromised agentd cannot mint authority for itself. Signature validity is
   * not revocation evidence: every protected use still rechecks Core state.
   * </pre>
   *
   * <code>bytes signature = 15 [json_name = "signature"];</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();

  /**
   * <pre>
   * Device selected as the Execution Owner for this Run. Before any use, the
   * verifier compares this signed claim with an independently authenticated
   * current Device identity. Signing a caller-supplied Device ID alone does not
   * establish Device identity or prevent replay.
   * </pre>
   *
   * <code>string execution_device_id = 16 [json_name = "executionDeviceId"];</code>
   * @return The executionDeviceId.
   */
  java.lang.String getExecutionDeviceId();
  /**
   * <pre>
   * Device selected as the Execution Owner for this Run. Before any use, the
   * verifier compares this signed claim with an independently authenticated
   * current Device identity. Signing a caller-supplied Device ID alone does not
   * establish Device identity or prevent replay.
   * </pre>
   *
   * <code>string execution_device_id = 16 [json_name = "executionDeviceId"];</code>
   * @return The bytes for executionDeviceId.
   */
  com.google.protobuf.ByteString
      getExecutionDeviceIdBytes();

  /**
   * <code>.threadline.capability.v1.CapabilityGrantSignatureProfile signature_profile = 17 [json_name = "signatureProfile"];</code>
   * @return The enum numeric value on the wire for signatureProfile.
   */
  int getSignatureProfileValue();
  /**
   * <code>.threadline.capability.v1.CapabilityGrantSignatureProfile signature_profile = 17 [json_name = "signatureProfile"];</code>
   * @return The signatureProfile.
   */
  com.threadline.proto.threadline.capability.v1.CapabilityGrantSignatureProfile getSignatureProfile();

  /**
   * <pre>
   * Tenant-scoped identifier of the control-plane verification key. The key
   * identifier is signed and selects a trusted key-ring entry; it never carries
   * private key material or authorizes an unknown key.
   * </pre>
   *
   * <code>string signing_key_id = 18 [json_name = "signingKeyId"];</code>
   * @return The signingKeyId.
   */
  java.lang.String getSigningKeyId();
  /**
   * <pre>
   * Tenant-scoped identifier of the control-plane verification key. The key
   * identifier is signed and selects a trusted key-ring entry; it never carries
   * private key material or authorizes an unknown key.
   * </pre>
   *
   * <code>string signing_key_id = 18 [json_name = "signingKeyId"];</code>
   * @return The bytes for signingKeyId.
   */
  com.google.protobuf.ByteString
      getSigningKeyIdBytes();

  /**
   * <pre>
   * Exact signed-projection schema version. v1 requires 1. This is independent
   * of the protobuf package version so transcript evolution remains explicit.
   * </pre>
   *
   * <code>uint32 signed_projection_version = 19 [json_name = "signedProjectionVersion"];</code>
   * @return The signedProjectionVersion.
   */
  int getSignedProjectionVersion();
}
