// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/capability/v1/capability.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.capability.v1;

/**
 * <pre>
 * GrantState is the Capability Grant lifecycle.
 *
 * ACTIVE -&gt; EXPIRED
 * |
 * +---&gt; REVOKED
 *
 * Both terminal states take effect on the next check, not at the next refresh.
 * A Grant revoked mid-Run causes the Runtime's next protected action to fail.
 * </pre>
 *
 * Protobuf enum {@code threadline.capability.v1.GrantState}
 */
@com.google.protobuf.Generated
public enum GrantState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>GRANT_STATE_UNSPECIFIED = 0;</code>
   */
  GRANT_STATE_UNSPECIFIED(0),
  /**
   * <code>GRANT_STATE_ACTIVE = 1;</code>
   */
  GRANT_STATE_ACTIVE(1),
  /**
   * <code>GRANT_STATE_EXPIRED = 2;</code>
   */
  GRANT_STATE_EXPIRED(2),
  /**
   * <code>GRANT_STATE_REVOKED = 3;</code>
   */
  GRANT_STATE_REVOKED(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "GrantState");
  }
  /**
   * <code>GRANT_STATE_UNSPECIFIED = 0;</code>
   */
  public static final int GRANT_STATE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>GRANT_STATE_ACTIVE = 1;</code>
   */
  public static final int GRANT_STATE_ACTIVE_VALUE = 1;
  /**
   * <code>GRANT_STATE_EXPIRED = 2;</code>
   */
  public static final int GRANT_STATE_EXPIRED_VALUE = 2;
  /**
   * <code>GRANT_STATE_REVOKED = 3;</code>
   */
  public static final int GRANT_STATE_REVOKED_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static GrantState valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static GrantState forNumber(int value) {
    switch (value) {
      case 0: return GRANT_STATE_UNSPECIFIED;
      case 1: return GRANT_STATE_ACTIVE;
      case 2: return GRANT_STATE_EXPIRED;
      case 3: return GRANT_STATE_REVOKED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GrantState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      GrantState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GrantState>() {
          public GrantState findValueByNumber(int number) {
            return GrantState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.threadline.proto.threadline.capability.v1.CapabilityProto.getDescriptor().getEnumType(1);
  }

  private static final GrantState[] VALUES = values();

  public static GrantState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private GrantState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:threadline.capability.v1.GrantState)
}

