// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/runtime/v1/runtime_service.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.runtime.v1;

@com.google.protobuf.Generated
public interface CompleteRunResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threadline.runtime.v1.CompleteRunResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.threadline.task.v1.Run run = 1 [json_name = "run"];</code>
   * @return Whether the run field is set.
   */
  boolean hasRun();
  /**
   * <code>.threadline.task.v1.Run run = 1 [json_name = "run"];</code>
   * @return The run.
   */
  com.threadline.proto.threadline.task.v1.Run getRun();
  /**
   * <code>.threadline.task.v1.Run run = 1 [json_name = "run"];</code>
   */
  com.threadline.proto.threadline.task.v1.RunOrBuilder getRunOrBuilder();
}
