// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/runtime/v1/runtime_service.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.runtime.v1;

@com.google.protobuf.Generated
public interface ListRuntimesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threadline.runtime.v1.ListRuntimesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .threadline.runtime.v1.RuntimeInstance runtimes = 1 [json_name = "runtimes"];</code>
   */
  java.util.List<com.threadline.proto.threadline.runtime.v1.RuntimeInstance> 
      getRuntimesList();
  /**
   * <code>repeated .threadline.runtime.v1.RuntimeInstance runtimes = 1 [json_name = "runtimes"];</code>
   */
  com.threadline.proto.threadline.runtime.v1.RuntimeInstance getRuntimes(int index);
  /**
   * <code>repeated .threadline.runtime.v1.RuntimeInstance runtimes = 1 [json_name = "runtimes"];</code>
   */
  int getRuntimesCount();
  /**
   * <code>repeated .threadline.runtime.v1.RuntimeInstance runtimes = 1 [json_name = "runtimes"];</code>
   */
  java.util.List<? extends com.threadline.proto.threadline.runtime.v1.RuntimeInstanceOrBuilder> 
      getRuntimesOrBuilderList();
  /**
   * <code>repeated .threadline.runtime.v1.RuntimeInstance runtimes = 1 [json_name = "runtimes"];</code>
   */
  com.threadline.proto.threadline.runtime.v1.RuntimeInstanceOrBuilder getRuntimesOrBuilder(
      int index);

  /**
   * <code>.threadline.type.v1.PageResponse page = 2 [json_name = "page"];</code>
   * @return Whether the page field is set.
   */
  boolean hasPage();
  /**
   * <code>.threadline.type.v1.PageResponse page = 2 [json_name = "page"];</code>
   * @return The page.
   */
  com.threadline.proto.threadline.type.v1.PageResponse getPage();
  /**
   * <code>.threadline.type.v1.PageResponse page = 2 [json_name = "page"];</code>
   */
  com.threadline.proto.threadline.type.v1.PageResponseOrBuilder getPageOrBuilder();
}
