// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/runtime/v1/runtime_service.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.runtime.v1;

@com.google.protobuf.Generated
public interface RequestApprovalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threadline.runtime.v1.RequestApprovalResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string approval_id = 1 [json_name = "approvalId"];</code>
   * @return The approvalId.
   */
  java.lang.String getApprovalId();
  /**
   * <code>string approval_id = 1 [json_name = "approvalId"];</code>
   * @return The bytes for approvalId.
   */
  com.google.protobuf.ByteString
      getApprovalIdBytes();
}
