// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactional_outbox.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeTransactionalOutboxPublished = `-- name: AcknowledgeTransactionalOutboxPublished :one
SELECT domain.acknowledge_transactional_outbox_published(
  $1::text,
  $2::text,
  $3::bigint,
  $4::bigint,
  $5::bigint,
  $6::text,
  $7::bytea,
  $8::text,
  $9::numeric,
  $10::boolean,
  $11::text
) AS result_code
`

type AcknowledgeTransactionalOutboxPublishedParams struct {
	TenantID          string
	EventID           string
	OutboxEntryID     int64
	DeliveryAttemptID int64
	ReplayGeneration  int64
	ClaimOwnerID      string
	CandidateDigest   []byte
	BrokerStream      string
	BrokerSequence    pgtype.Numeric
	BrokerDuplicate   bool
	BrokerMessageID   string
}

func (q *Queries) AcknowledgeTransactionalOutboxPublished(ctx context.Context, arg AcknowledgeTransactionalOutboxPublishedParams) (string, error) {
	row := q.db.QueryRow(ctx, acknowledgeTransactionalOutboxPublished,
		arg.TenantID,
		arg.EventID,
		arg.OutboxEntryID,
		arg.DeliveryAttemptID,
		arg.ReplayGeneration,
		arg.ClaimOwnerID,
		arg.CandidateDigest,
		arg.BrokerStream,
		arg.BrokerSequence,
		arg.BrokerDuplicate,
		arg.BrokerMessageID,
	)
	var result_code string
	err := row.Scan(&result_code)
	return result_code, err
}

const claimTransactionalOutboxBatch = `-- name: ClaimTransactionalOutboxBatch :many
WITH claimed AS (
  SELECT domain.claim_transactional_outbox_batch(
    $1::text,
    $2::integer
  )::domain.transactional_outbox_claim_result AS value
)
SELECT
  ((claimed.value).result_code)::text AS result_code,
  ((claimed.value).tenant_id)::text AS tenant_id,
  ((claimed.value).event_id)::text AS event_id,
  ((claimed.value).outbox_entry_id)::bigint AS outbox_entry_id,
  ((claimed.value).delivery_attempt_id)::bigint AS delivery_attempt_id,
  ((claimed.value).replay_generation)::bigint AS replay_generation,
  ((claimed.value).total_attempt_number)::bigint AS total_attempt_number,
  ((claimed.value).generation_attempt_number)::bigint AS generation_attempt_number,
  ((claimed.value).claim_owner_id)::text AS claim_owner_id,
  ((claimed.value).raw_claim_token)::bytea AS raw_claim_token,
  ((claimed.value).claimed_at)::timestamp with time zone AS claimed_at,
  ((claimed.value).lease_expires_at)::timestamp with time zone AS lease_expires_at,
  ((claimed.value).absolute_lease_expires_at)::timestamp with time zone AS absolute_lease_expires_at,
  ((claimed.value).broker_message_id)::text AS broker_message_id,
  ((claimed.value).destination)::text AS destination,
  ((claimed.value).event_type)::text AS event_type,
  ((claimed.value).schema_version)::integer AS schema_version,
  ((claimed.value).aggregate_kind)::text AS aggregate_kind,
  ((claimed.value).aggregate_id)::text AS aggregate_id,
  ((claimed.value).payload)::bytea AS payload,
  ((claimed.value).occurred_at)::timestamp with time zone AS occurred_at,
  ((claimed.value).enqueued_at)::timestamp with time zone AS enqueued_at,
  ((claimed.value).policy_id)::text AS policy_id,
  ((claimed.value).policy_snapshot_digest)::bytea AS policy_snapshot_digest
FROM claimed
`

type ClaimTransactionalOutboxBatchParams struct {
	ClaimOwnerID string
	BatchSize    int32
}

type ClaimTransactionalOutboxBatchRow struct {
	ResultCode              string
	TenantID                string
	EventID                 string
	OutboxEntryID           int64
	DeliveryAttemptID       int64
	ReplayGeneration        int64
	TotalAttemptNumber      int64
	GenerationAttemptNumber int64
	ClaimOwnerID            string
	RawClaimToken           []byte
	ClaimedAt               pgtype.Timestamptz
	LeaseExpiresAt          pgtype.Timestamptz
	AbsoluteLeaseExpiresAt  pgtype.Timestamptz
	BrokerMessageID         string
	Destination             string
	EventType               string
	SchemaVersion           int32
	AggregateKind           string
	AggregateID             string
	Payload                 []byte
	OccurredAt              pgtype.Timestamptz
	EnqueuedAt              pgtype.Timestamptz
	PolicyID                string
	PolicySnapshotDigest    []byte
}

func (q *Queries) ClaimTransactionalOutboxBatch(ctx context.Context, arg ClaimTransactionalOutboxBatchParams) ([]ClaimTransactionalOutboxBatchRow, error) {
	rows, err := q.db.Query(ctx, claimTransactionalOutboxBatch, arg.ClaimOwnerID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimTransactionalOutboxBatchRow{}
	for rows.Next() {
		var i ClaimTransactionalOutboxBatchRow
		if err := rows.Scan(
			&i.ResultCode,
			&i.TenantID,
			&i.EventID,
			&i.OutboxEntryID,
			&i.DeliveryAttemptID,
			&i.ReplayGeneration,
			&i.TotalAttemptNumber,
			&i.GenerationAttemptNumber,
			&i.ClaimOwnerID,
			&i.RawClaimToken,
			&i.ClaimedAt,
			&i.LeaseExpiresAt,
			&i.AbsoluteLeaseExpiresAt,
			&i.BrokerMessageID,
			&i.Destination,
			&i.EventType,
			&i.SchemaVersion,
			&i.AggregateKind,
			&i.AggregateID,
			&i.Payload,
			&i.OccurredAt,
			&i.EnqueuedAt,
			&i.PolicyID,
			&i.PolicySnapshotDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTransactionalOutboxPublishFailure = `-- name: RecordTransactionalOutboxPublishFailure :one
WITH failed AS (
  SELECT domain.record_transactional_outbox_publish_failure(
    $1::text,
    $2::text,
    $3::bigint,
    $4::bigint,
    $5::bigint,
    $6::text,
    $7::bytea,
    $8::text
  )::domain.transactional_outbox_failure_result AS value
)
SELECT
  ((failed.value).result_code)::text AS result_code,
  ((failed.value).next_attempt_at)::timestamp with time zone AS next_attempt_at
FROM failed
`

type RecordTransactionalOutboxPublishFailureParams struct {
	TenantID          string
	EventID           string
	OutboxEntryID     int64
	DeliveryAttemptID int64
	ReplayGeneration  int64
	ClaimOwnerID      string
	CandidateDigest   []byte
	FailureCode       string
}

type RecordTransactionalOutboxPublishFailureRow struct {
	ResultCode    string
	NextAttemptAt pgtype.Timestamptz
}

func (q *Queries) RecordTransactionalOutboxPublishFailure(ctx context.Context, arg RecordTransactionalOutboxPublishFailureParams) (RecordTransactionalOutboxPublishFailureRow, error) {
	row := q.db.QueryRow(ctx, recordTransactionalOutboxPublishFailure,
		arg.TenantID,
		arg.EventID,
		arg.OutboxEntryID,
		arg.DeliveryAttemptID,
		arg.ReplayGeneration,
		arg.ClaimOwnerID,
		arg.CandidateDigest,
		arg.FailureCode,
	)
	var i RecordTransactionalOutboxPublishFailureRow
	err := row.Scan(&i.ResultCode, &i.NextAttemptAt)
	return i, err
}

const renewTransactionalOutboxClaim = `-- name: RenewTransactionalOutboxClaim :one
WITH renewed AS (
  SELECT domain.renew_transactional_outbox_claim(
    $1::text,
    $2::text,
    $3::bigint,
    $4::bigint,
    $5::bigint,
    $6::text,
    $7::bytea
  )::domain.transactional_outbox_renew_result AS value
)
SELECT
  ((renewed.value).result_code)::text AS result_code,
  ((renewed.value).lease_expires_at)::timestamp with time zone AS lease_expires_at
FROM renewed
`

type RenewTransactionalOutboxClaimParams struct {
	TenantID          string
	EventID           string
	OutboxEntryID     int64
	DeliveryAttemptID int64
	ReplayGeneration  int64
	ClaimOwnerID      string
	CandidateDigest   []byte
}

type RenewTransactionalOutboxClaimRow struct {
	ResultCode     string
	LeaseExpiresAt pgtype.Timestamptz
}

func (q *Queries) RenewTransactionalOutboxClaim(ctx context.Context, arg RenewTransactionalOutboxClaimParams) (RenewTransactionalOutboxClaimRow, error) {
	row := q.db.QueryRow(ctx, renewTransactionalOutboxClaim,
		arg.TenantID,
		arg.EventID,
		arg.OutboxEntryID,
		arg.DeliveryAttemptID,
		arg.ReplayGeneration,
		arg.ClaimOwnerID,
		arg.CandidateDigest,
	)
	var i RenewTransactionalOutboxClaimRow
	err := row.Scan(&i.ResultCode, &i.LeaseExpiresAt)
	return i, err
}
