// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/task/v1/task_service.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.task.v1;

/**
 * Protobuf type {@code threadline.task.v1.StreamRunEventsRequest}
 */
@com.google.protobuf.Generated
public final class StreamRunEventsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:threadline.task.v1.StreamRunEventsRequest)
    StreamRunEventsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "StreamRunEventsRequest");
  }
  // Use StreamRunEventsRequest.newBuilder() to construct.
  private StreamRunEventsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StreamRunEventsRequest() {
    runId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.threadline.proto.threadline.task.v1.TaskServiceProto.internal_static_threadline_task_v1_StreamRunEventsRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.threadline.proto.threadline.task.v1.TaskServiceProto.internal_static_threadline_task_v1_StreamRunEventsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.threadline.proto.threadline.task.v1.TaskServiceProto.internal_static_threadline_task_v1_StreamRunEventsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.threadline.proto.threadline.task.v1.StreamRunEventsRequest.class, com.threadline.proto.threadline.task.v1.StreamRunEventsRequest.Builder.class);
  }

  public static final int RUN_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object runId_ = "";
  /**
   * <code>string run_id = 1 [json_name = "runId"];</code>
   * @return The runId.
   */
  @java.lang.Override
  public java.lang.String getRunId() {
    java.lang.Object ref = runId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      runId_ = s;
      return s;
    }
  }
  /**
   * <code>string run_id = 1 [json_name = "runId"];</code>
   * @return The bytes for runId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRunIdBytes() {
    java.lang.Object ref = runId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      runId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AFTER_SEQUENCE_FIELD_NUMBER = 2;
  private long afterSequence_ = 0L;
  /**
   * <pre>
   * Resume position. Returns events with `sequence` strictly greater.
   * </pre>
   *
   * <code>uint64 after_sequence = 2 [json_name = "afterSequence"];</code>
   * @return The afterSequence.
   */
  @java.lang.Override
  public long getAfterSequence() {
    return afterSequence_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(runId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, runId_);
    }
    if (afterSequence_ != 0L) {
      output.writeUInt64(2, afterSequence_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(runId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, runId_);
    }
    if (afterSequence_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, afterSequence_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.threadline.proto.threadline.task.v1.StreamRunEventsRequest)) {
      return super.equals(obj);
    }
    com.threadline.proto.threadline.task.v1.StreamRunEventsRequest other = (com.threadline.proto.threadline.task.v1.StreamRunEventsRequest) obj;

    if (!getRunId()
        .equals(other.getRunId())) return false;
    if (getAfterSequence()
        != other.getAfterSequence()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RUN_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRunId().hashCode();
    hash = (37 * hash) + AFTER_SEQUENCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAfterSequence());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.threadline.proto.threadline.task.v1.StreamRunEventsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.task.v1.StreamRunEventsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.task.v1.StreamRunEventsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.task.v1.StreamRunEventsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.task.v1.StreamRunEventsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.task.v1.StreamRunEventsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.task.v1.StreamRunEventsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.threadline.proto.threadline.task.v1.StreamRunEventsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.threadline.proto.threadline.task.v1.StreamRunEventsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.threadline.proto.threadline.task.v1.StreamRunEventsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.threadline.proto.threadline.task.v1.StreamRunEventsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.threadline.proto.threadline.task.v1.StreamRunEventsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.threadline.proto.threadline.task.v1.StreamRunEventsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code threadline.task.v1.StreamRunEventsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:threadline.task.v1.StreamRunEventsRequest)
      com.threadline.proto.threadline.task.v1.StreamRunEventsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.threadline.proto.threadline.task.v1.TaskServiceProto.internal_static_threadline_task_v1_StreamRunEventsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.threadline.proto.threadline.task.v1.TaskServiceProto.internal_static_threadline_task_v1_StreamRunEventsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.threadline.proto.threadline.task.v1.StreamRunEventsRequest.class, com.threadline.proto.threadline.task.v1.StreamRunEventsRequest.Builder.class);
    }

    // Construct using com.threadline.proto.threadline.task.v1.StreamRunEventsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      runId_ = "";
      afterSequence_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.threadline.proto.threadline.task.v1.TaskServiceProto.internal_static_threadline_task_v1_StreamRunEventsRequest_descriptor;
    }

    @java.lang.Override
    public com.threadline.proto.threadline.task.v1.StreamRunEventsRequest getDefaultInstanceForType() {
      return com.threadline.proto.threadline.task.v1.StreamRunEventsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.threadline.proto.threadline.task.v1.StreamRunEventsRequest build() {
      com.threadline.proto.threadline.task.v1.StreamRunEventsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.threadline.proto.threadline.task.v1.StreamRunEventsRequest buildPartial() {
      com.threadline.proto.threadline.task.v1.StreamRunEventsRequest result = new com.threadline.proto.threadline.task.v1.StreamRunEventsRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.threadline.proto.threadline.task.v1.StreamRunEventsRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.runId_ = runId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.afterSequence_ = afterSequence_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.threadline.proto.threadline.task.v1.StreamRunEventsRequest) {
        return mergeFrom((com.threadline.proto.threadline.task.v1.StreamRunEventsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.threadline.proto.threadline.task.v1.StreamRunEventsRequest other) {
      if (other == com.threadline.proto.threadline.task.v1.StreamRunEventsRequest.getDefaultInstance()) return this;
      if (!other.getRunId().isEmpty()) {
        runId_ = other.runId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getAfterSequence() != 0L) {
        setAfterSequence(other.getAfterSequence());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              runId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              afterSequence_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object runId_ = "";
    /**
     * <code>string run_id = 1 [json_name = "runId"];</code>
     * @return The runId.
     */
    public java.lang.String getRunId() {
      java.lang.Object ref = runId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        runId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string run_id = 1 [json_name = "runId"];</code>
     * @return The bytes for runId.
     */
    public com.google.protobuf.ByteString
        getRunIdBytes() {
      java.lang.Object ref = runId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        runId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string run_id = 1 [json_name = "runId"];</code>
     * @param value The runId to set.
     * @return This builder for chaining.
     */
    public Builder setRunId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      runId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string run_id = 1 [json_name = "runId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRunId() {
      runId_ = getDefaultInstance().getRunId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string run_id = 1 [json_name = "runId"];</code>
     * @param value The bytes for runId to set.
     * @return This builder for chaining.
     */
    public Builder setRunIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      runId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long afterSequence_ ;
    /**
     * <pre>
     * Resume position. Returns events with `sequence` strictly greater.
     * </pre>
     *
     * <code>uint64 after_sequence = 2 [json_name = "afterSequence"];</code>
     * @return The afterSequence.
     */
    @java.lang.Override
    public long getAfterSequence() {
      return afterSequence_;
    }
    /**
     * <pre>
     * Resume position. Returns events with `sequence` strictly greater.
     * </pre>
     *
     * <code>uint64 after_sequence = 2 [json_name = "afterSequence"];</code>
     * @param value The afterSequence to set.
     * @return This builder for chaining.
     */
    public Builder setAfterSequence(long value) {

      afterSequence_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Resume position. Returns events with `sequence` strictly greater.
     * </pre>
     *
     * <code>uint64 after_sequence = 2 [json_name = "afterSequence"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAfterSequence() {
      bitField0_ = (bitField0_ & ~0x00000002);
      afterSequence_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:threadline.task.v1.StreamRunEventsRequest)
  }

  // @@protoc_insertion_point(class_scope:threadline.task.v1.StreamRunEventsRequest)
  private static final com.threadline.proto.threadline.task.v1.StreamRunEventsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.threadline.proto.threadline.task.v1.StreamRunEventsRequest();
  }

  public static com.threadline.proto.threadline.task.v1.StreamRunEventsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamRunEventsRequest>
      PARSER = new com.google.protobuf.AbstractParser<StreamRunEventsRequest>() {
    @java.lang.Override
    public StreamRunEventsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StreamRunEventsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamRunEventsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.threadline.proto.threadline.task.v1.StreamRunEventsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

