// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/task/v1/task_service.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.task.v1;

/**
 * Protobuf type {@code threadline.task.v1.UpdateContextManifestResponse}
 */
@com.google.protobuf.Generated
public final class UpdateContextManifestResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:threadline.task.v1.UpdateContextManifestResponse)
    UpdateContextManifestResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "UpdateContextManifestResponse");
  }
  // Use UpdateContextManifestResponse.newBuilder() to construct.
  private UpdateContextManifestResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UpdateContextManifestResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.threadline.proto.threadline.task.v1.TaskServiceProto.internal_static_threadline_task_v1_UpdateContextManifestResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.threadline.proto.threadline.task.v1.TaskServiceProto.internal_static_threadline_task_v1_UpdateContextManifestResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.threadline.proto.threadline.task.v1.TaskServiceProto.internal_static_threadline_task_v1_UpdateContextManifestResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse.class, com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse.Builder.class);
  }

  private int bitField0_;
  public static final int CONTEXT_MANIFEST_FIELD_NUMBER = 1;
  private com.threadline.proto.threadline.task.v1.ContextManifest contextManifest_;
  /**
   * <code>.threadline.task.v1.ContextManifest context_manifest = 1 [json_name = "contextManifest"];</code>
   * @return Whether the contextManifest field is set.
   */
  @java.lang.Override
  public boolean hasContextManifest() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.threadline.task.v1.ContextManifest context_manifest = 1 [json_name = "contextManifest"];</code>
   * @return The contextManifest.
   */
  @java.lang.Override
  public com.threadline.proto.threadline.task.v1.ContextManifest getContextManifest() {
    return contextManifest_ == null ? com.threadline.proto.threadline.task.v1.ContextManifest.getDefaultInstance() : contextManifest_;
  }
  /**
   * <code>.threadline.task.v1.ContextManifest context_manifest = 1 [json_name = "contextManifest"];</code>
   */
  @java.lang.Override
  public com.threadline.proto.threadline.task.v1.ContextManifestOrBuilder getContextManifestOrBuilder() {
    return contextManifest_ == null ? com.threadline.proto.threadline.task.v1.ContextManifest.getDefaultInstance() : contextManifest_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getContextManifest());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getContextManifest());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse)) {
      return super.equals(obj);
    }
    com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse other = (com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse) obj;

    if (hasContextManifest() != other.hasContextManifest()) return false;
    if (hasContextManifest()) {
      if (!getContextManifest()
          .equals(other.getContextManifest())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasContextManifest()) {
      hash = (37 * hash) + CONTEXT_MANIFEST_FIELD_NUMBER;
      hash = (53 * hash) + getContextManifest().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code threadline.task.v1.UpdateContextManifestResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:threadline.task.v1.UpdateContextManifestResponse)
      com.threadline.proto.threadline.task.v1.UpdateContextManifestResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.threadline.proto.threadline.task.v1.TaskServiceProto.internal_static_threadline_task_v1_UpdateContextManifestResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.threadline.proto.threadline.task.v1.TaskServiceProto.internal_static_threadline_task_v1_UpdateContextManifestResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse.class, com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse.Builder.class);
    }

    // Construct using com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetContextManifestFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      contextManifest_ = null;
      if (contextManifestBuilder_ != null) {
        contextManifestBuilder_.dispose();
        contextManifestBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.threadline.proto.threadline.task.v1.TaskServiceProto.internal_static_threadline_task_v1_UpdateContextManifestResponse_descriptor;
    }

    @java.lang.Override
    public com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse getDefaultInstanceForType() {
      return com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse build() {
      com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse buildPartial() {
      com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse result = new com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.contextManifest_ = contextManifestBuilder_ == null
            ? contextManifest_
            : contextManifestBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse) {
        return mergeFrom((com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse other) {
      if (other == com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse.getDefaultInstance()) return this;
      if (other.hasContextManifest()) {
        mergeContextManifest(other.getContextManifest());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetContextManifestFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.threadline.proto.threadline.task.v1.ContextManifest contextManifest_;
    private com.google.protobuf.SingleFieldBuilder<
        com.threadline.proto.threadline.task.v1.ContextManifest, com.threadline.proto.threadline.task.v1.ContextManifest.Builder, com.threadline.proto.threadline.task.v1.ContextManifestOrBuilder> contextManifestBuilder_;
    /**
     * <code>.threadline.task.v1.ContextManifest context_manifest = 1 [json_name = "contextManifest"];</code>
     * @return Whether the contextManifest field is set.
     */
    public boolean hasContextManifest() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.threadline.task.v1.ContextManifest context_manifest = 1 [json_name = "contextManifest"];</code>
     * @return The contextManifest.
     */
    public com.threadline.proto.threadline.task.v1.ContextManifest getContextManifest() {
      if (contextManifestBuilder_ == null) {
        return contextManifest_ == null ? com.threadline.proto.threadline.task.v1.ContextManifest.getDefaultInstance() : contextManifest_;
      } else {
        return contextManifestBuilder_.getMessage();
      }
    }
    /**
     * <code>.threadline.task.v1.ContextManifest context_manifest = 1 [json_name = "contextManifest"];</code>
     */
    public Builder setContextManifest(com.threadline.proto.threadline.task.v1.ContextManifest value) {
      if (contextManifestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        contextManifest_ = value;
      } else {
        contextManifestBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.threadline.task.v1.ContextManifest context_manifest = 1 [json_name = "contextManifest"];</code>
     */
    public Builder setContextManifest(
        com.threadline.proto.threadline.task.v1.ContextManifest.Builder builderForValue) {
      if (contextManifestBuilder_ == null) {
        contextManifest_ = builderForValue.build();
      } else {
        contextManifestBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.threadline.task.v1.ContextManifest context_manifest = 1 [json_name = "contextManifest"];</code>
     */
    public Builder mergeContextManifest(com.threadline.proto.threadline.task.v1.ContextManifest value) {
      if (contextManifestBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          contextManifest_ != null &&
          contextManifest_ != com.threadline.proto.threadline.task.v1.ContextManifest.getDefaultInstance()) {
          getContextManifestBuilder().mergeFrom(value);
        } else {
          contextManifest_ = value;
        }
      } else {
        contextManifestBuilder_.mergeFrom(value);
      }
      if (contextManifest_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.threadline.task.v1.ContextManifest context_manifest = 1 [json_name = "contextManifest"];</code>
     */
    public Builder clearContextManifest() {
      bitField0_ = (bitField0_ & ~0x00000001);
      contextManifest_ = null;
      if (contextManifestBuilder_ != null) {
        contextManifestBuilder_.dispose();
        contextManifestBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.threadline.task.v1.ContextManifest context_manifest = 1 [json_name = "contextManifest"];</code>
     */
    public com.threadline.proto.threadline.task.v1.ContextManifest.Builder getContextManifestBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetContextManifestFieldBuilder().getBuilder();
    }
    /**
     * <code>.threadline.task.v1.ContextManifest context_manifest = 1 [json_name = "contextManifest"];</code>
     */
    public com.threadline.proto.threadline.task.v1.ContextManifestOrBuilder getContextManifestOrBuilder() {
      if (contextManifestBuilder_ != null) {
        return contextManifestBuilder_.getMessageOrBuilder();
      } else {
        return contextManifest_ == null ?
            com.threadline.proto.threadline.task.v1.ContextManifest.getDefaultInstance() : contextManifest_;
      }
    }
    /**
     * <code>.threadline.task.v1.ContextManifest context_manifest = 1 [json_name = "contextManifest"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.threadline.proto.threadline.task.v1.ContextManifest, com.threadline.proto.threadline.task.v1.ContextManifest.Builder, com.threadline.proto.threadline.task.v1.ContextManifestOrBuilder> 
        internalGetContextManifestFieldBuilder() {
      if (contextManifestBuilder_ == null) {
        contextManifestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.threadline.proto.threadline.task.v1.ContextManifest, com.threadline.proto.threadline.task.v1.ContextManifest.Builder, com.threadline.proto.threadline.task.v1.ContextManifestOrBuilder>(
                getContextManifest(),
                getParentForChildren(),
                isClean());
        contextManifest_ = null;
      }
      return contextManifestBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:threadline.task.v1.UpdateContextManifestResponse)
  }

  // @@protoc_insertion_point(class_scope:threadline.task.v1.UpdateContextManifestResponse)
  private static final com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse();
  }

  public static com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateContextManifestResponse>
      PARSER = new com.google.protobuf.AbstractParser<UpdateContextManifestResponse>() {
    @java.lang.Override
    public UpdateContextManifestResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateContextManifestResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateContextManifestResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.threadline.proto.threadline.task.v1.UpdateContextManifestResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

