// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/sync/v1/sync_service.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.sync.v1;

/**
 * Protobuf type {@code threadline.sync.v1.StreamEventsRequest}
 */
@com.google.protobuf.Generated
public final class StreamEventsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:threadline.sync.v1.StreamEventsRequest)
    StreamEventsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "StreamEventsRequest");
  }
  // Use StreamEventsRequest.newBuilder() to construct.
  private StreamEventsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StreamEventsRequest() {
    cursors_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.threadline.proto.threadline.sync.v1.SyncServiceProto.internal_static_threadline_sync_v1_StreamEventsRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.threadline.proto.threadline.sync.v1.SyncServiceProto.internal_static_threadline_sync_v1_StreamEventsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.threadline.proto.threadline.sync.v1.SyncServiceProto.internal_static_threadline_sync_v1_StreamEventsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.threadline.proto.threadline.sync.v1.StreamEventsRequest.class, com.threadline.proto.threadline.sync.v1.StreamEventsRequest.Builder.class);
  }

  public static final int CURSORS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.threadline.proto.threadline.sync.v1.SyncCursor> cursors_;
  /**
   * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
   */
  @java.lang.Override
  public java.util.List<com.threadline.proto.threadline.sync.v1.SyncCursor> getCursorsList() {
    return cursors_;
  }
  /**
   * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.threadline.proto.threadline.sync.v1.SyncCursorOrBuilder> 
      getCursorsOrBuilderList() {
    return cursors_;
  }
  /**
   * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
   */
  @java.lang.Override
  public int getCursorsCount() {
    return cursors_.size();
  }
  /**
   * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
   */
  @java.lang.Override
  public com.threadline.proto.threadline.sync.v1.SyncCursor getCursors(int index) {
    return cursors_.get(index);
  }
  /**
   * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
   */
  @java.lang.Override
  public com.threadline.proto.threadline.sync.v1.SyncCursorOrBuilder getCursorsOrBuilder(
      int index) {
    return cursors_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < cursors_.size(); i++) {
      output.writeMessage(1, cursors_.get(i));
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;

        {
          final int count = cursors_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(cursors_.get(i));
          }
          size += 1 * count;
        }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.threadline.proto.threadline.sync.v1.StreamEventsRequest)) {
      return super.equals(obj);
    }
    com.threadline.proto.threadline.sync.v1.StreamEventsRequest other = (com.threadline.proto.threadline.sync.v1.StreamEventsRequest) obj;

    if (!getCursorsList()
        .equals(other.getCursorsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCursorsCount() > 0) {
      hash = (37 * hash) + CURSORS_FIELD_NUMBER;
      hash = (53 * hash) + getCursorsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.threadline.proto.threadline.sync.v1.StreamEventsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.sync.v1.StreamEventsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.sync.v1.StreamEventsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.sync.v1.StreamEventsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.sync.v1.StreamEventsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.sync.v1.StreamEventsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.sync.v1.StreamEventsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.threadline.proto.threadline.sync.v1.StreamEventsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.threadline.proto.threadline.sync.v1.StreamEventsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.threadline.proto.threadline.sync.v1.StreamEventsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.threadline.proto.threadline.sync.v1.StreamEventsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.threadline.proto.threadline.sync.v1.StreamEventsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.threadline.proto.threadline.sync.v1.StreamEventsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code threadline.sync.v1.StreamEventsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:threadline.sync.v1.StreamEventsRequest)
      com.threadline.proto.threadline.sync.v1.StreamEventsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.threadline.proto.threadline.sync.v1.SyncServiceProto.internal_static_threadline_sync_v1_StreamEventsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.threadline.proto.threadline.sync.v1.SyncServiceProto.internal_static_threadline_sync_v1_StreamEventsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.threadline.proto.threadline.sync.v1.StreamEventsRequest.class, com.threadline.proto.threadline.sync.v1.StreamEventsRequest.Builder.class);
    }

    // Construct using com.threadline.proto.threadline.sync.v1.StreamEventsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (cursorsBuilder_ == null) {
        cursors_ = java.util.Collections.emptyList();
      } else {
        cursors_ = null;
        cursorsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.threadline.proto.threadline.sync.v1.SyncServiceProto.internal_static_threadline_sync_v1_StreamEventsRequest_descriptor;
    }

    @java.lang.Override
    public com.threadline.proto.threadline.sync.v1.StreamEventsRequest getDefaultInstanceForType() {
      return com.threadline.proto.threadline.sync.v1.StreamEventsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.threadline.proto.threadline.sync.v1.StreamEventsRequest build() {
      com.threadline.proto.threadline.sync.v1.StreamEventsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.threadline.proto.threadline.sync.v1.StreamEventsRequest buildPartial() {
      com.threadline.proto.threadline.sync.v1.StreamEventsRequest result = new com.threadline.proto.threadline.sync.v1.StreamEventsRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.threadline.proto.threadline.sync.v1.StreamEventsRequest result) {
      if (cursorsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          cursors_ = java.util.Collections.unmodifiableList(cursors_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.cursors_ = cursors_;
      } else {
        result.cursors_ = cursorsBuilder_.build();
      }
    }

    private void buildPartial0(com.threadline.proto.threadline.sync.v1.StreamEventsRequest result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.threadline.proto.threadline.sync.v1.StreamEventsRequest) {
        return mergeFrom((com.threadline.proto.threadline.sync.v1.StreamEventsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.threadline.proto.threadline.sync.v1.StreamEventsRequest other) {
      if (other == com.threadline.proto.threadline.sync.v1.StreamEventsRequest.getDefaultInstance()) return this;
      if (cursorsBuilder_ == null) {
        if (!other.cursors_.isEmpty()) {
          if (cursors_.isEmpty()) {
            cursors_ = other.cursors_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCursorsIsMutable();
            cursors_.addAll(other.cursors_);
          }
          onChanged();
        }
      } else {
        if (!other.cursors_.isEmpty()) {
          if (cursorsBuilder_.isEmpty()) {
            cursorsBuilder_.dispose();
            cursorsBuilder_ = null;
            cursors_ = other.cursors_;
            bitField0_ = (bitField0_ & ~0x00000001);
            cursorsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetCursorsFieldBuilder() : null;
          } else {
            cursorsBuilder_.addAllMessages(other.cursors_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.threadline.proto.threadline.sync.v1.SyncCursor m =
                  input.readMessage(
                      com.threadline.proto.threadline.sync.v1.SyncCursor.parser(),
                      extensionRegistry);
              if (cursorsBuilder_ == null) {
                ensureCursorsIsMutable();
                cursors_.add(m);
              } else {
                cursorsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.threadline.proto.threadline.sync.v1.SyncCursor> cursors_ =
      java.util.Collections.emptyList();
    private void ensureCursorsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        cursors_ = new java.util.ArrayList<com.threadline.proto.threadline.sync.v1.SyncCursor>(cursors_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.threadline.proto.threadline.sync.v1.SyncCursor, com.threadline.proto.threadline.sync.v1.SyncCursor.Builder, com.threadline.proto.threadline.sync.v1.SyncCursorOrBuilder> cursorsBuilder_;

    /**
     * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
     */
    public java.util.List<com.threadline.proto.threadline.sync.v1.SyncCursor> getCursorsList() {
      if (cursorsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cursors_);
      } else {
        return cursorsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
     */
    public int getCursorsCount() {
      if (cursorsBuilder_ == null) {
        return cursors_.size();
      } else {
        return cursorsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
     */
    public com.threadline.proto.threadline.sync.v1.SyncCursor getCursors(int index) {
      if (cursorsBuilder_ == null) {
        return cursors_.get(index);
      } else {
        return cursorsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
     */
    public Builder setCursors(
        int index, com.threadline.proto.threadline.sync.v1.SyncCursor value) {
      if (cursorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCursorsIsMutable();
        cursors_.set(index, value);
        onChanged();
      } else {
        cursorsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
     */
    public Builder setCursors(
        int index, com.threadline.proto.threadline.sync.v1.SyncCursor.Builder builderForValue) {
      if (cursorsBuilder_ == null) {
        ensureCursorsIsMutable();
        cursors_.set(index, builderForValue.build());
        onChanged();
      } else {
        cursorsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
     */
    public Builder addCursors(com.threadline.proto.threadline.sync.v1.SyncCursor value) {
      if (cursorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCursorsIsMutable();
        cursors_.add(value);
        onChanged();
      } else {
        cursorsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
     */
    public Builder addCursors(
        int index, com.threadline.proto.threadline.sync.v1.SyncCursor value) {
      if (cursorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCursorsIsMutable();
        cursors_.add(index, value);
        onChanged();
      } else {
        cursorsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
     */
    public Builder addCursors(
        com.threadline.proto.threadline.sync.v1.SyncCursor.Builder builderForValue) {
      if (cursorsBuilder_ == null) {
        ensureCursorsIsMutable();
        cursors_.add(builderForValue.build());
        onChanged();
      } else {
        cursorsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
     */
    public Builder addCursors(
        int index, com.threadline.proto.threadline.sync.v1.SyncCursor.Builder builderForValue) {
      if (cursorsBuilder_ == null) {
        ensureCursorsIsMutable();
        cursors_.add(index, builderForValue.build());
        onChanged();
      } else {
        cursorsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
     */
    public Builder addAllCursors(
        java.lang.Iterable<? extends com.threadline.proto.threadline.sync.v1.SyncCursor> values) {
      if (cursorsBuilder_ == null) {
        ensureCursorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cursors_);
        onChanged();
      } else {
        cursorsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
     */
    public Builder clearCursors() {
      if (cursorsBuilder_ == null) {
        cursors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        cursorsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
     */
    public Builder removeCursors(int index) {
      if (cursorsBuilder_ == null) {
        ensureCursorsIsMutable();
        cursors_.remove(index);
        onChanged();
      } else {
        cursorsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
     */
    public com.threadline.proto.threadline.sync.v1.SyncCursor.Builder getCursorsBuilder(
        int index) {
      return internalGetCursorsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
     */
    public com.threadline.proto.threadline.sync.v1.SyncCursorOrBuilder getCursorsOrBuilder(
        int index) {
      if (cursorsBuilder_ == null) {
        return cursors_.get(index);  } else {
        return cursorsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
     */
    public java.util.List<? extends com.threadline.proto.threadline.sync.v1.SyncCursorOrBuilder> 
         getCursorsOrBuilderList() {
      if (cursorsBuilder_ != null) {
        return cursorsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cursors_);
      }
    }
    /**
     * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
     */
    public com.threadline.proto.threadline.sync.v1.SyncCursor.Builder addCursorsBuilder() {
      return internalGetCursorsFieldBuilder().addBuilder(
          com.threadline.proto.threadline.sync.v1.SyncCursor.getDefaultInstance());
    }
    /**
     * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
     */
    public com.threadline.proto.threadline.sync.v1.SyncCursor.Builder addCursorsBuilder(
        int index) {
      return internalGetCursorsFieldBuilder().addBuilder(
          index, com.threadline.proto.threadline.sync.v1.SyncCursor.getDefaultInstance());
    }
    /**
     * <code>repeated .threadline.sync.v1.SyncCursor cursors = 1 [json_name = "cursors"];</code>
     */
    public java.util.List<com.threadline.proto.threadline.sync.v1.SyncCursor.Builder> 
         getCursorsBuilderList() {
      return internalGetCursorsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.threadline.proto.threadline.sync.v1.SyncCursor, com.threadline.proto.threadline.sync.v1.SyncCursor.Builder, com.threadline.proto.threadline.sync.v1.SyncCursorOrBuilder> 
        internalGetCursorsFieldBuilder() {
      if (cursorsBuilder_ == null) {
        cursorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.threadline.proto.threadline.sync.v1.SyncCursor, com.threadline.proto.threadline.sync.v1.SyncCursor.Builder, com.threadline.proto.threadline.sync.v1.SyncCursorOrBuilder>(
                cursors_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        cursors_ = null;
      }
      return cursorsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:threadline.sync.v1.StreamEventsRequest)
  }

  // @@protoc_insertion_point(class_scope:threadline.sync.v1.StreamEventsRequest)
  private static final com.threadline.proto.threadline.sync.v1.StreamEventsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.threadline.proto.threadline.sync.v1.StreamEventsRequest();
  }

  public static com.threadline.proto.threadline.sync.v1.StreamEventsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamEventsRequest>
      PARSER = new com.google.protobuf.AbstractParser<StreamEventsRequest>() {
    @java.lang.Override
    public StreamEventsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StreamEventsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamEventsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.threadline.proto.threadline.sync.v1.StreamEventsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

