// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/identity/v1/identity.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.identity.v1;

/**
 * <pre>
 * AgentHealthState summarizes whether an Agent can currently be dispatched.
 * </pre>
 *
 * Protobuf enum {@code threadline.identity.v1.AgentHealthState}
 */
@com.google.protobuf.Generated
public enum AgentHealthState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>AGENT_HEALTH_STATE_UNSPECIFIED = 0;</code>
   */
  AGENT_HEALTH_STATE_UNSPECIFIED(0),
  /**
   * <code>AGENT_HEALTH_STATE_HEALTHY = 1;</code>
   */
  AGENT_HEALTH_STATE_HEALTHY(1),
  /**
   * <pre>
   * No authorized Desktop Runtime is online for this Agent's owner, so Runs
   * queue. They never drift to another device or to the server.
   * </pre>
   *
   * <code>AGENT_HEALTH_STATE_NO_RUNTIME = 2;</code>
   */
  AGENT_HEALTH_STATE_NO_RUNTIME(2),
  /**
   * <pre>
   * Administratively suspended.
   * </pre>
   *
   * <code>AGENT_HEALTH_STATE_SUSPENDED = 3;</code>
   */
  AGENT_HEALTH_STATE_SUSPENDED(3),
  /**
   * <code>AGENT_HEALTH_STATE_DEGRADED = 4;</code>
   */
  AGENT_HEALTH_STATE_DEGRADED(4),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "AgentHealthState");
  }
  /**
   * <code>AGENT_HEALTH_STATE_UNSPECIFIED = 0;</code>
   */
  public static final int AGENT_HEALTH_STATE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>AGENT_HEALTH_STATE_HEALTHY = 1;</code>
   */
  public static final int AGENT_HEALTH_STATE_HEALTHY_VALUE = 1;
  /**
   * <pre>
   * No authorized Desktop Runtime is online for this Agent's owner, so Runs
   * queue. They never drift to another device or to the server.
   * </pre>
   *
   * <code>AGENT_HEALTH_STATE_NO_RUNTIME = 2;</code>
   */
  public static final int AGENT_HEALTH_STATE_NO_RUNTIME_VALUE = 2;
  /**
   * <pre>
   * Administratively suspended.
   * </pre>
   *
   * <code>AGENT_HEALTH_STATE_SUSPENDED = 3;</code>
   */
  public static final int AGENT_HEALTH_STATE_SUSPENDED_VALUE = 3;
  /**
   * <code>AGENT_HEALTH_STATE_DEGRADED = 4;</code>
   */
  public static final int AGENT_HEALTH_STATE_DEGRADED_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AgentHealthState valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AgentHealthState forNumber(int value) {
    switch (value) {
      case 0: return AGENT_HEALTH_STATE_UNSPECIFIED;
      case 1: return AGENT_HEALTH_STATE_HEALTHY;
      case 2: return AGENT_HEALTH_STATE_NO_RUNTIME;
      case 3: return AGENT_HEALTH_STATE_SUSPENDED;
      case 4: return AGENT_HEALTH_STATE_DEGRADED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AgentHealthState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AgentHealthState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AgentHealthState>() {
          public AgentHealthState findValueByNumber(int number) {
            return AgentHealthState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.threadline.proto.threadline.identity.v1.IdentityProto.getDescriptor().getEnumType(4);
  }

  private static final AgentHealthState[] VALUES = values();

  public static AgentHealthState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AgentHealthState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:threadline.identity.v1.AgentHealthState)
}

