// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/identity/v1/device.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.identity.v1;

/**
 * <pre>
 * DevicePlatform is the host platform, which determines which secure storage
 * backing is available and therefore what protection level may be claimed.
 * </pre>
 *
 * Protobuf enum {@code threadline.identity.v1.DevicePlatform}
 */
@com.google.protobuf.Generated
public enum DevicePlatform
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>DEVICE_PLATFORM_UNSPECIFIED = 0;</code>
   */
  DEVICE_PLATFORM_UNSPECIFIED(0),
  /**
   * <code>DEVICE_PLATFORM_MACOS = 1;</code>
   */
  DEVICE_PLATFORM_MACOS(1),
  /**
   * <code>DEVICE_PLATFORM_WINDOWS = 2;</code>
   */
  DEVICE_PLATFORM_WINDOWS(2),
  /**
   * <code>DEVICE_PLATFORM_LINUX = 3;</code>
   */
  DEVICE_PLATFORM_LINUX(3),
  /**
   * <code>DEVICE_PLATFORM_IOS = 4;</code>
   */
  DEVICE_PLATFORM_IOS(4),
  /**
   * <code>DEVICE_PLATFORM_ANDROID = 5;</code>
   */
  DEVICE_PLATFORM_ANDROID(5),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "DevicePlatform");
  }
  /**
   * <code>DEVICE_PLATFORM_UNSPECIFIED = 0;</code>
   */
  public static final int DEVICE_PLATFORM_UNSPECIFIED_VALUE = 0;
  /**
   * <code>DEVICE_PLATFORM_MACOS = 1;</code>
   */
  public static final int DEVICE_PLATFORM_MACOS_VALUE = 1;
  /**
   * <code>DEVICE_PLATFORM_WINDOWS = 2;</code>
   */
  public static final int DEVICE_PLATFORM_WINDOWS_VALUE = 2;
  /**
   * <code>DEVICE_PLATFORM_LINUX = 3;</code>
   */
  public static final int DEVICE_PLATFORM_LINUX_VALUE = 3;
  /**
   * <code>DEVICE_PLATFORM_IOS = 4;</code>
   */
  public static final int DEVICE_PLATFORM_IOS_VALUE = 4;
  /**
   * <code>DEVICE_PLATFORM_ANDROID = 5;</code>
   */
  public static final int DEVICE_PLATFORM_ANDROID_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DevicePlatform valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static DevicePlatform forNumber(int value) {
    switch (value) {
      case 0: return DEVICE_PLATFORM_UNSPECIFIED;
      case 1: return DEVICE_PLATFORM_MACOS;
      case 2: return DEVICE_PLATFORM_WINDOWS;
      case 3: return DEVICE_PLATFORM_LINUX;
      case 4: return DEVICE_PLATFORM_IOS;
      case 5: return DEVICE_PLATFORM_ANDROID;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DevicePlatform>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DevicePlatform> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DevicePlatform>() {
          public DevicePlatform findValueByNumber(int number) {
            return DevicePlatform.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.threadline.proto.threadline.identity.v1.DeviceProto.getDescriptor().getEnumType(0);
  }

  private static final DevicePlatform[] VALUES = values();

  public static DevicePlatform valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private DevicePlatform(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:threadline.identity.v1.DevicePlatform)
}

