// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/identity/v1/identity_service.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.identity.v1;

@com.google.protobuf.Generated
public interface ListDeviceLogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threadline.identity.v1.ListDeviceLogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Returns entries with `device_log_seq` strictly greater than this.
   * </pre>
   *
   * <code>uint64 after_seq = 1 [json_name = "afterSeq"];</code>
   * @return The afterSeq.
   */
  long getAfterSeq();

  /**
   * <code>.threadline.type.v1.PageRequest page = 2 [json_name = "page"];</code>
   * @return Whether the page field is set.
   */
  boolean hasPage();
  /**
   * <code>.threadline.type.v1.PageRequest page = 2 [json_name = "page"];</code>
   * @return The page.
   */
  com.threadline.proto.threadline.type.v1.PageRequest getPage();
  /**
   * <code>.threadline.type.v1.PageRequest page = 2 [json_name = "page"];</code>
   */
  com.threadline.proto.threadline.type.v1.PageRequestOrBuilder getPageOrBuilder();
}
