// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/identity/v1/device.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.identity.v1;

/**
 * <pre>
 * Session is an authenticated login, established through enterprise OIDC.
 *
 * Holding a Session never implies cryptographic access. Revoking a Session
 * stops API calls; it does not remove the Device from any E2EE Group, which
 * requires revoking the Device.
 * </pre>
 *
 * Protobuf type {@code threadline.identity.v1.Session}
 */
@com.google.protobuf.Generated
public final class Session extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:threadline.identity.v1.Session)
    SessionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Session");
  }
  // Use Session.newBuilder() to construct.
  private Session(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Session() {
    sessionId_ = "";
    tenantId_ = "";
    actorId_ = "";
    deviceId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.threadline.proto.threadline.identity.v1.DeviceProto.internal_static_threadline_identity_v1_Session_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.threadline.proto.threadline.identity.v1.DeviceProto.internal_static_threadline_identity_v1_Session_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.threadline.proto.threadline.identity.v1.DeviceProto.internal_static_threadline_identity_v1_Session_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.threadline.proto.threadline.identity.v1.Session.class, com.threadline.proto.threadline.identity.v1.Session.Builder.class);
  }

  private int bitField0_;
  public static final int SESSION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionId_ = "";
  /**
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANT_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTOR_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object actorId_ = "";
  /**
   * <code>string actor_id = 3 [json_name = "actorId"];</code>
   * @return The actorId.
   */
  @java.lang.Override
  public java.lang.String getActorId() {
    java.lang.Object ref = actorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      actorId_ = s;
      return s;
    }
  }
  /**
   * <code>string actor_id = 3 [json_name = "actorId"];</code>
   * @return The bytes for actorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActorIdBytes() {
    java.lang.Object ref = actorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      actorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object deviceId_ = "";
  /**
   * <pre>
   * The Device this session is bound to. Sessions are not transferable between
   * Devices.
   * </pre>
   *
   * <code>string device_id = 4 [json_name = "deviceId"];</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The Device this session is bound to. Sessions are not transferable between
   * Devices.
   * </pre>
   *
   * <code>string device_id = 4 [json_name = "deviceId"];</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_AT_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <code>.google.protobuf.Timestamp created_at = 5 [json_name = "createdAt"];</code>
   * @return Whether the createdAt field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 5 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 5 [json_name = "createdAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }

  public static final int EXPIRES_AT_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp expiresAt_;
  /**
   * <code>.google.protobuf.Timestamp expires_at = 6 [json_name = "expiresAt"];</code>
   * @return Whether the expiresAt field is set.
   */
  @java.lang.Override
  public boolean hasExpiresAt() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp expires_at = 6 [json_name = "expiresAt"];</code>
   * @return The expiresAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getExpiresAt() {
    return expiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiresAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp expires_at = 6 [json_name = "expiresAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getExpiresAtOrBuilder() {
    return expiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiresAt_;
  }

  public static final int REVOKED_AT_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp revokedAt_;
  /**
   * <pre>
   * Set when the session was explicitly revoked before expiry.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp revoked_at = 7 [json_name = "revokedAt"];</code>
   * @return Whether the revokedAt field is set.
   */
  @java.lang.Override
  public boolean hasRevokedAt() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Set when the session was explicitly revoked before expiry.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp revoked_at = 7 [json_name = "revokedAt"];</code>
   * @return The revokedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getRevokedAt() {
    return revokedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : revokedAt_;
  }
  /**
   * <pre>
   * Set when the session was explicitly revoked before expiry.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp revoked_at = 7 [json_name = "revokedAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getRevokedAtOrBuilder() {
    return revokedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : revokedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sessionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actorId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, actorId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, deviceId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getCreatedAt());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(6, getExpiresAt());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(7, getRevokedAt());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actorId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, actorId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, deviceId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getCreatedAt());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getExpiresAt());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getRevokedAt());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.threadline.proto.threadline.identity.v1.Session)) {
      return super.equals(obj);
    }
    com.threadline.proto.threadline.identity.v1.Session other = (com.threadline.proto.threadline.identity.v1.Session) obj;

    if (!getSessionId()
        .equals(other.getSessionId())) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (!getActorId()
        .equals(other.getActorId())) return false;
    if (!getDeviceId()
        .equals(other.getDeviceId())) return false;
    if (hasCreatedAt() != other.hasCreatedAt()) return false;
    if (hasCreatedAt()) {
      if (!getCreatedAt()
          .equals(other.getCreatedAt())) return false;
    }
    if (hasExpiresAt() != other.hasExpiresAt()) return false;
    if (hasExpiresAt()) {
      if (!getExpiresAt()
          .equals(other.getExpiresAt())) return false;
    }
    if (hasRevokedAt() != other.hasRevokedAt()) return false;
    if (hasRevokedAt()) {
      if (!getRevokedAt()
          .equals(other.getRevokedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (37 * hash) + ACTOR_ID_FIELD_NUMBER;
    hash = (53 * hash) + getActorId().hashCode();
    hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
    }
    if (hasExpiresAt()) {
      hash = (37 * hash) + EXPIRES_AT_FIELD_NUMBER;
      hash = (53 * hash) + getExpiresAt().hashCode();
    }
    if (hasRevokedAt()) {
      hash = (37 * hash) + REVOKED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getRevokedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.threadline.proto.threadline.identity.v1.Session parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.identity.v1.Session parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.identity.v1.Session parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.identity.v1.Session parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.identity.v1.Session parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.identity.v1.Session parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.identity.v1.Session parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.threadline.proto.threadline.identity.v1.Session parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.threadline.proto.threadline.identity.v1.Session parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.threadline.proto.threadline.identity.v1.Session parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.threadline.proto.threadline.identity.v1.Session parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.threadline.proto.threadline.identity.v1.Session parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.threadline.proto.threadline.identity.v1.Session prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Session is an authenticated login, established through enterprise OIDC.
   *
   * Holding a Session never implies cryptographic access. Revoking a Session
   * stops API calls; it does not remove the Device from any E2EE Group, which
   * requires revoking the Device.
   * </pre>
   *
   * Protobuf type {@code threadline.identity.v1.Session}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:threadline.identity.v1.Session)
      com.threadline.proto.threadline.identity.v1.SessionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.threadline.proto.threadline.identity.v1.DeviceProto.internal_static_threadline_identity_v1_Session_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.threadline.proto.threadline.identity.v1.DeviceProto.internal_static_threadline_identity_v1_Session_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.threadline.proto.threadline.identity.v1.Session.class, com.threadline.proto.threadline.identity.v1.Session.Builder.class);
    }

    // Construct using com.threadline.proto.threadline.identity.v1.Session.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetCreatedAtFieldBuilder();
        internalGetExpiresAtFieldBuilder();
        internalGetRevokedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sessionId_ = "";
      tenantId_ = "";
      actorId_ = "";
      deviceId_ = "";
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      expiresAt_ = null;
      if (expiresAtBuilder_ != null) {
        expiresAtBuilder_.dispose();
        expiresAtBuilder_ = null;
      }
      revokedAt_ = null;
      if (revokedAtBuilder_ != null) {
        revokedAtBuilder_.dispose();
        revokedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.threadline.proto.threadline.identity.v1.DeviceProto.internal_static_threadline_identity_v1_Session_descriptor;
    }

    @java.lang.Override
    public com.threadline.proto.threadline.identity.v1.Session getDefaultInstanceForType() {
      return com.threadline.proto.threadline.identity.v1.Session.getDefaultInstance();
    }

    @java.lang.Override
    public com.threadline.proto.threadline.identity.v1.Session build() {
      com.threadline.proto.threadline.identity.v1.Session result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.threadline.proto.threadline.identity.v1.Session buildPartial() {
      com.threadline.proto.threadline.identity.v1.Session result = new com.threadline.proto.threadline.identity.v1.Session(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.threadline.proto.threadline.identity.v1.Session result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sessionId_ = sessionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tenantId_ = tenantId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.actorId_ = actorId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.deviceId_ = deviceId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.createdAt_ = createdAtBuilder_ == null
            ? createdAt_
            : createdAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.expiresAt_ = expiresAtBuilder_ == null
            ? expiresAt_
            : expiresAtBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.revokedAt_ = revokedAtBuilder_ == null
            ? revokedAt_
            : revokedAtBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.threadline.proto.threadline.identity.v1.Session) {
        return mergeFrom((com.threadline.proto.threadline.identity.v1.Session)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.threadline.proto.threadline.identity.v1.Session other) {
      if (other == com.threadline.proto.threadline.identity.v1.Session.getDefaultInstance()) return this;
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getActorId().isEmpty()) {
        actorId_ = other.actorId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasCreatedAt()) {
        mergeCreatedAt(other.getCreatedAt());
      }
      if (other.hasExpiresAt()) {
        mergeExpiresAt(other.getExpiresAt());
      }
      if (other.hasRevokedAt()) {
        mergeRevokedAt(other.getRevokedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              actorId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              deviceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetCreatedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetExpiresAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  internalGetRevokedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sessionId_ = "";
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object actorId_ = "";
    /**
     * <code>string actor_id = 3 [json_name = "actorId"];</code>
     * @return The actorId.
     */
    public java.lang.String getActorId() {
      java.lang.Object ref = actorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string actor_id = 3 [json_name = "actorId"];</code>
     * @return The bytes for actorId.
     */
    public com.google.protobuf.ByteString
        getActorIdBytes() {
      java.lang.Object ref = actorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string actor_id = 3 [json_name = "actorId"];</code>
     * @param value The actorId to set.
     * @return This builder for chaining.
     */
    public Builder setActorId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      actorId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string actor_id = 3 [json_name = "actorId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearActorId() {
      actorId_ = getDefaultInstance().getActorId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string actor_id = 3 [json_name = "actorId"];</code>
     * @param value The bytes for actorId to set.
     * @return This builder for chaining.
     */
    public Builder setActorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      actorId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object deviceId_ = "";
    /**
     * <pre>
     * The Device this session is bound to. Sessions are not transferable between
     * Devices.
     * </pre>
     *
     * <code>string device_id = 4 [json_name = "deviceId"];</code>
     * @return The deviceId.
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The Device this session is bound to. Sessions are not transferable between
     * Devices.
     * </pre>
     *
     * <code>string device_id = 4 [json_name = "deviceId"];</code>
     * @return The bytes for deviceId.
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The Device this session is bound to. Sessions are not transferable between
     * Devices.
     * </pre>
     *
     * <code>string device_id = 4 [json_name = "deviceId"];</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      deviceId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The Device this session is bound to. Sessions are not transferable between
     * Devices.
     * </pre>
     *
     * <code>string device_id = 4 [json_name = "deviceId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      deviceId_ = getDefaultInstance().getDeviceId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The Device this session is bound to. Sessions are not transferable between
     * Devices.
     * </pre>
     *
     * <code>string device_id = 4 [json_name = "deviceId"];</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      deviceId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createdAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 5 [json_name = "createdAt"];</code>
     * @return Whether the createdAt field is set.
     */
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 5 [json_name = "createdAt"];</code>
     * @return The createdAt.
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 5 [json_name = "createdAt"];</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
      } else {
        createdAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 5 [json_name = "createdAt"];</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 5 [json_name = "createdAt"];</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          createdAt_ != null &&
          createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreatedAtBuilder().mergeFrom(value);
        } else {
          createdAt_ = value;
        }
      } else {
        createdAtBuilder_.mergeFrom(value);
      }
      if (createdAt_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 5 [json_name = "createdAt"];</code>
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00000010);
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 5 [json_name = "createdAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 5 [json_name = "createdAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 5 [json_name = "createdAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }

    private com.google.protobuf.Timestamp expiresAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> expiresAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp expires_at = 6 [json_name = "expiresAt"];</code>
     * @return Whether the expiresAt field is set.
     */
    public boolean hasExpiresAt() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 6 [json_name = "expiresAt"];</code>
     * @return The expiresAt.
     */
    public com.google.protobuf.Timestamp getExpiresAt() {
      if (expiresAtBuilder_ == null) {
        return expiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiresAt_;
      } else {
        return expiresAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 6 [json_name = "expiresAt"];</code>
     */
    public Builder setExpiresAt(com.google.protobuf.Timestamp value) {
      if (expiresAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expiresAt_ = value;
      } else {
        expiresAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 6 [json_name = "expiresAt"];</code>
     */
    public Builder setExpiresAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (expiresAtBuilder_ == null) {
        expiresAt_ = builderForValue.build();
      } else {
        expiresAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 6 [json_name = "expiresAt"];</code>
     */
    public Builder mergeExpiresAt(com.google.protobuf.Timestamp value) {
      if (expiresAtBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          expiresAt_ != null &&
          expiresAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getExpiresAtBuilder().mergeFrom(value);
        } else {
          expiresAt_ = value;
        }
      } else {
        expiresAtBuilder_.mergeFrom(value);
      }
      if (expiresAt_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 6 [json_name = "expiresAt"];</code>
     */
    public Builder clearExpiresAt() {
      bitField0_ = (bitField0_ & ~0x00000020);
      expiresAt_ = null;
      if (expiresAtBuilder_ != null) {
        expiresAtBuilder_.dispose();
        expiresAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 6 [json_name = "expiresAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getExpiresAtBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetExpiresAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 6 [json_name = "expiresAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getExpiresAtOrBuilder() {
      if (expiresAtBuilder_ != null) {
        return expiresAtBuilder_.getMessageOrBuilder();
      } else {
        return expiresAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : expiresAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 6 [json_name = "expiresAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetExpiresAtFieldBuilder() {
      if (expiresAtBuilder_ == null) {
        expiresAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getExpiresAt(),
                getParentForChildren(),
                isClean());
        expiresAt_ = null;
      }
      return expiresAtBuilder_;
    }

    private com.google.protobuf.Timestamp revokedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> revokedAtBuilder_;
    /**
     * <pre>
     * Set when the session was explicitly revoked before expiry.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp revoked_at = 7 [json_name = "revokedAt"];</code>
     * @return Whether the revokedAt field is set.
     */
    public boolean hasRevokedAt() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * Set when the session was explicitly revoked before expiry.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp revoked_at = 7 [json_name = "revokedAt"];</code>
     * @return The revokedAt.
     */
    public com.google.protobuf.Timestamp getRevokedAt() {
      if (revokedAtBuilder_ == null) {
        return revokedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : revokedAt_;
      } else {
        return revokedAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Set when the session was explicitly revoked before expiry.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp revoked_at = 7 [json_name = "revokedAt"];</code>
     */
    public Builder setRevokedAt(com.google.protobuf.Timestamp value) {
      if (revokedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        revokedAt_ = value;
      } else {
        revokedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Set when the session was explicitly revoked before expiry.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp revoked_at = 7 [json_name = "revokedAt"];</code>
     */
    public Builder setRevokedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (revokedAtBuilder_ == null) {
        revokedAt_ = builderForValue.build();
      } else {
        revokedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Set when the session was explicitly revoked before expiry.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp revoked_at = 7 [json_name = "revokedAt"];</code>
     */
    public Builder mergeRevokedAt(com.google.protobuf.Timestamp value) {
      if (revokedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          revokedAt_ != null &&
          revokedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getRevokedAtBuilder().mergeFrom(value);
        } else {
          revokedAt_ = value;
        }
      } else {
        revokedAtBuilder_.mergeFrom(value);
      }
      if (revokedAt_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Set when the session was explicitly revoked before expiry.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp revoked_at = 7 [json_name = "revokedAt"];</code>
     */
    public Builder clearRevokedAt() {
      bitField0_ = (bitField0_ & ~0x00000040);
      revokedAt_ = null;
      if (revokedAtBuilder_ != null) {
        revokedAtBuilder_.dispose();
        revokedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Set when the session was explicitly revoked before expiry.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp revoked_at = 7 [json_name = "revokedAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getRevokedAtBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return internalGetRevokedAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Set when the session was explicitly revoked before expiry.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp revoked_at = 7 [json_name = "revokedAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getRevokedAtOrBuilder() {
      if (revokedAtBuilder_ != null) {
        return revokedAtBuilder_.getMessageOrBuilder();
      } else {
        return revokedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : revokedAt_;
      }
    }
    /**
     * <pre>
     * Set when the session was explicitly revoked before expiry.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp revoked_at = 7 [json_name = "revokedAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetRevokedAtFieldBuilder() {
      if (revokedAtBuilder_ == null) {
        revokedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getRevokedAt(),
                getParentForChildren(),
                isClean());
        revokedAt_ = null;
      }
      return revokedAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:threadline.identity.v1.Session)
  }

  // @@protoc_insertion_point(class_scope:threadline.identity.v1.Session)
  private static final com.threadline.proto.threadline.identity.v1.Session DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.threadline.proto.threadline.identity.v1.Session();
  }

  public static com.threadline.proto.threadline.identity.v1.Session getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Session>
      PARSER = new com.google.protobuf.AbstractParser<Session>() {
    @java.lang.Override
    public Session parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Session> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Session> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.threadline.proto.threadline.identity.v1.Session getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

