// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/authorization/v1/authorization.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.authorization.v1;

/**
 * <pre>
 * AuthorizationReason is stable audit vocabulary. A denied result may report
 * unavailable facts separately from a policy denial while still failing closed.
 * </pre>
 *
 * Protobuf enum {@code threadline.authorization.v1.AuthorizationReason}
 */
@com.google.protobuf.Generated
public enum AuthorizationReason
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>AUTHORIZATION_REASON_UNSPECIFIED = 0;</code>
   */
  AUTHORIZATION_REASON_UNSPECIFIED(0),
  /**
   * <code>AUTHORIZATION_REASON_ALLOWED = 1;</code>
   */
  AUTHORIZATION_REASON_ALLOWED(1),
  /**
   * <code>AUTHORIZATION_REASON_AUTHENTICATION_REQUIRED = 2;</code>
   */
  AUTHORIZATION_REASON_AUTHENTICATION_REQUIRED(2),
  /**
   * <code>AUTHORIZATION_REASON_TENANT_MISMATCH = 3;</code>
   */
  AUTHORIZATION_REASON_TENANT_MISMATCH(3),
  /**
   * <code>AUTHORIZATION_REASON_ORGANIZATION_UNAVAILABLE = 4;</code>
   */
  AUTHORIZATION_REASON_ORGANIZATION_UNAVAILABLE(4),
  /**
   * <code>AUTHORIZATION_REASON_MEMBER_INACTIVE = 5;</code>
   */
  AUTHORIZATION_REASON_MEMBER_INACTIVE(5),
  /**
   * <code>AUTHORIZATION_REASON_NOT_A_MEMBER = 6;</code>
   */
  AUTHORIZATION_REASON_NOT_A_MEMBER(6),
  /**
   * <code>AUTHORIZATION_REASON_ORGANIZATION_ROLE_DENIED = 7;</code>
   */
  AUTHORIZATION_REASON_ORGANIZATION_ROLE_DENIED(7),
  /**
   * <code>AUTHORIZATION_REASON_CHANNEL_ROLE_DENIED = 8;</code>
   */
  AUTHORIZATION_REASON_CHANNEL_ROLE_DENIED(8),
  /**
   * <code>AUTHORIZATION_REASON_RESOURCE_STATE_DENIED = 9;</code>
   */
  AUTHORIZATION_REASON_RESOURCE_STATE_DENIED(9),
  /**
   * <code>AUTHORIZATION_REASON_ACL_MATCHED_DENY = 10;</code>
   */
  AUTHORIZATION_REASON_ACL_MATCHED_DENY(10),
  /**
   * <code>AUTHORIZATION_REASON_ACL_DEFAULT_DENY = 11;</code>
   */
  AUTHORIZATION_REASON_ACL_DEFAULT_DENY(11),
  /**
   * <code>AUTHORIZATION_REASON_ACL_INVALID = 12;</code>
   */
  AUTHORIZATION_REASON_ACL_INVALID(12),
  /**
   * <code>AUTHORIZATION_REASON_POLICY_VERSION_INVALID = 13;</code>
   */
  AUTHORIZATION_REASON_POLICY_VERSION_INVALID(13),
  /**
   * <code>AUTHORIZATION_REASON_ACL_VERSION_INVALID = 14;</code>
   */
  AUTHORIZATION_REASON_ACL_VERSION_INVALID(14),
  /**
   * <code>AUTHORIZATION_REASON_CAPABILITY_REQUIRED = 15;</code>
   */
  AUTHORIZATION_REASON_CAPABILITY_REQUIRED(15),
  /**
   * <code>AUTHORIZATION_REASON_CAPABILITY_DENIED = 16;</code>
   */
  AUTHORIZATION_REASON_CAPABILITY_DENIED(16),
  /**
   * <code>AUTHORIZATION_REASON_DELEGATION_DENIED = 17;</code>
   */
  AUTHORIZATION_REASON_DELEGATION_DENIED(17),
  /**
   * <code>AUTHORIZATION_REASON_APPROVAL_REQUIRED = 18;</code>
   */
  AUTHORIZATION_REASON_APPROVAL_REQUIRED(18),
  /**
   * <code>AUTHORIZATION_REASON_FACTS_UNAVAILABLE = 19;</code>
   */
  AUTHORIZATION_REASON_FACTS_UNAVAILABLE(19),
  /**
   * <code>AUTHORIZATION_REASON_UNKNOWN_ACTION = 20;</code>
   */
  AUTHORIZATION_REASON_UNKNOWN_ACTION(20),
  /**
   * <code>AUTHORIZATION_REASON_UNKNOWN_RESOURCE = 21;</code>
   */
  AUTHORIZATION_REASON_UNKNOWN_RESOURCE(21),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "AuthorizationReason");
  }
  /**
   * <code>AUTHORIZATION_REASON_UNSPECIFIED = 0;</code>
   */
  public static final int AUTHORIZATION_REASON_UNSPECIFIED_VALUE = 0;
  /**
   * <code>AUTHORIZATION_REASON_ALLOWED = 1;</code>
   */
  public static final int AUTHORIZATION_REASON_ALLOWED_VALUE = 1;
  /**
   * <code>AUTHORIZATION_REASON_AUTHENTICATION_REQUIRED = 2;</code>
   */
  public static final int AUTHORIZATION_REASON_AUTHENTICATION_REQUIRED_VALUE = 2;
  /**
   * <code>AUTHORIZATION_REASON_TENANT_MISMATCH = 3;</code>
   */
  public static final int AUTHORIZATION_REASON_TENANT_MISMATCH_VALUE = 3;
  /**
   * <code>AUTHORIZATION_REASON_ORGANIZATION_UNAVAILABLE = 4;</code>
   */
  public static final int AUTHORIZATION_REASON_ORGANIZATION_UNAVAILABLE_VALUE = 4;
  /**
   * <code>AUTHORIZATION_REASON_MEMBER_INACTIVE = 5;</code>
   */
  public static final int AUTHORIZATION_REASON_MEMBER_INACTIVE_VALUE = 5;
  /**
   * <code>AUTHORIZATION_REASON_NOT_A_MEMBER = 6;</code>
   */
  public static final int AUTHORIZATION_REASON_NOT_A_MEMBER_VALUE = 6;
  /**
   * <code>AUTHORIZATION_REASON_ORGANIZATION_ROLE_DENIED = 7;</code>
   */
  public static final int AUTHORIZATION_REASON_ORGANIZATION_ROLE_DENIED_VALUE = 7;
  /**
   * <code>AUTHORIZATION_REASON_CHANNEL_ROLE_DENIED = 8;</code>
   */
  public static final int AUTHORIZATION_REASON_CHANNEL_ROLE_DENIED_VALUE = 8;
  /**
   * <code>AUTHORIZATION_REASON_RESOURCE_STATE_DENIED = 9;</code>
   */
  public static final int AUTHORIZATION_REASON_RESOURCE_STATE_DENIED_VALUE = 9;
  /**
   * <code>AUTHORIZATION_REASON_ACL_MATCHED_DENY = 10;</code>
   */
  public static final int AUTHORIZATION_REASON_ACL_MATCHED_DENY_VALUE = 10;
  /**
   * <code>AUTHORIZATION_REASON_ACL_DEFAULT_DENY = 11;</code>
   */
  public static final int AUTHORIZATION_REASON_ACL_DEFAULT_DENY_VALUE = 11;
  /**
   * <code>AUTHORIZATION_REASON_ACL_INVALID = 12;</code>
   */
  public static final int AUTHORIZATION_REASON_ACL_INVALID_VALUE = 12;
  /**
   * <code>AUTHORIZATION_REASON_POLICY_VERSION_INVALID = 13;</code>
   */
  public static final int AUTHORIZATION_REASON_POLICY_VERSION_INVALID_VALUE = 13;
  /**
   * <code>AUTHORIZATION_REASON_ACL_VERSION_INVALID = 14;</code>
   */
  public static final int AUTHORIZATION_REASON_ACL_VERSION_INVALID_VALUE = 14;
  /**
   * <code>AUTHORIZATION_REASON_CAPABILITY_REQUIRED = 15;</code>
   */
  public static final int AUTHORIZATION_REASON_CAPABILITY_REQUIRED_VALUE = 15;
  /**
   * <code>AUTHORIZATION_REASON_CAPABILITY_DENIED = 16;</code>
   */
  public static final int AUTHORIZATION_REASON_CAPABILITY_DENIED_VALUE = 16;
  /**
   * <code>AUTHORIZATION_REASON_DELEGATION_DENIED = 17;</code>
   */
  public static final int AUTHORIZATION_REASON_DELEGATION_DENIED_VALUE = 17;
  /**
   * <code>AUTHORIZATION_REASON_APPROVAL_REQUIRED = 18;</code>
   */
  public static final int AUTHORIZATION_REASON_APPROVAL_REQUIRED_VALUE = 18;
  /**
   * <code>AUTHORIZATION_REASON_FACTS_UNAVAILABLE = 19;</code>
   */
  public static final int AUTHORIZATION_REASON_FACTS_UNAVAILABLE_VALUE = 19;
  /**
   * <code>AUTHORIZATION_REASON_UNKNOWN_ACTION = 20;</code>
   */
  public static final int AUTHORIZATION_REASON_UNKNOWN_ACTION_VALUE = 20;
  /**
   * <code>AUTHORIZATION_REASON_UNKNOWN_RESOURCE = 21;</code>
   */
  public static final int AUTHORIZATION_REASON_UNKNOWN_RESOURCE_VALUE = 21;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AuthorizationReason valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AuthorizationReason forNumber(int value) {
    switch (value) {
      case 0: return AUTHORIZATION_REASON_UNSPECIFIED;
      case 1: return AUTHORIZATION_REASON_ALLOWED;
      case 2: return AUTHORIZATION_REASON_AUTHENTICATION_REQUIRED;
      case 3: return AUTHORIZATION_REASON_TENANT_MISMATCH;
      case 4: return AUTHORIZATION_REASON_ORGANIZATION_UNAVAILABLE;
      case 5: return AUTHORIZATION_REASON_MEMBER_INACTIVE;
      case 6: return AUTHORIZATION_REASON_NOT_A_MEMBER;
      case 7: return AUTHORIZATION_REASON_ORGANIZATION_ROLE_DENIED;
      case 8: return AUTHORIZATION_REASON_CHANNEL_ROLE_DENIED;
      case 9: return AUTHORIZATION_REASON_RESOURCE_STATE_DENIED;
      case 10: return AUTHORIZATION_REASON_ACL_MATCHED_DENY;
      case 11: return AUTHORIZATION_REASON_ACL_DEFAULT_DENY;
      case 12: return AUTHORIZATION_REASON_ACL_INVALID;
      case 13: return AUTHORIZATION_REASON_POLICY_VERSION_INVALID;
      case 14: return AUTHORIZATION_REASON_ACL_VERSION_INVALID;
      case 15: return AUTHORIZATION_REASON_CAPABILITY_REQUIRED;
      case 16: return AUTHORIZATION_REASON_CAPABILITY_DENIED;
      case 17: return AUTHORIZATION_REASON_DELEGATION_DENIED;
      case 18: return AUTHORIZATION_REASON_APPROVAL_REQUIRED;
      case 19: return AUTHORIZATION_REASON_FACTS_UNAVAILABLE;
      case 20: return AUTHORIZATION_REASON_UNKNOWN_ACTION;
      case 21: return AUTHORIZATION_REASON_UNKNOWN_RESOURCE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AuthorizationReason>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AuthorizationReason> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AuthorizationReason>() {
          public AuthorizationReason findValueByNumber(int number) {
            return AuthorizationReason.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.threadline.proto.threadline.authorization.v1.AuthorizationProto.getDescriptor().getEnumType(3);
  }

  private static final AuthorizationReason[] VALUES = values();

  public static AuthorizationReason valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AuthorizationReason(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:threadline.authorization.v1.AuthorizationReason)
}

