// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/authorization/v1/authorization.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.authorization.v1;

/**
 * <pre>
 * ResourceAcl is the complete, versioned ACL snapshot used for one decision.
 * With no matching entry, default_effect applies. The default must be an
 * explicit ALLOW or DENY; unspecified and unknown values fail closed. An empty
 * entry set uses default_effect, while conflicting matching entries use DENY.
 * Missing resource, actor, action, effect, identifier, or version data makes
 * the ACL invalid and denies the whole evaluation.
 * </pre>
 *
 * Protobuf type {@code threadline.authorization.v1.ResourceAcl}
 */
@com.google.protobuf.Generated
public final class ResourceAcl extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:threadline.authorization.v1.ResourceAcl)
    ResourceAclOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ResourceAcl");
  }
  // Use ResourceAcl.newBuilder() to construct.
  private ResourceAcl(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ResourceAcl() {
    aclVersion_ = "";
    defaultEffect_ = 0;
    entries_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.threadline.proto.threadline.authorization.v1.AuthorizationProto.internal_static_threadline_authorization_v1_ResourceAcl_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.threadline.proto.threadline.authorization.v1.AuthorizationProto.internal_static_threadline_authorization_v1_ResourceAcl_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.threadline.proto.threadline.authorization.v1.AuthorizationProto.internal_static_threadline_authorization_v1_ResourceAcl_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.threadline.proto.threadline.authorization.v1.ResourceAcl.class, com.threadline.proto.threadline.authorization.v1.ResourceAcl.Builder.class);
  }

  private int bitField0_;
  public static final int RESOURCE_FIELD_NUMBER = 1;
  private com.threadline.proto.threadline.authorization.v1.ResourceRef resource_;
  /**
   * <code>.threadline.authorization.v1.ResourceRef resource = 1 [json_name = "resource"];</code>
   * @return Whether the resource field is set.
   */
  @java.lang.Override
  public boolean hasResource() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.threadline.authorization.v1.ResourceRef resource = 1 [json_name = "resource"];</code>
   * @return The resource.
   */
  @java.lang.Override
  public com.threadline.proto.threadline.authorization.v1.ResourceRef getResource() {
    return resource_ == null ? com.threadline.proto.threadline.authorization.v1.ResourceRef.getDefaultInstance() : resource_;
  }
  /**
   * <code>.threadline.authorization.v1.ResourceRef resource = 1 [json_name = "resource"];</code>
   */
  @java.lang.Override
  public com.threadline.proto.threadline.authorization.v1.ResourceRefOrBuilder getResourceOrBuilder() {
    return resource_ == null ? com.threadline.proto.threadline.authorization.v1.ResourceRef.getDefaultInstance() : resource_;
  }

  public static final int ACL_VERSION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object aclVersion_ = "";
  /**
   * <code>string acl_version = 2 [json_name = "aclVersion"];</code>
   * @return The aclVersion.
   */
  @java.lang.Override
  public java.lang.String getAclVersion() {
    java.lang.Object ref = aclVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aclVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string acl_version = 2 [json_name = "aclVersion"];</code>
   * @return The bytes for aclVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAclVersionBytes() {
    java.lang.Object ref = aclVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aclVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEFAULT_EFFECT_FIELD_NUMBER = 3;
  private int defaultEffect_ = 0;
  /**
   * <code>.threadline.authorization.v1.AclEffect default_effect = 3 [json_name = "defaultEffect"];</code>
   * @return The enum numeric value on the wire for defaultEffect.
   */
  @java.lang.Override public int getDefaultEffectValue() {
    return defaultEffect_;
  }
  /**
   * <code>.threadline.authorization.v1.AclEffect default_effect = 3 [json_name = "defaultEffect"];</code>
   * @return The defaultEffect.
   */
  @java.lang.Override public com.threadline.proto.threadline.authorization.v1.AclEffect getDefaultEffect() {
    com.threadline.proto.threadline.authorization.v1.AclEffect result = com.threadline.proto.threadline.authorization.v1.AclEffect.forNumber(defaultEffect_);
    return result == null ? com.threadline.proto.threadline.authorization.v1.AclEffect.UNRECOGNIZED : result;
  }

  public static final int ENTRIES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.threadline.proto.threadline.authorization.v1.ActorAclEntry> entries_;
  /**
   * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
   */
  @java.lang.Override
  public java.util.List<com.threadline.proto.threadline.authorization.v1.ActorAclEntry> getEntriesList() {
    return entries_;
  }
  /**
   * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.threadline.proto.threadline.authorization.v1.ActorAclEntryOrBuilder> 
      getEntriesOrBuilderList() {
    return entries_;
  }
  /**
   * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
   */
  @java.lang.Override
  public int getEntriesCount() {
    return entries_.size();
  }
  /**
   * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
   */
  @java.lang.Override
  public com.threadline.proto.threadline.authorization.v1.ActorAclEntry getEntries(int index) {
    return entries_.get(index);
  }
  /**
   * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
   */
  @java.lang.Override
  public com.threadline.proto.threadline.authorization.v1.ActorAclEntryOrBuilder getEntriesOrBuilder(
      int index) {
    return entries_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getResource());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(aclVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, aclVersion_);
    }
    if (defaultEffect_ != com.threadline.proto.threadline.authorization.v1.AclEffect.ACL_EFFECT_UNSPECIFIED.getNumber()) {
      output.writeEnum(3, defaultEffect_);
    }
    for (int i = 0; i < entries_.size(); i++) {
      output.writeMessage(4, entries_.get(i));
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResource());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(aclVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, aclVersion_);
    }
    if (defaultEffect_ != com.threadline.proto.threadline.authorization.v1.AclEffect.ACL_EFFECT_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, defaultEffect_);
    }

        {
          final int count = entries_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(entries_.get(i));
          }
          size += 1 * count;
        }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.threadline.proto.threadline.authorization.v1.ResourceAcl)) {
      return super.equals(obj);
    }
    com.threadline.proto.threadline.authorization.v1.ResourceAcl other = (com.threadline.proto.threadline.authorization.v1.ResourceAcl) obj;

    if (hasResource() != other.hasResource()) return false;
    if (hasResource()) {
      if (!getResource()
          .equals(other.getResource())) return false;
    }
    if (!getAclVersion()
        .equals(other.getAclVersion())) return false;
    if (defaultEffect_ != other.defaultEffect_) return false;
    if (!getEntriesList()
        .equals(other.getEntriesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasResource()) {
      hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getResource().hashCode();
    }
    hash = (37 * hash) + ACL_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getAclVersion().hashCode();
    hash = (37 * hash) + DEFAULT_EFFECT_FIELD_NUMBER;
    hash = (53 * hash) + defaultEffect_;
    if (getEntriesCount() > 0) {
      hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
      hash = (53 * hash) + getEntriesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.threadline.proto.threadline.authorization.v1.ResourceAcl parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.authorization.v1.ResourceAcl parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.authorization.v1.ResourceAcl parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.authorization.v1.ResourceAcl parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.authorization.v1.ResourceAcl parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.authorization.v1.ResourceAcl parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.authorization.v1.ResourceAcl parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.threadline.proto.threadline.authorization.v1.ResourceAcl parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.threadline.proto.threadline.authorization.v1.ResourceAcl parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.threadline.proto.threadline.authorization.v1.ResourceAcl parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.threadline.proto.threadline.authorization.v1.ResourceAcl parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.threadline.proto.threadline.authorization.v1.ResourceAcl parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.threadline.proto.threadline.authorization.v1.ResourceAcl prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ResourceAcl is the complete, versioned ACL snapshot used for one decision.
   * With no matching entry, default_effect applies. The default must be an
   * explicit ALLOW or DENY; unspecified and unknown values fail closed. An empty
   * entry set uses default_effect, while conflicting matching entries use DENY.
   * Missing resource, actor, action, effect, identifier, or version data makes
   * the ACL invalid and denies the whole evaluation.
   * </pre>
   *
   * Protobuf type {@code threadline.authorization.v1.ResourceAcl}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:threadline.authorization.v1.ResourceAcl)
      com.threadline.proto.threadline.authorization.v1.ResourceAclOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.threadline.proto.threadline.authorization.v1.AuthorizationProto.internal_static_threadline_authorization_v1_ResourceAcl_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.threadline.proto.threadline.authorization.v1.AuthorizationProto.internal_static_threadline_authorization_v1_ResourceAcl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.threadline.proto.threadline.authorization.v1.ResourceAcl.class, com.threadline.proto.threadline.authorization.v1.ResourceAcl.Builder.class);
    }

    // Construct using com.threadline.proto.threadline.authorization.v1.ResourceAcl.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetResourceFieldBuilder();
        internalGetEntriesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      resource_ = null;
      if (resourceBuilder_ != null) {
        resourceBuilder_.dispose();
        resourceBuilder_ = null;
      }
      aclVersion_ = "";
      defaultEffect_ = 0;
      if (entriesBuilder_ == null) {
        entries_ = java.util.Collections.emptyList();
      } else {
        entries_ = null;
        entriesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.threadline.proto.threadline.authorization.v1.AuthorizationProto.internal_static_threadline_authorization_v1_ResourceAcl_descriptor;
    }

    @java.lang.Override
    public com.threadline.proto.threadline.authorization.v1.ResourceAcl getDefaultInstanceForType() {
      return com.threadline.proto.threadline.authorization.v1.ResourceAcl.getDefaultInstance();
    }

    @java.lang.Override
    public com.threadline.proto.threadline.authorization.v1.ResourceAcl build() {
      com.threadline.proto.threadline.authorization.v1.ResourceAcl result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.threadline.proto.threadline.authorization.v1.ResourceAcl buildPartial() {
      com.threadline.proto.threadline.authorization.v1.ResourceAcl result = new com.threadline.proto.threadline.authorization.v1.ResourceAcl(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.threadline.proto.threadline.authorization.v1.ResourceAcl result) {
      if (entriesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          entries_ = java.util.Collections.unmodifiableList(entries_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.entries_ = entries_;
      } else {
        result.entries_ = entriesBuilder_.build();
      }
    }

    private void buildPartial0(com.threadline.proto.threadline.authorization.v1.ResourceAcl result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.resource_ = resourceBuilder_ == null
            ? resource_
            : resourceBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.aclVersion_ = aclVersion_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.defaultEffect_ = defaultEffect_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.threadline.proto.threadline.authorization.v1.ResourceAcl) {
        return mergeFrom((com.threadline.proto.threadline.authorization.v1.ResourceAcl)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.threadline.proto.threadline.authorization.v1.ResourceAcl other) {
      if (other == com.threadline.proto.threadline.authorization.v1.ResourceAcl.getDefaultInstance()) return this;
      if (other.hasResource()) {
        mergeResource(other.getResource());
      }
      if (!other.getAclVersion().isEmpty()) {
        aclVersion_ = other.aclVersion_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.defaultEffect_ != 0) {
        setDefaultEffectValue(other.getDefaultEffectValue());
      }
      if (entriesBuilder_ == null) {
        if (!other.entries_.isEmpty()) {
          if (entries_.isEmpty()) {
            entries_ = other.entries_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureEntriesIsMutable();
            entries_.addAll(other.entries_);
          }
          onChanged();
        }
      } else {
        if (!other.entries_.isEmpty()) {
          if (entriesBuilder_.isEmpty()) {
            entriesBuilder_.dispose();
            entriesBuilder_ = null;
            entries_ = other.entries_;
            bitField0_ = (bitField0_ & ~0x00000008);
            entriesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetEntriesFieldBuilder() : null;
          } else {
            entriesBuilder_.addAllMessages(other.entries_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetResourceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              aclVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              defaultEffect_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              com.threadline.proto.threadline.authorization.v1.ActorAclEntry m =
                  input.readMessage(
                      com.threadline.proto.threadline.authorization.v1.ActorAclEntry.parser(),
                      extensionRegistry);
              if (entriesBuilder_ == null) {
                ensureEntriesIsMutable();
                entries_.add(m);
              } else {
                entriesBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.threadline.proto.threadline.authorization.v1.ResourceRef resource_;
    private com.google.protobuf.SingleFieldBuilder<
        com.threadline.proto.threadline.authorization.v1.ResourceRef, com.threadline.proto.threadline.authorization.v1.ResourceRef.Builder, com.threadline.proto.threadline.authorization.v1.ResourceRefOrBuilder> resourceBuilder_;
    /**
     * <code>.threadline.authorization.v1.ResourceRef resource = 1 [json_name = "resource"];</code>
     * @return Whether the resource field is set.
     */
    public boolean hasResource() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.threadline.authorization.v1.ResourceRef resource = 1 [json_name = "resource"];</code>
     * @return The resource.
     */
    public com.threadline.proto.threadline.authorization.v1.ResourceRef getResource() {
      if (resourceBuilder_ == null) {
        return resource_ == null ? com.threadline.proto.threadline.authorization.v1.ResourceRef.getDefaultInstance() : resource_;
      } else {
        return resourceBuilder_.getMessage();
      }
    }
    /**
     * <code>.threadline.authorization.v1.ResourceRef resource = 1 [json_name = "resource"];</code>
     */
    public Builder setResource(com.threadline.proto.threadline.authorization.v1.ResourceRef value) {
      if (resourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
      } else {
        resourceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.threadline.authorization.v1.ResourceRef resource = 1 [json_name = "resource"];</code>
     */
    public Builder setResource(
        com.threadline.proto.threadline.authorization.v1.ResourceRef.Builder builderForValue) {
      if (resourceBuilder_ == null) {
        resource_ = builderForValue.build();
      } else {
        resourceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.threadline.authorization.v1.ResourceRef resource = 1 [json_name = "resource"];</code>
     */
    public Builder mergeResource(com.threadline.proto.threadline.authorization.v1.ResourceRef value) {
      if (resourceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          resource_ != null &&
          resource_ != com.threadline.proto.threadline.authorization.v1.ResourceRef.getDefaultInstance()) {
          getResourceBuilder().mergeFrom(value);
        } else {
          resource_ = value;
        }
      } else {
        resourceBuilder_.mergeFrom(value);
      }
      if (resource_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.threadline.authorization.v1.ResourceRef resource = 1 [json_name = "resource"];</code>
     */
    public Builder clearResource() {
      bitField0_ = (bitField0_ & ~0x00000001);
      resource_ = null;
      if (resourceBuilder_ != null) {
        resourceBuilder_.dispose();
        resourceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.threadline.authorization.v1.ResourceRef resource = 1 [json_name = "resource"];</code>
     */
    public com.threadline.proto.threadline.authorization.v1.ResourceRef.Builder getResourceBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetResourceFieldBuilder().getBuilder();
    }
    /**
     * <code>.threadline.authorization.v1.ResourceRef resource = 1 [json_name = "resource"];</code>
     */
    public com.threadline.proto.threadline.authorization.v1.ResourceRefOrBuilder getResourceOrBuilder() {
      if (resourceBuilder_ != null) {
        return resourceBuilder_.getMessageOrBuilder();
      } else {
        return resource_ == null ?
            com.threadline.proto.threadline.authorization.v1.ResourceRef.getDefaultInstance() : resource_;
      }
    }
    /**
     * <code>.threadline.authorization.v1.ResourceRef resource = 1 [json_name = "resource"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.threadline.proto.threadline.authorization.v1.ResourceRef, com.threadline.proto.threadline.authorization.v1.ResourceRef.Builder, com.threadline.proto.threadline.authorization.v1.ResourceRefOrBuilder> 
        internalGetResourceFieldBuilder() {
      if (resourceBuilder_ == null) {
        resourceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.threadline.proto.threadline.authorization.v1.ResourceRef, com.threadline.proto.threadline.authorization.v1.ResourceRef.Builder, com.threadline.proto.threadline.authorization.v1.ResourceRefOrBuilder>(
                getResource(),
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      return resourceBuilder_;
    }

    private java.lang.Object aclVersion_ = "";
    /**
     * <code>string acl_version = 2 [json_name = "aclVersion"];</code>
     * @return The aclVersion.
     */
    public java.lang.String getAclVersion() {
      java.lang.Object ref = aclVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aclVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string acl_version = 2 [json_name = "aclVersion"];</code>
     * @return The bytes for aclVersion.
     */
    public com.google.protobuf.ByteString
        getAclVersionBytes() {
      java.lang.Object ref = aclVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aclVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string acl_version = 2 [json_name = "aclVersion"];</code>
     * @param value The aclVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAclVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      aclVersion_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string acl_version = 2 [json_name = "aclVersion"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAclVersion() {
      aclVersion_ = getDefaultInstance().getAclVersion();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string acl_version = 2 [json_name = "aclVersion"];</code>
     * @param value The bytes for aclVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAclVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      aclVersion_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int defaultEffect_ = 0;
    /**
     * <code>.threadline.authorization.v1.AclEffect default_effect = 3 [json_name = "defaultEffect"];</code>
     * @return The enum numeric value on the wire for defaultEffect.
     */
    @java.lang.Override public int getDefaultEffectValue() {
      return defaultEffect_;
    }
    /**
     * <code>.threadline.authorization.v1.AclEffect default_effect = 3 [json_name = "defaultEffect"];</code>
     * @param value The enum numeric value on the wire for defaultEffect to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultEffectValue(int value) {
      defaultEffect_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.threadline.authorization.v1.AclEffect default_effect = 3 [json_name = "defaultEffect"];</code>
     * @return The defaultEffect.
     */
    @java.lang.Override
    public com.threadline.proto.threadline.authorization.v1.AclEffect getDefaultEffect() {
      com.threadline.proto.threadline.authorization.v1.AclEffect result = com.threadline.proto.threadline.authorization.v1.AclEffect.forNumber(defaultEffect_);
      return result == null ? com.threadline.proto.threadline.authorization.v1.AclEffect.UNRECOGNIZED : result;
    }
    /**
     * <code>.threadline.authorization.v1.AclEffect default_effect = 3 [json_name = "defaultEffect"];</code>
     * @param value The defaultEffect to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setDefaultEffect(com.threadline.proto.threadline.authorization.v1.AclEffect value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000004;
      defaultEffect_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.threadline.authorization.v1.AclEffect default_effect = 3 [json_name = "defaultEffect"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDefaultEffect() {
      bitField0_ = (bitField0_ & ~0x00000004);
      defaultEffect_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.threadline.proto.threadline.authorization.v1.ActorAclEntry> entries_ =
      java.util.Collections.emptyList();
    private void ensureEntriesIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        entries_ = new java.util.ArrayList<com.threadline.proto.threadline.authorization.v1.ActorAclEntry>(entries_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.threadline.proto.threadline.authorization.v1.ActorAclEntry, com.threadline.proto.threadline.authorization.v1.ActorAclEntry.Builder, com.threadline.proto.threadline.authorization.v1.ActorAclEntryOrBuilder> entriesBuilder_;

    /**
     * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
     */
    public java.util.List<com.threadline.proto.threadline.authorization.v1.ActorAclEntry> getEntriesList() {
      if (entriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(entries_);
      } else {
        return entriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
     */
    public int getEntriesCount() {
      if (entriesBuilder_ == null) {
        return entries_.size();
      } else {
        return entriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
     */
    public com.threadline.proto.threadline.authorization.v1.ActorAclEntry getEntries(int index) {
      if (entriesBuilder_ == null) {
        return entries_.get(index);
      } else {
        return entriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
     */
    public Builder setEntries(
        int index, com.threadline.proto.threadline.authorization.v1.ActorAclEntry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.set(index, value);
        onChanged();
      } else {
        entriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
     */
    public Builder setEntries(
        int index, com.threadline.proto.threadline.authorization.v1.ActorAclEntry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.set(index, builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
     */
    public Builder addEntries(com.threadline.proto.threadline.authorization.v1.ActorAclEntry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.add(value);
        onChanged();
      } else {
        entriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
     */
    public Builder addEntries(
        int index, com.threadline.proto.threadline.authorization.v1.ActorAclEntry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.add(index, value);
        onChanged();
      } else {
        entriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
     */
    public Builder addEntries(
        com.threadline.proto.threadline.authorization.v1.ActorAclEntry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.add(builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
     */
    public Builder addEntries(
        int index, com.threadline.proto.threadline.authorization.v1.ActorAclEntry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.add(index, builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
     */
    public Builder addAllEntries(
        java.lang.Iterable<? extends com.threadline.proto.threadline.authorization.v1.ActorAclEntry> values) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entries_);
        onChanged();
      } else {
        entriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
     */
    public Builder clearEntries() {
      if (entriesBuilder_ == null) {
        entries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        entriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
     */
    public Builder removeEntries(int index) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.remove(index);
        onChanged();
      } else {
        entriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
     */
    public com.threadline.proto.threadline.authorization.v1.ActorAclEntry.Builder getEntriesBuilder(
        int index) {
      return internalGetEntriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
     */
    public com.threadline.proto.threadline.authorization.v1.ActorAclEntryOrBuilder getEntriesOrBuilder(
        int index) {
      if (entriesBuilder_ == null) {
        return entries_.get(index);  } else {
        return entriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
     */
    public java.util.List<? extends com.threadline.proto.threadline.authorization.v1.ActorAclEntryOrBuilder> 
         getEntriesOrBuilderList() {
      if (entriesBuilder_ != null) {
        return entriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(entries_);
      }
    }
    /**
     * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
     */
    public com.threadline.proto.threadline.authorization.v1.ActorAclEntry.Builder addEntriesBuilder() {
      return internalGetEntriesFieldBuilder().addBuilder(
          com.threadline.proto.threadline.authorization.v1.ActorAclEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
     */
    public com.threadline.proto.threadline.authorization.v1.ActorAclEntry.Builder addEntriesBuilder(
        int index) {
      return internalGetEntriesFieldBuilder().addBuilder(
          index, com.threadline.proto.threadline.authorization.v1.ActorAclEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .threadline.authorization.v1.ActorAclEntry entries = 4 [json_name = "entries"];</code>
     */
    public java.util.List<com.threadline.proto.threadline.authorization.v1.ActorAclEntry.Builder> 
         getEntriesBuilderList() {
      return internalGetEntriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.threadline.proto.threadline.authorization.v1.ActorAclEntry, com.threadline.proto.threadline.authorization.v1.ActorAclEntry.Builder, com.threadline.proto.threadline.authorization.v1.ActorAclEntryOrBuilder> 
        internalGetEntriesFieldBuilder() {
      if (entriesBuilder_ == null) {
        entriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.threadline.proto.threadline.authorization.v1.ActorAclEntry, com.threadline.proto.threadline.authorization.v1.ActorAclEntry.Builder, com.threadline.proto.threadline.authorization.v1.ActorAclEntryOrBuilder>(
                entries_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        entries_ = null;
      }
      return entriesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:threadline.authorization.v1.ResourceAcl)
  }

  // @@protoc_insertion_point(class_scope:threadline.authorization.v1.ResourceAcl)
  private static final com.threadline.proto.threadline.authorization.v1.ResourceAcl DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.threadline.proto.threadline.authorization.v1.ResourceAcl();
  }

  public static com.threadline.proto.threadline.authorization.v1.ResourceAcl getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResourceAcl>
      PARSER = new com.google.protobuf.AbstractParser<ResourceAcl>() {
    @java.lang.Override
    public ResourceAcl parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResourceAcl> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResourceAcl> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.threadline.proto.threadline.authorization.v1.ResourceAcl getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

