// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/crypto/v1/key_service.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.crypto.v1;

@com.google.protobuf.Generated
public interface ClaimKeyPackagesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threadline.crypto.v1.ClaimKeyPackagesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string e2ee_group_id = 1 [json_name = "e2eeGroupId"];</code>
   * @return The e2eeGroupId.
   */
  java.lang.String getE2EeGroupId();
  /**
   * <code>string e2ee_group_id = 1 [json_name = "e2eeGroupId"];</code>
   * @return The bytes for e2eeGroupId.
   */
  com.google.protobuf.ByteString
      getE2EeGroupIdBytes();

  /**
   * <code>repeated string target_device_ids = 2 [json_name = "targetDeviceIds"];</code>
   * @return A list containing the targetDeviceIds.
   */
  java.util.List<java.lang.String>
      getTargetDeviceIdsList();
  /**
   * <code>repeated string target_device_ids = 2 [json_name = "targetDeviceIds"];</code>
   * @return The count of targetDeviceIds.
   */
  int getTargetDeviceIdsCount();
  /**
   * <code>repeated string target_device_ids = 2 [json_name = "targetDeviceIds"];</code>
   * @param index The index of the element to return.
   * @return The targetDeviceIds at the given index.
   */
  java.lang.String getTargetDeviceIds(int index);
  /**
   * <code>repeated string target_device_ids = 2 [json_name = "targetDeviceIds"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the targetDeviceIds at the given index.
   */
  com.google.protobuf.ByteString
      getTargetDeviceIdsBytes(int index);

  /**
   * <pre>
   * The pending membership authorization that will consume these packages.
   * A claim is committed atomically with its consumption markers.
   * </pre>
   *
   * <code>string authorization_id = 3 [json_name = "authorizationId"];</code>
   * @return The authorizationId.
   */
  java.lang.String getAuthorizationId();
  /**
   * <pre>
   * The pending membership authorization that will consume these packages.
   * A claim is committed atomically with its consumption markers.
   * </pre>
   *
   * <code>string authorization_id = 3 [json_name = "authorizationId"];</code>
   * @return The bytes for authorizationId.
   */
  com.google.protobuf.ByteString
      getAuthorizationIdBytes();

  /**
   * <pre>
   * Client-generated replay identity. An exact retry returns the original
   * package set; a conflicting retry fails with ERROR_CODE_REPLAY_DETECTED.
   * </pre>
   *
   * <code>string claim_id = 4 [json_name = "claimId"];</code>
   * @return The claimId.
   */
  java.lang.String getClaimId();
  /**
   * <pre>
   * Client-generated replay identity. An exact retry returns the original
   * package set; a conflicting retry fails with ERROR_CODE_REPLAY_DETECTED.
   * </pre>
   *
   * <code>string claim_id = 4 [json_name = "claimId"];</code>
   * @return The bytes for claimId.
   */
  com.google.protobuf.ByteString
      getClaimIdBytes();
}
