// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/crypto/v1/key_service.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.crypto.v1;

@com.google.protobuf.Generated
public interface CreateTargetedRecoveryCaseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threadline.crypto.v1.CreateTargetedRecoveryCaseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.threadline.type.v1.EncryptedField reason = 1 [json_name = "reason"];</code>
   * @return Whether the reason field is set.
   */
  boolean hasReason();
  /**
   * <code>.threadline.type.v1.EncryptedField reason = 1 [json_name = "reason"];</code>
   * @return The reason.
   */
  com.threadline.proto.threadline.type.v1.EncryptedField getReason();
  /**
   * <code>.threadline.type.v1.EncryptedField reason = 1 [json_name = "reason"];</code>
   */
  com.threadline.proto.threadline.type.v1.EncryptedFieldOrBuilder getReasonOrBuilder();

  /**
   * <code>string recovery_recipient_device_id = 2 [json_name = "recoveryRecipientDeviceId"];</code>
   * @return The recoveryRecipientDeviceId.
   */
  java.lang.String getRecoveryRecipientDeviceId();
  /**
   * <code>string recovery_recipient_device_id = 2 [json_name = "recoveryRecipientDeviceId"];</code>
   * @return The bytes for recoveryRecipientDeviceId.
   */
  com.google.protobuf.ByteString
      getRecoveryRecipientDeviceIdBytes();

  /**
   * <code>repeated .threadline.crypto.v1.RecoveryScope scopes = 3 [json_name = "scopes"];</code>
   */
  java.util.List<com.threadline.proto.threadline.crypto.v1.RecoveryScope> 
      getScopesList();
  /**
   * <code>repeated .threadline.crypto.v1.RecoveryScope scopes = 3 [json_name = "scopes"];</code>
   */
  com.threadline.proto.threadline.crypto.v1.RecoveryScope getScopes(int index);
  /**
   * <code>repeated .threadline.crypto.v1.RecoveryScope scopes = 3 [json_name = "scopes"];</code>
   */
  int getScopesCount();
  /**
   * <code>repeated .threadline.crypto.v1.RecoveryScope scopes = 3 [json_name = "scopes"];</code>
   */
  java.util.List<? extends com.threadline.proto.threadline.crypto.v1.RecoveryScopeOrBuilder> 
      getScopesOrBuilderList();
  /**
   * <code>repeated .threadline.crypto.v1.RecoveryScope scopes = 3 [json_name = "scopes"];</code>
   */
  com.threadline.proto.threadline.crypto.v1.RecoveryScopeOrBuilder getScopesOrBuilder(
      int index);

  /**
   * <code>string request_id = 4 [json_name = "requestId"];</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string request_id = 4 [json_name = "requestId"];</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();
}
