// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/crypto/v1/key_service.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.crypto.v1;

/**
 * Protobuf type {@code threadline.crypto.v1.DecideRecoveryCaseRequest}
 */
@com.google.protobuf.Generated
public final class DecideRecoveryCaseRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:threadline.crypto.v1.DecideRecoveryCaseRequest)
    DecideRecoveryCaseRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "DecideRecoveryCaseRequest");
  }
  // Use DecideRecoveryCaseRequest.newBuilder() to construct.
  private DecideRecoveryCaseRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DecideRecoveryCaseRequest() {
    recoveryCaseId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.threadline.proto.threadline.crypto.v1.KeyServiceProto.internal_static_threadline_crypto_v1_DecideRecoveryCaseRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.threadline.proto.threadline.crypto.v1.KeyServiceProto.internal_static_threadline_crypto_v1_DecideRecoveryCaseRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.threadline.proto.threadline.crypto.v1.KeyServiceProto.internal_static_threadline_crypto_v1_DecideRecoveryCaseRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest.class, com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest.Builder.class);
  }

  private int bitField0_;
  public static final int RECOVERY_CASE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object recoveryCaseId_ = "";
  /**
   * <code>string recovery_case_id = 1 [json_name = "recoveryCaseId"];</code>
   * @return The recoveryCaseId.
   */
  @java.lang.Override
  public java.lang.String getRecoveryCaseId() {
    java.lang.Object ref = recoveryCaseId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recoveryCaseId_ = s;
      return s;
    }
  }
  /**
   * <code>string recovery_case_id = 1 [json_name = "recoveryCaseId"];</code>
   * @return The bytes for recoveryCaseId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecoveryCaseIdBytes() {
    java.lang.Object ref = recoveryCaseId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recoveryCaseId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPROVED_FIELD_NUMBER = 2;
  private boolean approved_ = false;
  /**
   * <code>bool approved = 2 [json_name = "approved"];</code>
   * @return The approved.
   */
  @java.lang.Override
  public boolean getApproved() {
    return approved_;
  }

  public static final int NOTE_FIELD_NUMBER = 3;
  private com.threadline.proto.threadline.type.v1.EncryptedField note_;
  /**
   * <code>.threadline.type.v1.EncryptedField note = 3 [json_name = "note"];</code>
   * @return Whether the note field is set.
   */
  @java.lang.Override
  public boolean hasNote() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.threadline.type.v1.EncryptedField note = 3 [json_name = "note"];</code>
   * @return The note.
   */
  @java.lang.Override
  public com.threadline.proto.threadline.type.v1.EncryptedField getNote() {
    return note_ == null ? com.threadline.proto.threadline.type.v1.EncryptedField.getDefaultInstance() : note_;
  }
  /**
   * <code>.threadline.type.v1.EncryptedField note = 3 [json_name = "note"];</code>
   */
  @java.lang.Override
  public com.threadline.proto.threadline.type.v1.EncryptedFieldOrBuilder getNoteOrBuilder() {
    return note_ == null ? com.threadline.proto.threadline.type.v1.EncryptedField.getDefaultInstance() : note_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(recoveryCaseId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, recoveryCaseId_);
    }
    if (approved_ != false) {
      output.writeBool(2, approved_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getNote());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(recoveryCaseId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, recoveryCaseId_);
    }
    if (approved_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, approved_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getNote());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest)) {
      return super.equals(obj);
    }
    com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest other = (com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest) obj;

    if (!getRecoveryCaseId()
        .equals(other.getRecoveryCaseId())) return false;
    if (getApproved()
        != other.getApproved()) return false;
    if (hasNote() != other.hasNote()) return false;
    if (hasNote()) {
      if (!getNote()
          .equals(other.getNote())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RECOVERY_CASE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRecoveryCaseId().hashCode();
    hash = (37 * hash) + APPROVED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getApproved());
    if (hasNote()) {
      hash = (37 * hash) + NOTE_FIELD_NUMBER;
      hash = (53 * hash) + getNote().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code threadline.crypto.v1.DecideRecoveryCaseRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:threadline.crypto.v1.DecideRecoveryCaseRequest)
      com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.threadline.proto.threadline.crypto.v1.KeyServiceProto.internal_static_threadline_crypto_v1_DecideRecoveryCaseRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.threadline.proto.threadline.crypto.v1.KeyServiceProto.internal_static_threadline_crypto_v1_DecideRecoveryCaseRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest.class, com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest.Builder.class);
    }

    // Construct using com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetNoteFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      recoveryCaseId_ = "";
      approved_ = false;
      note_ = null;
      if (noteBuilder_ != null) {
        noteBuilder_.dispose();
        noteBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.threadline.proto.threadline.crypto.v1.KeyServiceProto.internal_static_threadline_crypto_v1_DecideRecoveryCaseRequest_descriptor;
    }

    @java.lang.Override
    public com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest getDefaultInstanceForType() {
      return com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest build() {
      com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest buildPartial() {
      com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest result = new com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.recoveryCaseId_ = recoveryCaseId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.approved_ = approved_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.note_ = noteBuilder_ == null
            ? note_
            : noteBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest) {
        return mergeFrom((com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest other) {
      if (other == com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest.getDefaultInstance()) return this;
      if (!other.getRecoveryCaseId().isEmpty()) {
        recoveryCaseId_ = other.recoveryCaseId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getApproved() != false) {
        setApproved(other.getApproved());
      }
      if (other.hasNote()) {
        mergeNote(other.getNote());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              recoveryCaseId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              approved_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  internalGetNoteFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object recoveryCaseId_ = "";
    /**
     * <code>string recovery_case_id = 1 [json_name = "recoveryCaseId"];</code>
     * @return The recoveryCaseId.
     */
    public java.lang.String getRecoveryCaseId() {
      java.lang.Object ref = recoveryCaseId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recoveryCaseId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string recovery_case_id = 1 [json_name = "recoveryCaseId"];</code>
     * @return The bytes for recoveryCaseId.
     */
    public com.google.protobuf.ByteString
        getRecoveryCaseIdBytes() {
      java.lang.Object ref = recoveryCaseId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recoveryCaseId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string recovery_case_id = 1 [json_name = "recoveryCaseId"];</code>
     * @param value The recoveryCaseId to set.
     * @return This builder for chaining.
     */
    public Builder setRecoveryCaseId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      recoveryCaseId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string recovery_case_id = 1 [json_name = "recoveryCaseId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRecoveryCaseId() {
      recoveryCaseId_ = getDefaultInstance().getRecoveryCaseId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string recovery_case_id = 1 [json_name = "recoveryCaseId"];</code>
     * @param value The bytes for recoveryCaseId to set.
     * @return This builder for chaining.
     */
    public Builder setRecoveryCaseIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      recoveryCaseId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean approved_ ;
    /**
     * <code>bool approved = 2 [json_name = "approved"];</code>
     * @return The approved.
     */
    @java.lang.Override
    public boolean getApproved() {
      return approved_;
    }
    /**
     * <code>bool approved = 2 [json_name = "approved"];</code>
     * @param value The approved to set.
     * @return This builder for chaining.
     */
    public Builder setApproved(boolean value) {

      approved_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool approved = 2 [json_name = "approved"];</code>
     * @return This builder for chaining.
     */
    public Builder clearApproved() {
      bitField0_ = (bitField0_ & ~0x00000002);
      approved_ = false;
      onChanged();
      return this;
    }

    private com.threadline.proto.threadline.type.v1.EncryptedField note_;
    private com.google.protobuf.SingleFieldBuilder<
        com.threadline.proto.threadline.type.v1.EncryptedField, com.threadline.proto.threadline.type.v1.EncryptedField.Builder, com.threadline.proto.threadline.type.v1.EncryptedFieldOrBuilder> noteBuilder_;
    /**
     * <code>.threadline.type.v1.EncryptedField note = 3 [json_name = "note"];</code>
     * @return Whether the note field is set.
     */
    public boolean hasNote() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.threadline.type.v1.EncryptedField note = 3 [json_name = "note"];</code>
     * @return The note.
     */
    public com.threadline.proto.threadline.type.v1.EncryptedField getNote() {
      if (noteBuilder_ == null) {
        return note_ == null ? com.threadline.proto.threadline.type.v1.EncryptedField.getDefaultInstance() : note_;
      } else {
        return noteBuilder_.getMessage();
      }
    }
    /**
     * <code>.threadline.type.v1.EncryptedField note = 3 [json_name = "note"];</code>
     */
    public Builder setNote(com.threadline.proto.threadline.type.v1.EncryptedField value) {
      if (noteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        note_ = value;
      } else {
        noteBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.threadline.type.v1.EncryptedField note = 3 [json_name = "note"];</code>
     */
    public Builder setNote(
        com.threadline.proto.threadline.type.v1.EncryptedField.Builder builderForValue) {
      if (noteBuilder_ == null) {
        note_ = builderForValue.build();
      } else {
        noteBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.threadline.type.v1.EncryptedField note = 3 [json_name = "note"];</code>
     */
    public Builder mergeNote(com.threadline.proto.threadline.type.v1.EncryptedField value) {
      if (noteBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          note_ != null &&
          note_ != com.threadline.proto.threadline.type.v1.EncryptedField.getDefaultInstance()) {
          getNoteBuilder().mergeFrom(value);
        } else {
          note_ = value;
        }
      } else {
        noteBuilder_.mergeFrom(value);
      }
      if (note_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.threadline.type.v1.EncryptedField note = 3 [json_name = "note"];</code>
     */
    public Builder clearNote() {
      bitField0_ = (bitField0_ & ~0x00000004);
      note_ = null;
      if (noteBuilder_ != null) {
        noteBuilder_.dispose();
        noteBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.threadline.type.v1.EncryptedField note = 3 [json_name = "note"];</code>
     */
    public com.threadline.proto.threadline.type.v1.EncryptedField.Builder getNoteBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetNoteFieldBuilder().getBuilder();
    }
    /**
     * <code>.threadline.type.v1.EncryptedField note = 3 [json_name = "note"];</code>
     */
    public com.threadline.proto.threadline.type.v1.EncryptedFieldOrBuilder getNoteOrBuilder() {
      if (noteBuilder_ != null) {
        return noteBuilder_.getMessageOrBuilder();
      } else {
        return note_ == null ?
            com.threadline.proto.threadline.type.v1.EncryptedField.getDefaultInstance() : note_;
      }
    }
    /**
     * <code>.threadline.type.v1.EncryptedField note = 3 [json_name = "note"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.threadline.proto.threadline.type.v1.EncryptedField, com.threadline.proto.threadline.type.v1.EncryptedField.Builder, com.threadline.proto.threadline.type.v1.EncryptedFieldOrBuilder> 
        internalGetNoteFieldBuilder() {
      if (noteBuilder_ == null) {
        noteBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.threadline.proto.threadline.type.v1.EncryptedField, com.threadline.proto.threadline.type.v1.EncryptedField.Builder, com.threadline.proto.threadline.type.v1.EncryptedFieldOrBuilder>(
                getNote(),
                getParentForChildren(),
                isClean());
        note_ = null;
      }
      return noteBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:threadline.crypto.v1.DecideRecoveryCaseRequest)
  }

  // @@protoc_insertion_point(class_scope:threadline.crypto.v1.DecideRecoveryCaseRequest)
  private static final com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest();
  }

  public static com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DecideRecoveryCaseRequest>
      PARSER = new com.google.protobuf.AbstractParser<DecideRecoveryCaseRequest>() {
    @java.lang.Override
    public DecideRecoveryCaseRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DecideRecoveryCaseRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DecideRecoveryCaseRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.threadline.proto.threadline.crypto.v1.DecideRecoveryCaseRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

