// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/crypto/v1/key_service.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.crypto.v1;

/**
 * Protobuf type {@code threadline.crypto.v1.GetRecoveryEvidenceRequest}
 */
@com.google.protobuf.Generated
public final class GetRecoveryEvidenceRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:threadline.crypto.v1.GetRecoveryEvidenceRequest)
    GetRecoveryEvidenceRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "GetRecoveryEvidenceRequest");
  }
  // Use GetRecoveryEvidenceRequest.newBuilder() to construct.
  private GetRecoveryEvidenceRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetRecoveryEvidenceRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.threadline.proto.threadline.crypto.v1.KeyServiceProto.internal_static_threadline_crypto_v1_GetRecoveryEvidenceRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.threadline.proto.threadline.crypto.v1.KeyServiceProto.internal_static_threadline_crypto_v1_GetRecoveryEvidenceRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.threadline.proto.threadline.crypto.v1.KeyServiceProto.internal_static_threadline_crypto_v1_GetRecoveryEvidenceRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest.class, com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest.Builder.class);
  }

  private int bitField0_;
  public static final int GRANT_FIELD_NUMBER = 1;
  private com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant grant_;
  /**
   * <pre>
   * Signed by isolated Recovery Control after approval. Core verifies the mTLS
   * caller, signature and expiry before discovering records; the caller need
   * not and must not pre-supply envelope hashes.
   * </pre>
   *
   * <code>.threadline.crypto.v1.RecoveryEvidenceGrant grant = 1 [json_name = "grant"];</code>
   * @return Whether the grant field is set.
   */
  @java.lang.Override
  public boolean hasGrant() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Signed by isolated Recovery Control after approval. Core verifies the mTLS
   * caller, signature and expiry before discovering records; the caller need
   * not and must not pre-supply envelope hashes.
   * </pre>
   *
   * <code>.threadline.crypto.v1.RecoveryEvidenceGrant grant = 1 [json_name = "grant"];</code>
   * @return The grant.
   */
  @java.lang.Override
  public com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant getGrant() {
    return grant_ == null ? com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant.getDefaultInstance() : grant_;
  }
  /**
   * <pre>
   * Signed by isolated Recovery Control after approval. Core verifies the mTLS
   * caller, signature and expiry before discovering records; the caller need
   * not and must not pre-supply envelope hashes.
   * </pre>
   *
   * <code>.threadline.crypto.v1.RecoveryEvidenceGrant grant = 1 [json_name = "grant"];</code>
   */
  @java.lang.Override
  public com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrantOrBuilder getGrantOrBuilder() {
    return grant_ == null ? com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant.getDefaultInstance() : grant_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getGrant());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getGrant());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest)) {
      return super.equals(obj);
    }
    com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest other = (com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest) obj;

    if (hasGrant() != other.hasGrant()) return false;
    if (hasGrant()) {
      if (!getGrant()
          .equals(other.getGrant())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasGrant()) {
      hash = (37 * hash) + GRANT_FIELD_NUMBER;
      hash = (53 * hash) + getGrant().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code threadline.crypto.v1.GetRecoveryEvidenceRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:threadline.crypto.v1.GetRecoveryEvidenceRequest)
      com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.threadline.proto.threadline.crypto.v1.KeyServiceProto.internal_static_threadline_crypto_v1_GetRecoveryEvidenceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.threadline.proto.threadline.crypto.v1.KeyServiceProto.internal_static_threadline_crypto_v1_GetRecoveryEvidenceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest.class, com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest.Builder.class);
    }

    // Construct using com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetGrantFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      grant_ = null;
      if (grantBuilder_ != null) {
        grantBuilder_.dispose();
        grantBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.threadline.proto.threadline.crypto.v1.KeyServiceProto.internal_static_threadline_crypto_v1_GetRecoveryEvidenceRequest_descriptor;
    }

    @java.lang.Override
    public com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest getDefaultInstanceForType() {
      return com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest build() {
      com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest buildPartial() {
      com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest result = new com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.grant_ = grantBuilder_ == null
            ? grant_
            : grantBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest) {
        return mergeFrom((com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest other) {
      if (other == com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest.getDefaultInstance()) return this;
      if (other.hasGrant()) {
        mergeGrant(other.getGrant());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetGrantFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant grant_;
    private com.google.protobuf.SingleFieldBuilder<
        com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant, com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant.Builder, com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrantOrBuilder> grantBuilder_;
    /**
     * <pre>
     * Signed by isolated Recovery Control after approval. Core verifies the mTLS
     * caller, signature and expiry before discovering records; the caller need
     * not and must not pre-supply envelope hashes.
     * </pre>
     *
     * <code>.threadline.crypto.v1.RecoveryEvidenceGrant grant = 1 [json_name = "grant"];</code>
     * @return Whether the grant field is set.
     */
    public boolean hasGrant() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Signed by isolated Recovery Control after approval. Core verifies the mTLS
     * caller, signature and expiry before discovering records; the caller need
     * not and must not pre-supply envelope hashes.
     * </pre>
     *
     * <code>.threadline.crypto.v1.RecoveryEvidenceGrant grant = 1 [json_name = "grant"];</code>
     * @return The grant.
     */
    public com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant getGrant() {
      if (grantBuilder_ == null) {
        return grant_ == null ? com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant.getDefaultInstance() : grant_;
      } else {
        return grantBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Signed by isolated Recovery Control after approval. Core verifies the mTLS
     * caller, signature and expiry before discovering records; the caller need
     * not and must not pre-supply envelope hashes.
     * </pre>
     *
     * <code>.threadline.crypto.v1.RecoveryEvidenceGrant grant = 1 [json_name = "grant"];</code>
     */
    public Builder setGrant(com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant value) {
      if (grantBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        grant_ = value;
      } else {
        grantBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Signed by isolated Recovery Control after approval. Core verifies the mTLS
     * caller, signature and expiry before discovering records; the caller need
     * not and must not pre-supply envelope hashes.
     * </pre>
     *
     * <code>.threadline.crypto.v1.RecoveryEvidenceGrant grant = 1 [json_name = "grant"];</code>
     */
    public Builder setGrant(
        com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant.Builder builderForValue) {
      if (grantBuilder_ == null) {
        grant_ = builderForValue.build();
      } else {
        grantBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Signed by isolated Recovery Control after approval. Core verifies the mTLS
     * caller, signature and expiry before discovering records; the caller need
     * not and must not pre-supply envelope hashes.
     * </pre>
     *
     * <code>.threadline.crypto.v1.RecoveryEvidenceGrant grant = 1 [json_name = "grant"];</code>
     */
    public Builder mergeGrant(com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant value) {
      if (grantBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          grant_ != null &&
          grant_ != com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant.getDefaultInstance()) {
          getGrantBuilder().mergeFrom(value);
        } else {
          grant_ = value;
        }
      } else {
        grantBuilder_.mergeFrom(value);
      }
      if (grant_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Signed by isolated Recovery Control after approval. Core verifies the mTLS
     * caller, signature and expiry before discovering records; the caller need
     * not and must not pre-supply envelope hashes.
     * </pre>
     *
     * <code>.threadline.crypto.v1.RecoveryEvidenceGrant grant = 1 [json_name = "grant"];</code>
     */
    public Builder clearGrant() {
      bitField0_ = (bitField0_ & ~0x00000001);
      grant_ = null;
      if (grantBuilder_ != null) {
        grantBuilder_.dispose();
        grantBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Signed by isolated Recovery Control after approval. Core verifies the mTLS
     * caller, signature and expiry before discovering records; the caller need
     * not and must not pre-supply envelope hashes.
     * </pre>
     *
     * <code>.threadline.crypto.v1.RecoveryEvidenceGrant grant = 1 [json_name = "grant"];</code>
     */
    public com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant.Builder getGrantBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetGrantFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Signed by isolated Recovery Control after approval. Core verifies the mTLS
     * caller, signature and expiry before discovering records; the caller need
     * not and must not pre-supply envelope hashes.
     * </pre>
     *
     * <code>.threadline.crypto.v1.RecoveryEvidenceGrant grant = 1 [json_name = "grant"];</code>
     */
    public com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrantOrBuilder getGrantOrBuilder() {
      if (grantBuilder_ != null) {
        return grantBuilder_.getMessageOrBuilder();
      } else {
        return grant_ == null ?
            com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant.getDefaultInstance() : grant_;
      }
    }
    /**
     * <pre>
     * Signed by isolated Recovery Control after approval. Core verifies the mTLS
     * caller, signature and expiry before discovering records; the caller need
     * not and must not pre-supply envelope hashes.
     * </pre>
     *
     * <code>.threadline.crypto.v1.RecoveryEvidenceGrant grant = 1 [json_name = "grant"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant, com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant.Builder, com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrantOrBuilder> 
        internalGetGrantFieldBuilder() {
      if (grantBuilder_ == null) {
        grantBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant, com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrant.Builder, com.threadline.proto.threadline.crypto.v1.RecoveryEvidenceGrantOrBuilder>(
                getGrant(),
                getParentForChildren(),
                isClean());
        grant_ = null;
      }
      return grantBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:threadline.crypto.v1.GetRecoveryEvidenceRequest)
  }

  // @@protoc_insertion_point(class_scope:threadline.crypto.v1.GetRecoveryEvidenceRequest)
  private static final com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest();
  }

  public static com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetRecoveryEvidenceRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetRecoveryEvidenceRequest>() {
    @java.lang.Override
    public GetRecoveryEvidenceRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetRecoveryEvidenceRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetRecoveryEvidenceRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.threadline.proto.threadline.crypto.v1.GetRecoveryEvidenceRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

