// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/crypto/v1/crypto.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.crypto.v1;

/**
 * <pre>
 * MlsWireMessage transports MLS handshake material.
 *
 * The server accepts or orders these using only the fields below plus Device
 * authorization and size limits. Cryptographic validity is a client
 * responsibility: a malicious or faulty server can still delay, drop, replay or
 * fork delivery, and clients detect that through MLS transcript state, strict
 * Epoch continuity and gap repair. E2EE does not promise denial-of-service
 * resistance.
 * </pre>
 *
 * Protobuf type {@code threadline.crypto.v1.MlsWireMessage}
 */
@com.google.protobuf.Generated
public final class MlsWireMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:threadline.crypto.v1.MlsWireMessage)
    MlsWireMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "MlsWireMessage");
  }
  // Use MlsWireMessage.newBuilder() to construct.
  private MlsWireMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MlsWireMessage() {
    messageType_ = 0;
    mlsData_ = com.google.protobuf.ByteString.EMPTY;
    authorizationId_ = "";
    targetDeviceIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    tenantId_ = "";
    e2EeGroupId_ = "";
    senderDeviceId_ = "";
    wireFormat_ = 0;
    handshakeId_ = "";
    relatedHandshakeId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.threadline.proto.threadline.crypto.v1.CryptoProto.internal_static_threadline_crypto_v1_MlsWireMessage_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.threadline.proto.threadline.crypto.v1.CryptoProto.internal_static_threadline_crypto_v1_MlsWireMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.threadline.proto.threadline.crypto.v1.CryptoProto.internal_static_threadline_crypto_v1_MlsWireMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.threadline.proto.threadline.crypto.v1.MlsWireMessage.class, com.threadline.proto.threadline.crypto.v1.MlsWireMessage.Builder.class);
  }

  public static final int MESSAGE_TYPE_FIELD_NUMBER = 1;
  private int messageType_ = 0;
  /**
   * <code>.threadline.crypto.v1.MlsWireMessageType message_type = 1 [json_name = "messageType"];</code>
   * @return The enum numeric value on the wire for messageType.
   */
  @java.lang.Override public int getMessageTypeValue() {
    return messageType_;
  }
  /**
   * <code>.threadline.crypto.v1.MlsWireMessageType message_type = 1 [json_name = "messageType"];</code>
   * @return The messageType.
   */
  @java.lang.Override public com.threadline.proto.threadline.crypto.v1.MlsWireMessageType getMessageType() {
    com.threadline.proto.threadline.crypto.v1.MlsWireMessageType result = com.threadline.proto.threadline.crypto.v1.MlsWireMessageType.forNumber(messageType_);
    return result == null ? com.threadline.proto.threadline.crypto.v1.MlsWireMessageType.UNRECOGNIZED : result;
  }

  public static final int MLS_DATA_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString mlsData_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Serialized MLS message. Commit and Proposal use PrivateMessage under
   * tl-mls-1. Welcome and GroupInfo are independent MLS objects. The bytes are
   * opaque to all server workloads.
   * </pre>
   *
   * <code>bytes mls_data = 2 [json_name = "mlsData"];</code>
   * @return The mlsData.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getMlsData() {
    return mlsData_;
  }

  public static final int EPOCH_FIELD_NUMBER = 3;
  private long epoch_ = 0L;
  /**
   * <pre>
   * Epoch this message builds on, replicated outside `mls_data` so the server
   * can order and reject stale Commits without parsing MLS.
   * </pre>
   *
   * <code>uint64 epoch = 3 [json_name = "epoch"];</code>
   * @return The epoch.
   */
  @java.lang.Override
  public long getEpoch() {
    return epoch_;
  }

  public static final int SUCCESSOR_EPOCH_FIELD_NUMBER = 4;
  private long successorEpoch_ = 0L;
  /**
   * <pre>
   * Epoch that results from applying this message. Set for COMMIT only.
   * </pre>
   *
   * <code>uint64 successor_epoch = 4 [json_name = "successorEpoch"];</code>
   * @return The successorEpoch.
   */
  @java.lang.Override
  public long getSuccessorEpoch() {
    return successorEpoch_;
  }

  public static final int AUTHORIZATION_ID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object authorizationId_ = "";
  /**
   * <pre>
   * Authorization consumed by a COMMIT. Empty for PROPOSAL and WELCOME.
   * </pre>
   *
   * <code>string authorization_id = 5 [json_name = "authorizationId"];</code>
   * @return The authorizationId.
   */
  @java.lang.Override
  public java.lang.String getAuthorizationId() {
    java.lang.Object ref = authorizationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      authorizationId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Authorization consumed by a COMMIT. Empty for PROPOSAL and WELCOME.
   * </pre>
   *
   * <code>string authorization_id = 5 [json_name = "authorizationId"];</code>
   * @return The bytes for authorizationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAuthorizationIdBytes() {
    java.lang.Object ref = authorizationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      authorizationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TARGET_DEVICE_IDS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList targetDeviceIds_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * Devices this message is addressed to. Required and non-empty for WELCOME,
   * which is delivered to joining Devices only. Empty means "all current
   * members" only for non-WELCOME message types.
   * </pre>
   *
   * <code>repeated string target_device_ids = 6 [json_name = "targetDeviceIds"];</code>
   * @return A list containing the targetDeviceIds.
   */
  public com.google.protobuf.ProtocolStringList
      getTargetDeviceIdsList() {
    return targetDeviceIds_;
  }
  /**
   * <pre>
   * Devices this message is addressed to. Required and non-empty for WELCOME,
   * which is delivered to joining Devices only. Empty means "all current
   * members" only for non-WELCOME message types.
   * </pre>
   *
   * <code>repeated string target_device_ids = 6 [json_name = "targetDeviceIds"];</code>
   * @return The count of targetDeviceIds.
   */
  public int getTargetDeviceIdsCount() {
    return targetDeviceIds_.size();
  }
  /**
   * <pre>
   * Devices this message is addressed to. Required and non-empty for WELCOME,
   * which is delivered to joining Devices only. Empty means "all current
   * members" only for non-WELCOME message types.
   * </pre>
   *
   * <code>repeated string target_device_ids = 6 [json_name = "targetDeviceIds"];</code>
   * @param index The index of the element to return.
   * @return The targetDeviceIds at the given index.
   */
  public java.lang.String getTargetDeviceIds(int index) {
    return targetDeviceIds_.get(index);
  }
  /**
   * <pre>
   * Devices this message is addressed to. Required and non-empty for WELCOME,
   * which is delivered to joining Devices only. Empty means "all current
   * members" only for non-WELCOME message types.
   * </pre>
   *
   * <code>repeated string target_device_ids = 6 [json_name = "targetDeviceIds"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the targetDeviceIds at the given index.
   */
  public com.google.protobuf.ByteString
      getTargetDeviceIdsBytes(int index) {
    return targetDeviceIds_.getByteString(index);
  }

  public static final int TENANT_ID_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <pre>
   * Required outer routing and ordering bindings. Servers validate these
   * fields but treat `mls_data` as an opaque byte string.
   * </pre>
   *
   * <code>string tenant_id = 7 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required outer routing and ordering bindings. Servers validate these
   * fields but treat `mls_data` as an opaque byte string.
   * </pre>
   *
   * <code>string tenant_id = 7 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int E2EE_GROUP_ID_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object e2EeGroupId_ = "";
  /**
   * <code>string e2ee_group_id = 8 [json_name = "e2eeGroupId"];</code>
   * @return The e2eeGroupId.
   */
  @java.lang.Override
  public java.lang.String getE2EeGroupId() {
    java.lang.Object ref = e2EeGroupId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      e2EeGroupId_ = s;
      return s;
    }
  }
  /**
   * <code>string e2ee_group_id = 8 [json_name = "e2eeGroupId"];</code>
   * @return The bytes for e2eeGroupId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getE2EeGroupIdBytes() {
    java.lang.Object ref = e2EeGroupId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      e2EeGroupId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHANGE_SEQ_FIELD_NUMBER = 9;
  private long changeSeq_ = 0L;
  /**
   * <code>uint64 change_seq = 9 [json_name = "changeSeq"];</code>
   * @return The changeSeq.
   */
  @java.lang.Override
  public long getChangeSeq() {
    return changeSeq_;
  }

  public static final int SENDER_DEVICE_ID_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object senderDeviceId_ = "";
  /**
   * <code>string sender_device_id = 10 [json_name = "senderDeviceId"];</code>
   * @return The senderDeviceId.
   */
  @java.lang.Override
  public java.lang.String getSenderDeviceId() {
    java.lang.Object ref = senderDeviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senderDeviceId_ = s;
      return s;
    }
  }
  /**
   * <code>string sender_device_id = 10 [json_name = "senderDeviceId"];</code>
   * @return The bytes for senderDeviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderDeviceIdBytes() {
    java.lang.Object ref = senderDeviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderDeviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WIRE_FORMAT_FIELD_NUMBER = 11;
  private int wireFormat_ = 0;
  /**
   * <code>.threadline.crypto.v1.MlsWireFormat wire_format = 11 [json_name = "wireFormat"];</code>
   * @return The enum numeric value on the wire for wireFormat.
   */
  @java.lang.Override public int getWireFormatValue() {
    return wireFormat_;
  }
  /**
   * <code>.threadline.crypto.v1.MlsWireFormat wire_format = 11 [json_name = "wireFormat"];</code>
   * @return The wireFormat.
   */
  @java.lang.Override public com.threadline.proto.threadline.crypto.v1.MlsWireFormat getWireFormat() {
    com.threadline.proto.threadline.crypto.v1.MlsWireFormat result = com.threadline.proto.threadline.crypto.v1.MlsWireFormat.forNumber(wireFormat_);
    return result == null ? com.threadline.proto.threadline.crypto.v1.MlsWireFormat.UNRECOGNIZED : result;
  }

  public static final int HANDSHAKE_ID_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object handshakeId_ = "";
  /**
   * <pre>
   * Sender-chosen replay identity. The same ID with different binding fields
   * or bytes is rejected; an exact duplicate is idempotent.
   * </pre>
   *
   * <code>string handshake_id = 12 [json_name = "handshakeId"];</code>
   * @return The handshakeId.
   */
  @java.lang.Override
  public java.lang.String getHandshakeId() {
    java.lang.Object ref = handshakeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      handshakeId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Sender-chosen replay identity. The same ID with different binding fields
   * or bytes is rejected; an exact duplicate is idempotent.
   * </pre>
   *
   * <code>string handshake_id = 12 [json_name = "handshakeId"];</code>
   * @return The bytes for handshakeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHandshakeIdBytes() {
    java.lang.Object ref = handshakeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      handshakeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RELATED_HANDSHAKE_ID_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object relatedHandshakeId_ = "";
  /**
   * <pre>
   * For Welcome, the accepted Commit handshake that created the joining Epoch.
   * Empty for Commit/Proposal and optional for independently refreshed
   * GroupInfo. This correlation does not require parsing the MLS bytes.
   * </pre>
   *
   * <code>string related_handshake_id = 13 [json_name = "relatedHandshakeId"];</code>
   * @return The relatedHandshakeId.
   */
  @java.lang.Override
  public java.lang.String getRelatedHandshakeId() {
    java.lang.Object ref = relatedHandshakeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      relatedHandshakeId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * For Welcome, the accepted Commit handshake that created the joining Epoch.
   * Empty for Commit/Proposal and optional for independently refreshed
   * GroupInfo. This correlation does not require parsing the MLS bytes.
   * </pre>
   *
   * <code>string related_handshake_id = 13 [json_name = "relatedHandshakeId"];</code>
   * @return The bytes for relatedHandshakeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRelatedHandshakeIdBytes() {
    java.lang.Object ref = relatedHandshakeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      relatedHandshakeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageType_ != com.threadline.proto.threadline.crypto.v1.MlsWireMessageType.MLS_WIRE_MESSAGE_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, messageType_);
    }
    if (!mlsData_.isEmpty()) {
      output.writeBytes(2, mlsData_);
    }
    if (epoch_ != 0L) {
      output.writeUInt64(3, epoch_);
    }
    if (successorEpoch_ != 0L) {
      output.writeUInt64(4, successorEpoch_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(authorizationId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, authorizationId_);
    }
    for (int i = 0; i < targetDeviceIds_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, targetDeviceIds_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(e2EeGroupId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, e2EeGroupId_);
    }
    if (changeSeq_ != 0L) {
      output.writeUInt64(9, changeSeq_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(senderDeviceId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, senderDeviceId_);
    }
    if (wireFormat_ != com.threadline.proto.threadline.crypto.v1.MlsWireFormat.MLS_WIRE_FORMAT_UNSPECIFIED.getNumber()) {
      output.writeEnum(11, wireFormat_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(handshakeId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 12, handshakeId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(relatedHandshakeId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 13, relatedHandshakeId_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (messageType_ != com.threadline.proto.threadline.crypto.v1.MlsWireMessageType.MLS_WIRE_MESSAGE_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, messageType_);
    }
    if (!mlsData_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, mlsData_);
    }
    if (epoch_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, epoch_);
    }
    if (successorEpoch_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, successorEpoch_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(authorizationId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, authorizationId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < targetDeviceIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(targetDeviceIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTargetDeviceIdsList().size();
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(e2EeGroupId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, e2EeGroupId_);
    }
    if (changeSeq_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, changeSeq_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(senderDeviceId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, senderDeviceId_);
    }
    if (wireFormat_ != com.threadline.proto.threadline.crypto.v1.MlsWireFormat.MLS_WIRE_FORMAT_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(11, wireFormat_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(handshakeId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(12, handshakeId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(relatedHandshakeId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(13, relatedHandshakeId_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.threadline.proto.threadline.crypto.v1.MlsWireMessage)) {
      return super.equals(obj);
    }
    com.threadline.proto.threadline.crypto.v1.MlsWireMessage other = (com.threadline.proto.threadline.crypto.v1.MlsWireMessage) obj;

    if (messageType_ != other.messageType_) return false;
    if (!getMlsData()
        .equals(other.getMlsData())) return false;
    if (getEpoch()
        != other.getEpoch()) return false;
    if (getSuccessorEpoch()
        != other.getSuccessorEpoch()) return false;
    if (!getAuthorizationId()
        .equals(other.getAuthorizationId())) return false;
    if (!getTargetDeviceIdsList()
        .equals(other.getTargetDeviceIdsList())) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (!getE2EeGroupId()
        .equals(other.getE2EeGroupId())) return false;
    if (getChangeSeq()
        != other.getChangeSeq()) return false;
    if (!getSenderDeviceId()
        .equals(other.getSenderDeviceId())) return false;
    if (wireFormat_ != other.wireFormat_) return false;
    if (!getHandshakeId()
        .equals(other.getHandshakeId())) return false;
    if (!getRelatedHandshakeId()
        .equals(other.getRelatedHandshakeId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + messageType_;
    hash = (37 * hash) + MLS_DATA_FIELD_NUMBER;
    hash = (53 * hash) + getMlsData().hashCode();
    hash = (37 * hash) + EPOCH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEpoch());
    hash = (37 * hash) + SUCCESSOR_EPOCH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSuccessorEpoch());
    hash = (37 * hash) + AUTHORIZATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAuthorizationId().hashCode();
    if (getTargetDeviceIdsCount() > 0) {
      hash = (37 * hash) + TARGET_DEVICE_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getTargetDeviceIdsList().hashCode();
    }
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (37 * hash) + E2EE_GROUP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getE2EeGroupId().hashCode();
    hash = (37 * hash) + CHANGE_SEQ_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getChangeSeq());
    hash = (37 * hash) + SENDER_DEVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSenderDeviceId().hashCode();
    hash = (37 * hash) + WIRE_FORMAT_FIELD_NUMBER;
    hash = (53 * hash) + wireFormat_;
    hash = (37 * hash) + HANDSHAKE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getHandshakeId().hashCode();
    hash = (37 * hash) + RELATED_HANDSHAKE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRelatedHandshakeId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.threadline.proto.threadline.crypto.v1.MlsWireMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.crypto.v1.MlsWireMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.crypto.v1.MlsWireMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.crypto.v1.MlsWireMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.crypto.v1.MlsWireMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.crypto.v1.MlsWireMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.crypto.v1.MlsWireMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.threadline.proto.threadline.crypto.v1.MlsWireMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.threadline.proto.threadline.crypto.v1.MlsWireMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.threadline.proto.threadline.crypto.v1.MlsWireMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.threadline.proto.threadline.crypto.v1.MlsWireMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.threadline.proto.threadline.crypto.v1.MlsWireMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.threadline.proto.threadline.crypto.v1.MlsWireMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * MlsWireMessage transports MLS handshake material.
   *
   * The server accepts or orders these using only the fields below plus Device
   * authorization and size limits. Cryptographic validity is a client
   * responsibility: a malicious or faulty server can still delay, drop, replay or
   * fork delivery, and clients detect that through MLS transcript state, strict
   * Epoch continuity and gap repair. E2EE does not promise denial-of-service
   * resistance.
   * </pre>
   *
   * Protobuf type {@code threadline.crypto.v1.MlsWireMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:threadline.crypto.v1.MlsWireMessage)
      com.threadline.proto.threadline.crypto.v1.MlsWireMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.threadline.proto.threadline.crypto.v1.CryptoProto.internal_static_threadline_crypto_v1_MlsWireMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.threadline.proto.threadline.crypto.v1.CryptoProto.internal_static_threadline_crypto_v1_MlsWireMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.threadline.proto.threadline.crypto.v1.MlsWireMessage.class, com.threadline.proto.threadline.crypto.v1.MlsWireMessage.Builder.class);
    }

    // Construct using com.threadline.proto.threadline.crypto.v1.MlsWireMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      messageType_ = 0;
      mlsData_ = com.google.protobuf.ByteString.EMPTY;
      epoch_ = 0L;
      successorEpoch_ = 0L;
      authorizationId_ = "";
      targetDeviceIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      tenantId_ = "";
      e2EeGroupId_ = "";
      changeSeq_ = 0L;
      senderDeviceId_ = "";
      wireFormat_ = 0;
      handshakeId_ = "";
      relatedHandshakeId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.threadline.proto.threadline.crypto.v1.CryptoProto.internal_static_threadline_crypto_v1_MlsWireMessage_descriptor;
    }

    @java.lang.Override
    public com.threadline.proto.threadline.crypto.v1.MlsWireMessage getDefaultInstanceForType() {
      return com.threadline.proto.threadline.crypto.v1.MlsWireMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.threadline.proto.threadline.crypto.v1.MlsWireMessage build() {
      com.threadline.proto.threadline.crypto.v1.MlsWireMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.threadline.proto.threadline.crypto.v1.MlsWireMessage buildPartial() {
      com.threadline.proto.threadline.crypto.v1.MlsWireMessage result = new com.threadline.proto.threadline.crypto.v1.MlsWireMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.threadline.proto.threadline.crypto.v1.MlsWireMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.messageType_ = messageType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.mlsData_ = mlsData_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.epoch_ = epoch_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.successorEpoch_ = successorEpoch_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.authorizationId_ = authorizationId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        targetDeviceIds_.makeImmutable();
        result.targetDeviceIds_ = targetDeviceIds_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.tenantId_ = tenantId_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.e2EeGroupId_ = e2EeGroupId_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.changeSeq_ = changeSeq_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.senderDeviceId_ = senderDeviceId_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.wireFormat_ = wireFormat_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.handshakeId_ = handshakeId_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.relatedHandshakeId_ = relatedHandshakeId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.threadline.proto.threadline.crypto.v1.MlsWireMessage) {
        return mergeFrom((com.threadline.proto.threadline.crypto.v1.MlsWireMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.threadline.proto.threadline.crypto.v1.MlsWireMessage other) {
      if (other == com.threadline.proto.threadline.crypto.v1.MlsWireMessage.getDefaultInstance()) return this;
      if (other.messageType_ != 0) {
        setMessageTypeValue(other.getMessageTypeValue());
      }
      if (!other.getMlsData().isEmpty()) {
        setMlsData(other.getMlsData());
      }
      if (other.getEpoch() != 0L) {
        setEpoch(other.getEpoch());
      }
      if (other.getSuccessorEpoch() != 0L) {
        setSuccessorEpoch(other.getSuccessorEpoch());
      }
      if (!other.getAuthorizationId().isEmpty()) {
        authorizationId_ = other.authorizationId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.targetDeviceIds_.isEmpty()) {
        if (targetDeviceIds_.isEmpty()) {
          targetDeviceIds_ = other.targetDeviceIds_;
          bitField0_ |= 0x00000020;
        } else {
          ensureTargetDeviceIdsIsMutable();
          targetDeviceIds_.addAll(other.targetDeviceIds_);
        }
        onChanged();
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getE2EeGroupId().isEmpty()) {
        e2EeGroupId_ = other.e2EeGroupId_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.getChangeSeq() != 0L) {
        setChangeSeq(other.getChangeSeq());
      }
      if (!other.getSenderDeviceId().isEmpty()) {
        senderDeviceId_ = other.senderDeviceId_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (other.wireFormat_ != 0) {
        setWireFormatValue(other.getWireFormatValue());
      }
      if (!other.getHandshakeId().isEmpty()) {
        handshakeId_ = other.handshakeId_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      if (!other.getRelatedHandshakeId().isEmpty()) {
        relatedHandshakeId_ = other.relatedHandshakeId_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              messageType_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              mlsData_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              epoch_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              successorEpoch_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              authorizationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              ensureTargetDeviceIdsIsMutable();
              targetDeviceIds_.add(input.readStringRequireUtf8());
              break;
            } // case 50
            case 58: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              e2EeGroupId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 72: {
              changeSeq_ = input.readUInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 82: {
              senderDeviceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 88: {
              wireFormat_ = input.readEnum();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 98: {
              handshakeId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              relatedHandshakeId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int messageType_ = 0;
    /**
     * <code>.threadline.crypto.v1.MlsWireMessageType message_type = 1 [json_name = "messageType"];</code>
     * @return The enum numeric value on the wire for messageType.
     */
    @java.lang.Override public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <code>.threadline.crypto.v1.MlsWireMessageType message_type = 1 [json_name = "messageType"];</code>
     * @param value The enum numeric value on the wire for messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageTypeValue(int value) {
      messageType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.threadline.crypto.v1.MlsWireMessageType message_type = 1 [json_name = "messageType"];</code>
     * @return The messageType.
     */
    @java.lang.Override
    public com.threadline.proto.threadline.crypto.v1.MlsWireMessageType getMessageType() {
      com.threadline.proto.threadline.crypto.v1.MlsWireMessageType result = com.threadline.proto.threadline.crypto.v1.MlsWireMessageType.forNumber(messageType_);
      return result == null ? com.threadline.proto.threadline.crypto.v1.MlsWireMessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.threadline.crypto.v1.MlsWireMessageType message_type = 1 [json_name = "messageType"];</code>
     * @param value The messageType to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setMessageType(com.threadline.proto.threadline.crypto.v1.MlsWireMessageType value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000001;
      messageType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.threadline.crypto.v1.MlsWireMessageType message_type = 1 [json_name = "messageType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      messageType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString mlsData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Serialized MLS message. Commit and Proposal use PrivateMessage under
     * tl-mls-1. Welcome and GroupInfo are independent MLS objects. The bytes are
     * opaque to all server workloads.
     * </pre>
     *
     * <code>bytes mls_data = 2 [json_name = "mlsData"];</code>
     * @return The mlsData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMlsData() {
      return mlsData_;
    }
    /**
     * <pre>
     * Serialized MLS message. Commit and Proposal use PrivateMessage under
     * tl-mls-1. Welcome and GroupInfo are independent MLS objects. The bytes are
     * opaque to all server workloads.
     * </pre>
     *
     * <code>bytes mls_data = 2 [json_name = "mlsData"];</code>
     * @param value The mlsData to set.
     * @return This builder for chaining.
     */
    public Builder setMlsData(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      mlsData_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Serialized MLS message. Commit and Proposal use PrivateMessage under
     * tl-mls-1. Welcome and GroupInfo are independent MLS objects. The bytes are
     * opaque to all server workloads.
     * </pre>
     *
     * <code>bytes mls_data = 2 [json_name = "mlsData"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMlsData() {
      bitField0_ = (bitField0_ & ~0x00000002);
      mlsData_ = getDefaultInstance().getMlsData();
      onChanged();
      return this;
    }

    private long epoch_ ;
    /**
     * <pre>
     * Epoch this message builds on, replicated outside `mls_data` so the server
     * can order and reject stale Commits without parsing MLS.
     * </pre>
     *
     * <code>uint64 epoch = 3 [json_name = "epoch"];</code>
     * @return The epoch.
     */
    @java.lang.Override
    public long getEpoch() {
      return epoch_;
    }
    /**
     * <pre>
     * Epoch this message builds on, replicated outside `mls_data` so the server
     * can order and reject stale Commits without parsing MLS.
     * </pre>
     *
     * <code>uint64 epoch = 3 [json_name = "epoch"];</code>
     * @param value The epoch to set.
     * @return This builder for chaining.
     */
    public Builder setEpoch(long value) {

      epoch_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Epoch this message builds on, replicated outside `mls_data` so the server
     * can order and reject stale Commits without parsing MLS.
     * </pre>
     *
     * <code>uint64 epoch = 3 [json_name = "epoch"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEpoch() {
      bitField0_ = (bitField0_ & ~0x00000004);
      epoch_ = 0L;
      onChanged();
      return this;
    }

    private long successorEpoch_ ;
    /**
     * <pre>
     * Epoch that results from applying this message. Set for COMMIT only.
     * </pre>
     *
     * <code>uint64 successor_epoch = 4 [json_name = "successorEpoch"];</code>
     * @return The successorEpoch.
     */
    @java.lang.Override
    public long getSuccessorEpoch() {
      return successorEpoch_;
    }
    /**
     * <pre>
     * Epoch that results from applying this message. Set for COMMIT only.
     * </pre>
     *
     * <code>uint64 successor_epoch = 4 [json_name = "successorEpoch"];</code>
     * @param value The successorEpoch to set.
     * @return This builder for chaining.
     */
    public Builder setSuccessorEpoch(long value) {

      successorEpoch_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Epoch that results from applying this message. Set for COMMIT only.
     * </pre>
     *
     * <code>uint64 successor_epoch = 4 [json_name = "successorEpoch"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccessorEpoch() {
      bitField0_ = (bitField0_ & ~0x00000008);
      successorEpoch_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object authorizationId_ = "";
    /**
     * <pre>
     * Authorization consumed by a COMMIT. Empty for PROPOSAL and WELCOME.
     * </pre>
     *
     * <code>string authorization_id = 5 [json_name = "authorizationId"];</code>
     * @return The authorizationId.
     */
    public java.lang.String getAuthorizationId() {
      java.lang.Object ref = authorizationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authorizationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Authorization consumed by a COMMIT. Empty for PROPOSAL and WELCOME.
     * </pre>
     *
     * <code>string authorization_id = 5 [json_name = "authorizationId"];</code>
     * @return The bytes for authorizationId.
     */
    public com.google.protobuf.ByteString
        getAuthorizationIdBytes() {
      java.lang.Object ref = authorizationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authorizationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Authorization consumed by a COMMIT. Empty for PROPOSAL and WELCOME.
     * </pre>
     *
     * <code>string authorization_id = 5 [json_name = "authorizationId"];</code>
     * @param value The authorizationId to set.
     * @return This builder for chaining.
     */
    public Builder setAuthorizationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      authorizationId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Authorization consumed by a COMMIT. Empty for PROPOSAL and WELCOME.
     * </pre>
     *
     * <code>string authorization_id = 5 [json_name = "authorizationId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthorizationId() {
      authorizationId_ = getDefaultInstance().getAuthorizationId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Authorization consumed by a COMMIT. Empty for PROPOSAL and WELCOME.
     * </pre>
     *
     * <code>string authorization_id = 5 [json_name = "authorizationId"];</code>
     * @param value The bytes for authorizationId to set.
     * @return This builder for chaining.
     */
    public Builder setAuthorizationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      authorizationId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList targetDeviceIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTargetDeviceIdsIsMutable() {
      if (!targetDeviceIds_.isModifiable()) {
        targetDeviceIds_ = new com.google.protobuf.LazyStringArrayList(targetDeviceIds_);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <pre>
     * Devices this message is addressed to. Required and non-empty for WELCOME,
     * which is delivered to joining Devices only. Empty means "all current
     * members" only for non-WELCOME message types.
     * </pre>
     *
     * <code>repeated string target_device_ids = 6 [json_name = "targetDeviceIds"];</code>
     * @return A list containing the targetDeviceIds.
     */
    public com.google.protobuf.ProtocolStringList
        getTargetDeviceIdsList() {
      targetDeviceIds_.makeImmutable();
      return targetDeviceIds_;
    }
    /**
     * <pre>
     * Devices this message is addressed to. Required and non-empty for WELCOME,
     * which is delivered to joining Devices only. Empty means "all current
     * members" only for non-WELCOME message types.
     * </pre>
     *
     * <code>repeated string target_device_ids = 6 [json_name = "targetDeviceIds"];</code>
     * @return The count of targetDeviceIds.
     */
    public int getTargetDeviceIdsCount() {
      return targetDeviceIds_.size();
    }
    /**
     * <pre>
     * Devices this message is addressed to. Required and non-empty for WELCOME,
     * which is delivered to joining Devices only. Empty means "all current
     * members" only for non-WELCOME message types.
     * </pre>
     *
     * <code>repeated string target_device_ids = 6 [json_name = "targetDeviceIds"];</code>
     * @param index The index of the element to return.
     * @return The targetDeviceIds at the given index.
     */
    public java.lang.String getTargetDeviceIds(int index) {
      return targetDeviceIds_.get(index);
    }
    /**
     * <pre>
     * Devices this message is addressed to. Required and non-empty for WELCOME,
     * which is delivered to joining Devices only. Empty means "all current
     * members" only for non-WELCOME message types.
     * </pre>
     *
     * <code>repeated string target_device_ids = 6 [json_name = "targetDeviceIds"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the targetDeviceIds at the given index.
     */
    public com.google.protobuf.ByteString
        getTargetDeviceIdsBytes(int index) {
      return targetDeviceIds_.getByteString(index);
    }
    /**
     * <pre>
     * Devices this message is addressed to. Required and non-empty for WELCOME,
     * which is delivered to joining Devices only. Empty means "all current
     * members" only for non-WELCOME message types.
     * </pre>
     *
     * <code>repeated string target_device_ids = 6 [json_name = "targetDeviceIds"];</code>
     * @param index The index to set the value at.
     * @param value The targetDeviceIds to set.
     * @return This builder for chaining.
     */
    public Builder setTargetDeviceIds(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTargetDeviceIdsIsMutable();
      targetDeviceIds_.set(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Devices this message is addressed to. Required and non-empty for WELCOME,
     * which is delivered to joining Devices only. Empty means "all current
     * members" only for non-WELCOME message types.
     * </pre>
     *
     * <code>repeated string target_device_ids = 6 [json_name = "targetDeviceIds"];</code>
     * @param value The targetDeviceIds to add.
     * @return This builder for chaining.
     */
    public Builder addTargetDeviceIds(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTargetDeviceIdsIsMutable();
      targetDeviceIds_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Devices this message is addressed to. Required and non-empty for WELCOME,
     * which is delivered to joining Devices only. Empty means "all current
     * members" only for non-WELCOME message types.
     * </pre>
     *
     * <code>repeated string target_device_ids = 6 [json_name = "targetDeviceIds"];</code>
     * @param values The targetDeviceIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllTargetDeviceIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureTargetDeviceIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, targetDeviceIds_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Devices this message is addressed to. Required and non-empty for WELCOME,
     * which is delivered to joining Devices only. Empty means "all current
     * members" only for non-WELCOME message types.
     * </pre>
     *
     * <code>repeated string target_device_ids = 6 [json_name = "targetDeviceIds"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetDeviceIds() {
      targetDeviceIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Devices this message is addressed to. Required and non-empty for WELCOME,
     * which is delivered to joining Devices only. Empty means "all current
     * members" only for non-WELCOME message types.
     * </pre>
     *
     * <code>repeated string target_device_ids = 6 [json_name = "targetDeviceIds"];</code>
     * @param value The bytes of the targetDeviceIds to add.
     * @return This builder for chaining.
     */
    public Builder addTargetDeviceIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureTargetDeviceIdsIsMutable();
      targetDeviceIds_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <pre>
     * Required outer routing and ordering bindings. Servers validate these
     * fields but treat `mls_data` as an opaque byte string.
     * </pre>
     *
     * <code>string tenant_id = 7 [json_name = "tenantId"];</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required outer routing and ordering bindings. Servers validate these
     * fields but treat `mls_data` as an opaque byte string.
     * </pre>
     *
     * <code>string tenant_id = 7 [json_name = "tenantId"];</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required outer routing and ordering bindings. Servers validate these
     * fields but treat `mls_data` as an opaque byte string.
     * </pre>
     *
     * <code>string tenant_id = 7 [json_name = "tenantId"];</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required outer routing and ordering bindings. Servers validate these
     * fields but treat `mls_data` as an opaque byte string.
     * </pre>
     *
     * <code>string tenant_id = 7 [json_name = "tenantId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required outer routing and ordering bindings. Servers validate these
     * fields but treat `mls_data` as an opaque byte string.
     * </pre>
     *
     * <code>string tenant_id = 7 [json_name = "tenantId"];</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object e2EeGroupId_ = "";
    /**
     * <code>string e2ee_group_id = 8 [json_name = "e2eeGroupId"];</code>
     * @return The e2eeGroupId.
     */
    public java.lang.String getE2EeGroupId() {
      java.lang.Object ref = e2EeGroupId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        e2EeGroupId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string e2ee_group_id = 8 [json_name = "e2eeGroupId"];</code>
     * @return The bytes for e2eeGroupId.
     */
    public com.google.protobuf.ByteString
        getE2EeGroupIdBytes() {
      java.lang.Object ref = e2EeGroupId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        e2EeGroupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string e2ee_group_id = 8 [json_name = "e2eeGroupId"];</code>
     * @param value The e2eeGroupId to set.
     * @return This builder for chaining.
     */
    public Builder setE2EeGroupId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      e2EeGroupId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string e2ee_group_id = 8 [json_name = "e2eeGroupId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearE2EeGroupId() {
      e2EeGroupId_ = getDefaultInstance().getE2EeGroupId();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string e2ee_group_id = 8 [json_name = "e2eeGroupId"];</code>
     * @param value The bytes for e2eeGroupId to set.
     * @return This builder for chaining.
     */
    public Builder setE2EeGroupIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      e2EeGroupId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private long changeSeq_ ;
    /**
     * <code>uint64 change_seq = 9 [json_name = "changeSeq"];</code>
     * @return The changeSeq.
     */
    @java.lang.Override
    public long getChangeSeq() {
      return changeSeq_;
    }
    /**
     * <code>uint64 change_seq = 9 [json_name = "changeSeq"];</code>
     * @param value The changeSeq to set.
     * @return This builder for chaining.
     */
    public Builder setChangeSeq(long value) {

      changeSeq_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 change_seq = 9 [json_name = "changeSeq"];</code>
     * @return This builder for chaining.
     */
    public Builder clearChangeSeq() {
      bitField0_ = (bitField0_ & ~0x00000100);
      changeSeq_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object senderDeviceId_ = "";
    /**
     * <code>string sender_device_id = 10 [json_name = "senderDeviceId"];</code>
     * @return The senderDeviceId.
     */
    public java.lang.String getSenderDeviceId() {
      java.lang.Object ref = senderDeviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderDeviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sender_device_id = 10 [json_name = "senderDeviceId"];</code>
     * @return The bytes for senderDeviceId.
     */
    public com.google.protobuf.ByteString
        getSenderDeviceIdBytes() {
      java.lang.Object ref = senderDeviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderDeviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sender_device_id = 10 [json_name = "senderDeviceId"];</code>
     * @param value The senderDeviceId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderDeviceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      senderDeviceId_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string sender_device_id = 10 [json_name = "senderDeviceId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderDeviceId() {
      senderDeviceId_ = getDefaultInstance().getSenderDeviceId();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string sender_device_id = 10 [json_name = "senderDeviceId"];</code>
     * @param value The bytes for senderDeviceId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      senderDeviceId_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private int wireFormat_ = 0;
    /**
     * <code>.threadline.crypto.v1.MlsWireFormat wire_format = 11 [json_name = "wireFormat"];</code>
     * @return The enum numeric value on the wire for wireFormat.
     */
    @java.lang.Override public int getWireFormatValue() {
      return wireFormat_;
    }
    /**
     * <code>.threadline.crypto.v1.MlsWireFormat wire_format = 11 [json_name = "wireFormat"];</code>
     * @param value The enum numeric value on the wire for wireFormat to set.
     * @return This builder for chaining.
     */
    public Builder setWireFormatValue(int value) {
      wireFormat_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>.threadline.crypto.v1.MlsWireFormat wire_format = 11 [json_name = "wireFormat"];</code>
     * @return The wireFormat.
     */
    @java.lang.Override
    public com.threadline.proto.threadline.crypto.v1.MlsWireFormat getWireFormat() {
      com.threadline.proto.threadline.crypto.v1.MlsWireFormat result = com.threadline.proto.threadline.crypto.v1.MlsWireFormat.forNumber(wireFormat_);
      return result == null ? com.threadline.proto.threadline.crypto.v1.MlsWireFormat.UNRECOGNIZED : result;
    }
    /**
     * <code>.threadline.crypto.v1.MlsWireFormat wire_format = 11 [json_name = "wireFormat"];</code>
     * @param value The wireFormat to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setWireFormat(com.threadline.proto.threadline.crypto.v1.MlsWireFormat value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000400;
      wireFormat_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.threadline.crypto.v1.MlsWireFormat wire_format = 11 [json_name = "wireFormat"];</code>
     * @return This builder for chaining.
     */
    public Builder clearWireFormat() {
      bitField0_ = (bitField0_ & ~0x00000400);
      wireFormat_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object handshakeId_ = "";
    /**
     * <pre>
     * Sender-chosen replay identity. The same ID with different binding fields
     * or bytes is rejected; an exact duplicate is idempotent.
     * </pre>
     *
     * <code>string handshake_id = 12 [json_name = "handshakeId"];</code>
     * @return The handshakeId.
     */
    public java.lang.String getHandshakeId() {
      java.lang.Object ref = handshakeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        handshakeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Sender-chosen replay identity. The same ID with different binding fields
     * or bytes is rejected; an exact duplicate is idempotent.
     * </pre>
     *
     * <code>string handshake_id = 12 [json_name = "handshakeId"];</code>
     * @return The bytes for handshakeId.
     */
    public com.google.protobuf.ByteString
        getHandshakeIdBytes() {
      java.lang.Object ref = handshakeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        handshakeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Sender-chosen replay identity. The same ID with different binding fields
     * or bytes is rejected; an exact duplicate is idempotent.
     * </pre>
     *
     * <code>string handshake_id = 12 [json_name = "handshakeId"];</code>
     * @param value The handshakeId to set.
     * @return This builder for chaining.
     */
    public Builder setHandshakeId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      handshakeId_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Sender-chosen replay identity. The same ID with different binding fields
     * or bytes is rejected; an exact duplicate is idempotent.
     * </pre>
     *
     * <code>string handshake_id = 12 [json_name = "handshakeId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearHandshakeId() {
      handshakeId_ = getDefaultInstance().getHandshakeId();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Sender-chosen replay identity. The same ID with different binding fields
     * or bytes is rejected; an exact duplicate is idempotent.
     * </pre>
     *
     * <code>string handshake_id = 12 [json_name = "handshakeId"];</code>
     * @param value The bytes for handshakeId to set.
     * @return This builder for chaining.
     */
    public Builder setHandshakeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      handshakeId_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private java.lang.Object relatedHandshakeId_ = "";
    /**
     * <pre>
     * For Welcome, the accepted Commit handshake that created the joining Epoch.
     * Empty for Commit/Proposal and optional for independently refreshed
     * GroupInfo. This correlation does not require parsing the MLS bytes.
     * </pre>
     *
     * <code>string related_handshake_id = 13 [json_name = "relatedHandshakeId"];</code>
     * @return The relatedHandshakeId.
     */
    public java.lang.String getRelatedHandshakeId() {
      java.lang.Object ref = relatedHandshakeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        relatedHandshakeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * For Welcome, the accepted Commit handshake that created the joining Epoch.
     * Empty for Commit/Proposal and optional for independently refreshed
     * GroupInfo. This correlation does not require parsing the MLS bytes.
     * </pre>
     *
     * <code>string related_handshake_id = 13 [json_name = "relatedHandshakeId"];</code>
     * @return The bytes for relatedHandshakeId.
     */
    public com.google.protobuf.ByteString
        getRelatedHandshakeIdBytes() {
      java.lang.Object ref = relatedHandshakeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relatedHandshakeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * For Welcome, the accepted Commit handshake that created the joining Epoch.
     * Empty for Commit/Proposal and optional for independently refreshed
     * GroupInfo. This correlation does not require parsing the MLS bytes.
     * </pre>
     *
     * <code>string related_handshake_id = 13 [json_name = "relatedHandshakeId"];</code>
     * @param value The relatedHandshakeId to set.
     * @return This builder for chaining.
     */
    public Builder setRelatedHandshakeId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      relatedHandshakeId_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * For Welcome, the accepted Commit handshake that created the joining Epoch.
     * Empty for Commit/Proposal and optional for independently refreshed
     * GroupInfo. This correlation does not require parsing the MLS bytes.
     * </pre>
     *
     * <code>string related_handshake_id = 13 [json_name = "relatedHandshakeId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRelatedHandshakeId() {
      relatedHandshakeId_ = getDefaultInstance().getRelatedHandshakeId();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * For Welcome, the accepted Commit handshake that created the joining Epoch.
     * Empty for Commit/Proposal and optional for independently refreshed
     * GroupInfo. This correlation does not require parsing the MLS bytes.
     * </pre>
     *
     * <code>string related_handshake_id = 13 [json_name = "relatedHandshakeId"];</code>
     * @param value The bytes for relatedHandshakeId to set.
     * @return This builder for chaining.
     */
    public Builder setRelatedHandshakeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      relatedHandshakeId_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:threadline.crypto.v1.MlsWireMessage)
  }

  // @@protoc_insertion_point(class_scope:threadline.crypto.v1.MlsWireMessage)
  private static final com.threadline.proto.threadline.crypto.v1.MlsWireMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.threadline.proto.threadline.crypto.v1.MlsWireMessage();
  }

  public static com.threadline.proto.threadline.crypto.v1.MlsWireMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MlsWireMessage>
      PARSER = new com.google.protobuf.AbstractParser<MlsWireMessage>() {
    @java.lang.Override
    public MlsWireMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MlsWireMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MlsWireMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.threadline.proto.threadline.crypto.v1.MlsWireMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

