// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/crypto/v1/key_service.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.crypto.v1;

@com.google.protobuf.Generated
public interface RecoveryEvidenceItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threadline.crypto.v1.RecoveryEvidenceItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Exact persisted sender envelope, including the wrapped material that stays
   * opaque to Core and Recovery Control and is passed only to the KMS/HSM.
   * </pre>
   *
   * <code>.threadline.crypto.v1.RecoveryEnvelope envelope = 1 [json_name = "envelope"];</code>
   * @return Whether the envelope field is set.
   */
  boolean hasEnvelope();
  /**
   * <pre>
   * Exact persisted sender envelope, including the wrapped material that stays
   * opaque to Core and Recovery Control and is passed only to the KMS/HSM.
   * </pre>
   *
   * <code>.threadline.crypto.v1.RecoveryEnvelope envelope = 1 [json_name = "envelope"];</code>
   * @return The envelope.
   */
  com.threadline.proto.threadline.crypto.v1.RecoveryEnvelope getEnvelope();
  /**
   * <pre>
   * Exact persisted sender envelope, including the wrapped material that stays
   * opaque to Core and Recovery Control and is passed only to the KMS/HSM.
   * </pre>
   *
   * <code>.threadline.crypto.v1.RecoveryEnvelope envelope = 1 [json_name = "envelope"];</code>
   */
  com.threadline.proto.threadline.crypto.v1.RecoveryEnvelopeOrBuilder getEnvelopeOrBuilder();

  /**
   * <pre>
   * Core-produced proof for this exact envelope. The transcript hash in the
   * attestation must match `envelope` one-for-one; missing or duplicate items
   * fail closed.
   * </pre>
   *
   * <code>.threadline.crypto.v1.RecoveryScopeCommitAttestation attestation = 2 [json_name = "attestation"];</code>
   * @return Whether the attestation field is set.
   */
  boolean hasAttestation();
  /**
   * <pre>
   * Core-produced proof for this exact envelope. The transcript hash in the
   * attestation must match `envelope` one-for-one; missing or duplicate items
   * fail closed.
   * </pre>
   *
   * <code>.threadline.crypto.v1.RecoveryScopeCommitAttestation attestation = 2 [json_name = "attestation"];</code>
   * @return The attestation.
   */
  com.threadline.proto.threadline.crypto.v1.RecoveryScopeCommitAttestation getAttestation();
  /**
   * <pre>
   * Core-produced proof for this exact envelope. The transcript hash in the
   * attestation must match `envelope` one-for-one; missing or duplicate items
   * fail closed.
   * </pre>
   *
   * <code>.threadline.crypto.v1.RecoveryScopeCommitAttestation attestation = 2 [json_name = "attestation"];</code>
   */
  com.threadline.proto.threadline.crypto.v1.RecoveryScopeCommitAttestationOrBuilder getAttestationOrBuilder();
}
