// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/crypto/v1/recovery.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.crypto.v1;

@com.google.protobuf.Generated
public interface TargetedRecoveryApprovalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threadline.crypto.v1.TargetedRecoveryApproval)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string approval_id = 1 [json_name = "approvalId"];</code>
   * @return The approvalId.
   */
  java.lang.String getApprovalId();
  /**
   * <code>string approval_id = 1 [json_name = "approvalId"];</code>
   * @return The bytes for approvalId.
   */
  com.google.protobuf.ByteString
      getApprovalIdBytes();

  /**
   * <code>.threadline.type.v1.ActorRef approver = 2 [json_name = "approver"];</code>
   * @return Whether the approver field is set.
   */
  boolean hasApprover();
  /**
   * <code>.threadline.type.v1.ActorRef approver = 2 [json_name = "approver"];</code>
   * @return The approver.
   */
  com.threadline.proto.threadline.type.v1.ActorRef getApprover();
  /**
   * <code>.threadline.type.v1.ActorRef approver = 2 [json_name = "approver"];</code>
   */
  com.threadline.proto.threadline.type.v1.ActorRefOrBuilder getApproverOrBuilder();

  /**
   * <code>bool approved = 3 [json_name = "approved"];</code>
   * @return The approved.
   */
  boolean getApproved();

  /**
   * <pre>
   * Free-text justification, entered by the approver. Data class C3: it may
   * describe the incident, so it is stored encrypted and never logged.
   * </pre>
   *
   * <code>.threadline.type.v1.EncryptedField note = 4 [json_name = "note"];</code>
   * @return Whether the note field is set.
   */
  boolean hasNote();
  /**
   * <pre>
   * Free-text justification, entered by the approver. Data class C3: it may
   * describe the incident, so it is stored encrypted and never logged.
   * </pre>
   *
   * <code>.threadline.type.v1.EncryptedField note = 4 [json_name = "note"];</code>
   * @return The note.
   */
  com.threadline.proto.threadline.type.v1.EncryptedField getNote();
  /**
   * <pre>
   * Free-text justification, entered by the approver. Data class C3: it may
   * describe the incident, so it is stored encrypted and never logged.
   * </pre>
   *
   * <code>.threadline.type.v1.EncryptedField note = 4 [json_name = "note"];</code>
   */
  com.threadline.proto.threadline.type.v1.EncryptedFieldOrBuilder getNoteOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp decided_at = 5 [json_name = "decidedAt"];</code>
   * @return Whether the decidedAt field is set.
   */
  boolean hasDecidedAt();
  /**
   * <code>.google.protobuf.Timestamp decided_at = 5 [json_name = "decidedAt"];</code>
   * @return The decidedAt.
   */
  com.google.protobuf.Timestamp getDecidedAt();
  /**
   * <code>.google.protobuf.Timestamp decided_at = 5 [json_name = "decidedAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getDecidedAtOrBuilder();

  /**
   * <pre>
   * Organization policy version in force at decision time.
   * </pre>
   *
   * <code>string policy_version = 6 [json_name = "policyVersion"];</code>
   * @return The policyVersion.
   */
  java.lang.String getPolicyVersion();
  /**
   * <pre>
   * Organization policy version in force at decision time.
   * </pre>
   *
   * <code>string policy_version = 6 [json_name = "policyVersion"];</code>
   * @return The bytes for policyVersion.
   */
  com.google.protobuf.ByteString
      getPolicyVersionBytes();

  /**
   * <pre>
   * Client-generated idempotency key for this approver and case. Reusing it
   * with another decision fails with ERROR_CODE_REPLAY_DETECTED.
   * </pre>
   *
   * <code>string decision_id = 7 [json_name = "decisionId"];</code>
   * @return The decisionId.
   */
  java.lang.String getDecisionId();
  /**
   * <pre>
   * Client-generated idempotency key for this approver and case. Reusing it
   * with another decision fails with ERROR_CODE_REPLAY_DETECTED.
   * </pre>
   *
   * <code>string decision_id = 7 [json_name = "decisionId"];</code>
   * @return The bytes for decisionId.
   */
  com.google.protobuf.ByteString
      getDecisionIdBytes();

  /**
   * <pre>
   * Digest of the authoritative `recovery-case` v1 canonical transcript:
   * recovery_case_id, request_id, Tenant, requester ActorRef identity (actor_id
   * and actor_type), encrypted-reason binding, canonical `scopes`, one
   * recipient Device, required approval count, expiry and policy. No legacy
   * RecoveryCase projection participates in this targeted transcript.
   * The Case is immutable after the first decision; a changed projection
   * invalidates every approval and cannot be replayed to another request/Case.
   * </pre>
   *
   * <code>bytes case_binding_hash = 8 [json_name = "caseBindingHash"];</code>
   * @return The caseBindingHash.
   */
  com.google.protobuf.ByteString getCaseBindingHash();

  /**
   * <pre>
   * Device signature over the `recovery-decision` v1 canonical transcript of
   * `case_binding_hash` followed by the canonical
   * DecideTargetedRecoveryCaseRequest fields 1-4 and 7: recovery_case_id, approved,
   * the complete encrypted note (ciphertext, e2ee_group_id, epoch,
   * crypto_profile and envelope_version), decision_id and approver_device_id.
   * Service-generated approval_id, approver ActorRef and decided_at are
   * excluded. Policy is already covered by case_binding_hash.
   * </pre>
   *
   * <code>bytes decision_signature = 9 [json_name = "decisionSignature"];</code>
   * @return The decisionSignature.
   */
  com.google.protobuf.ByteString getDecisionSignature();

  /**
   * <pre>
   * Authorized Device that signed the decision. It is copied unchanged from
   * the request after the service verifies that it matches the caller session.
   * </pre>
   *
   * <code>string approver_device_id = 10 [json_name = "approverDeviceId"];</code>
   * @return The approverDeviceId.
   */
  java.lang.String getApproverDeviceId();
  /**
   * <pre>
   * Authorized Device that signed the decision. It is copied unchanged from
   * the request after the service verifies that it matches the caller session.
   * </pre>
   *
   * <code>string approver_device_id = 10 [json_name = "approverDeviceId"];</code>
   * @return The bytes for approverDeviceId.
   */
  com.google.protobuf.ByteString
      getApproverDeviceIdBytes();
}
