// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/identity/v1/identity_service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.threadline.proto.threadline.identity.v1;

@kotlin.jvm.JvmName("-initializerevokeSessionResponse")
public inline fun revokeSessionResponse(block: com.threadline.proto.threadline.identity.v1.RevokeSessionResponseKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.identity.v1.RevokeSessionResponse =
  com.threadline.proto.threadline.identity.v1.RevokeSessionResponseKt.Dsl._create(com.threadline.proto.threadline.identity.v1.RevokeSessionResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `threadline.identity.v1.RevokeSessionResponse`
 */
public object RevokeSessionResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.threadline.proto.threadline.identity.v1.RevokeSessionResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.threadline.proto.threadline.identity.v1.RevokeSessionResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.threadline.proto.threadline.identity.v1.RevokeSessionResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.threadline.proto.threadline.identity.v1.RevokeSessionResponse.copy(block: `com.threadline.proto.threadline.identity.v1`.RevokeSessionResponseKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.identity.v1.RevokeSessionResponse =
  `com.threadline.proto.threadline.identity.v1`.RevokeSessionResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

