// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/local_agent/v1/agent_service.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.local_agent.v1;

@com.google.protobuf.Generated
public interface LocalToolActivityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threadline.local_agent.v1.LocalToolActivity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Bounded, filtered display label. Never raw arguments, paths or tool output.
   * </pre>
   *
   * <code>string label = 1 [json_name = "label"];</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <pre>
   * Bounded, filtered display label. Never raw arguments, paths or tool output.
   * </pre>
   *
   * <code>string label = 1 [json_name = "label"];</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>.threadline.local_agent.v1.LocalToolPhase phase = 2 [json_name = "phase"];</code>
   * @return The enum numeric value on the wire for phase.
   */
  int getPhaseValue();
  /**
   * <code>.threadline.local_agent.v1.LocalToolPhase phase = 2 [json_name = "phase"];</code>
   * @return The phase.
   */
  com.threadline.proto.threadline.local_agent.v1.LocalToolPhase getPhase();
}
