// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/message/v1/message_service.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.message.v1;

@com.google.protobuf.Generated
public interface GetEventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threadline.message.v1.GetEventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.threadline.message.v1.ChannelEventEnvelope event = 1 [json_name = "event"];</code>
   * @return Whether the event field is set.
   */
  boolean hasEvent();
  /**
   * <code>.threadline.message.v1.ChannelEventEnvelope event = 1 [json_name = "event"];</code>
   * @return The event.
   */
  com.threadline.proto.threadline.message.v1.ChannelEventEnvelope getEvent();
  /**
   * <code>.threadline.message.v1.ChannelEventEnvelope event = 1 [json_name = "event"];</code>
   */
  com.threadline.proto.threadline.message.v1.ChannelEventEnvelopeOrBuilder getEventOrBuilder();
}
