// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/message/v1/payload.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.message.v1;

/**
 * <pre>
 * PinChanged pins or unpins an event in its conversation.
 * </pre>
 *
 * Protobuf type {@code threadline.message.v1.PinChanged}
 */
@com.google.protobuf.Generated
public final class PinChanged extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:threadline.message.v1.PinChanged)
    PinChangedOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "PinChanged");
  }
  // Use PinChanged.newBuilder() to construct.
  private PinChanged(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PinChanged() {
    targetEventId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.threadline.proto.threadline.message.v1.PayloadProto.internal_static_threadline_message_v1_PinChanged_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.threadline.proto.threadline.message.v1.PayloadProto.internal_static_threadline_message_v1_PinChanged_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.threadline.proto.threadline.message.v1.PayloadProto.internal_static_threadline_message_v1_PinChanged_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.threadline.proto.threadline.message.v1.PinChanged.class, com.threadline.proto.threadline.message.v1.PinChanged.Builder.class);
  }

  public static final int TARGET_EVENT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object targetEventId_ = "";
  /**
   * <code>string target_event_id = 1 [json_name = "targetEventId"];</code>
   * @return The targetEventId.
   */
  @java.lang.Override
  public java.lang.String getTargetEventId() {
    java.lang.Object ref = targetEventId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      targetEventId_ = s;
      return s;
    }
  }
  /**
   * <code>string target_event_id = 1 [json_name = "targetEventId"];</code>
   * @return The bytes for targetEventId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTargetEventIdBytes() {
    java.lang.Object ref = targetEventId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      targetEventId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PINNED_FIELD_NUMBER = 2;
  private boolean pinned_ = false;
  /**
   * <code>bool pinned = 2 [json_name = "pinned"];</code>
   * @return The pinned.
   */
  @java.lang.Override
  public boolean getPinned() {
    return pinned_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(targetEventId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, targetEventId_);
    }
    if (pinned_ != false) {
      output.writeBool(2, pinned_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(targetEventId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, targetEventId_);
    }
    if (pinned_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, pinned_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.threadline.proto.threadline.message.v1.PinChanged)) {
      return super.equals(obj);
    }
    com.threadline.proto.threadline.message.v1.PinChanged other = (com.threadline.proto.threadline.message.v1.PinChanged) obj;

    if (!getTargetEventId()
        .equals(other.getTargetEventId())) return false;
    if (getPinned()
        != other.getPinned()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TARGET_EVENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTargetEventId().hashCode();
    hash = (37 * hash) + PINNED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPinned());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.threadline.proto.threadline.message.v1.PinChanged parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.message.v1.PinChanged parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.message.v1.PinChanged parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.message.v1.PinChanged parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.message.v1.PinChanged parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.threadline.proto.threadline.message.v1.PinChanged parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.threadline.proto.threadline.message.v1.PinChanged parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.threadline.proto.threadline.message.v1.PinChanged parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.threadline.proto.threadline.message.v1.PinChanged parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.threadline.proto.threadline.message.v1.PinChanged parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.threadline.proto.threadline.message.v1.PinChanged parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.threadline.proto.threadline.message.v1.PinChanged parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.threadline.proto.threadline.message.v1.PinChanged prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * PinChanged pins or unpins an event in its conversation.
   * </pre>
   *
   * Protobuf type {@code threadline.message.v1.PinChanged}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:threadline.message.v1.PinChanged)
      com.threadline.proto.threadline.message.v1.PinChangedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.threadline.proto.threadline.message.v1.PayloadProto.internal_static_threadline_message_v1_PinChanged_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.threadline.proto.threadline.message.v1.PayloadProto.internal_static_threadline_message_v1_PinChanged_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.threadline.proto.threadline.message.v1.PinChanged.class, com.threadline.proto.threadline.message.v1.PinChanged.Builder.class);
    }

    // Construct using com.threadline.proto.threadline.message.v1.PinChanged.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      targetEventId_ = "";
      pinned_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.threadline.proto.threadline.message.v1.PayloadProto.internal_static_threadline_message_v1_PinChanged_descriptor;
    }

    @java.lang.Override
    public com.threadline.proto.threadline.message.v1.PinChanged getDefaultInstanceForType() {
      return com.threadline.proto.threadline.message.v1.PinChanged.getDefaultInstance();
    }

    @java.lang.Override
    public com.threadline.proto.threadline.message.v1.PinChanged build() {
      com.threadline.proto.threadline.message.v1.PinChanged result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.threadline.proto.threadline.message.v1.PinChanged buildPartial() {
      com.threadline.proto.threadline.message.v1.PinChanged result = new com.threadline.proto.threadline.message.v1.PinChanged(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.threadline.proto.threadline.message.v1.PinChanged result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.targetEventId_ = targetEventId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pinned_ = pinned_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.threadline.proto.threadline.message.v1.PinChanged) {
        return mergeFrom((com.threadline.proto.threadline.message.v1.PinChanged)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.threadline.proto.threadline.message.v1.PinChanged other) {
      if (other == com.threadline.proto.threadline.message.v1.PinChanged.getDefaultInstance()) return this;
      if (!other.getTargetEventId().isEmpty()) {
        targetEventId_ = other.targetEventId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getPinned() != false) {
        setPinned(other.getPinned());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              targetEventId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              pinned_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object targetEventId_ = "";
    /**
     * <code>string target_event_id = 1 [json_name = "targetEventId"];</code>
     * @return The targetEventId.
     */
    public java.lang.String getTargetEventId() {
      java.lang.Object ref = targetEventId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetEventId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string target_event_id = 1 [json_name = "targetEventId"];</code>
     * @return The bytes for targetEventId.
     */
    public com.google.protobuf.ByteString
        getTargetEventIdBytes() {
      java.lang.Object ref = targetEventId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetEventId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string target_event_id = 1 [json_name = "targetEventId"];</code>
     * @param value The targetEventId to set.
     * @return This builder for chaining.
     */
    public Builder setTargetEventId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      targetEventId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string target_event_id = 1 [json_name = "targetEventId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetEventId() {
      targetEventId_ = getDefaultInstance().getTargetEventId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string target_event_id = 1 [json_name = "targetEventId"];</code>
     * @param value The bytes for targetEventId to set.
     * @return This builder for chaining.
     */
    public Builder setTargetEventIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      targetEventId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean pinned_ ;
    /**
     * <code>bool pinned = 2 [json_name = "pinned"];</code>
     * @return The pinned.
     */
    @java.lang.Override
    public boolean getPinned() {
      return pinned_;
    }
    /**
     * <code>bool pinned = 2 [json_name = "pinned"];</code>
     * @param value The pinned to set.
     * @return This builder for chaining.
     */
    public Builder setPinned(boolean value) {

      pinned_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool pinned = 2 [json_name = "pinned"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPinned() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pinned_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:threadline.message.v1.PinChanged)
  }

  // @@protoc_insertion_point(class_scope:threadline.message.v1.PinChanged)
  private static final com.threadline.proto.threadline.message.v1.PinChanged DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.threadline.proto.threadline.message.v1.PinChanged();
  }

  public static com.threadline.proto.threadline.message.v1.PinChanged getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PinChanged>
      PARSER = new com.google.protobuf.AbstractParser<PinChanged>() {
    @java.lang.Override
    public PinChanged parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PinChanged> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PinChanged> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.threadline.proto.threadline.message.v1.PinChanged getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

