// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/message/v1/payload.proto
// Protobuf Java Version: 4.35.1

package com.threadline.proto.threadline.message.v1;

@com.google.protobuf.Generated
public interface PinChangedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threadline.message.v1.PinChanged)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string target_event_id = 1 [json_name = "targetEventId"];</code>
   * @return The targetEventId.
   */
  java.lang.String getTargetEventId();
  /**
   * <code>string target_event_id = 1 [json_name = "targetEventId"];</code>
   * @return The bytes for targetEventId.
   */
  com.google.protobuf.ByteString
      getTargetEventIdBytes();

  /**
   * <code>bool pinned = 2 [json_name = "pinned"];</code>
   * @return The pinned.
   */
  boolean getPinned();
}
