// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	CreateMember(ctx context.Context, arg CreateMemberParams) (DomainMember, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (DomainOrganization, error)
	DatabaseReady(ctx context.Context) (int64, error)
	GetMember(ctx context.Context, arg GetMemberParams) (DomainMember, error)
	GetOrganization(ctx context.Context, tenantID string) (DomainOrganization, error)
	UpdateMemberRoleState(ctx context.Context, arg UpdateMemberRoleStateParams) (DomainMember, error)
	UpdateOrganizationStatePolicy(ctx context.Context, arg UpdateOrganizationStatePolicyParams) (DomainOrganization, error)
}

var _ Querier = (*Queries)(nil)
