// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_acl.sql

package dbgen

import (
	"context"
)

const createResourceACLEntry = `-- name: CreateResourceACLEntry :exec
INSERT INTO domain.resource_acl_entries (
  tenant_id,
  acl_version,
  entry_ordinal,
  actor_type,
  actor_id,
  action,
  effect
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
`

type CreateResourceACLEntryParams struct {
	TenantID     string
	AclVersion   int64
	EntryOrdinal int32
	ActorType    int16
	ActorID      string
	Action       int16
	Effect       int16
}

func (q *Queries) CreateResourceACLEntry(ctx context.Context, arg CreateResourceACLEntryParams) error {
	_, err := q.db.Exec(ctx, createResourceACLEntry,
		arg.TenantID,
		arg.AclVersion,
		arg.EntryOrdinal,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.Effect,
	)
	return err
}

const createResourceACLSnapshot = `-- name: CreateResourceACLSnapshot :one
INSERT INTO domain.resource_acl_snapshots (
  tenant_id,
  resource_kind,
  resource_id,
  space_id,
  channel_id,
  default_effect
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING acl_version, tenant_id, resource_kind, resource_id, space_id, channel_id,
  default_effect, entries_sealed, created_at
`

type CreateResourceACLSnapshotParams struct {
	TenantID      string
	ResourceKind  int16
	ResourceID    string
	SpaceID       *string
	ChannelID     *string
	DefaultEffect int16
}

func (q *Queries) CreateResourceACLSnapshot(ctx context.Context, arg CreateResourceACLSnapshotParams) (DomainResourceAclSnapshot, error) {
	row := q.db.QueryRow(ctx, createResourceACLSnapshot,
		arg.TenantID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.SpaceID,
		arg.ChannelID,
		arg.DefaultEffect,
	)
	var i DomainResourceAclSnapshot
	err := row.Scan(
		&i.AclVersion,
		&i.TenantID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.SpaceID,
		&i.ChannelID,
		&i.DefaultEffect,
		&i.EntriesSealed,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentResourceACLSnapshot = `-- name: GetCurrentResourceACLSnapshot :one
SELECT
  snapshot.acl_version,
  snapshot.default_effect
FROM domain.resource_acl_heads AS head
JOIN domain.resource_acl_snapshots AS snapshot
  ON snapshot.tenant_id = head.tenant_id
 AND snapshot.acl_version = head.current_acl_version
 AND snapshot.resource_kind = head.resource_kind
 AND snapshot.resource_id = head.resource_id
WHERE head.tenant_id = $1
  AND head.resource_kind = $2
  AND head.resource_id = $3
  AND snapshot.entries_sealed
`

type GetCurrentResourceACLSnapshotParams struct {
	TenantID     string
	ResourceKind int16
	ResourceID   string
}

type GetCurrentResourceACLSnapshotRow struct {
	AclVersion    int64
	DefaultEffect int16
}

func (q *Queries) GetCurrentResourceACLSnapshot(ctx context.Context, arg GetCurrentResourceACLSnapshotParams) (GetCurrentResourceACLSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getCurrentResourceACLSnapshot, arg.TenantID, arg.ResourceKind, arg.ResourceID)
	var i GetCurrentResourceACLSnapshotRow
	err := row.Scan(&i.AclVersion, &i.DefaultEffect)
	return i, err
}

const listResourceACLEntries = `-- name: ListResourceACLEntries :many
SELECT actor_type, actor_id, action, effect
FROM domain.resource_acl_entries
WHERE tenant_id = $1
  AND acl_version = $2
ORDER BY entry_ordinal
`

type ListResourceACLEntriesParams struct {
	TenantID   string
	AclVersion int64
}

type ListResourceACLEntriesRow struct {
	ActorType int16
	ActorID   string
	Action    int16
	Effect    int16
}

func (q *Queries) ListResourceACLEntries(ctx context.Context, arg ListResourceACLEntriesParams) ([]ListResourceACLEntriesRow, error) {
	rows, err := q.db.Query(ctx, listResourceACLEntries, arg.TenantID, arg.AclVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourceACLEntriesRow{}
	for rows.Next() {
		var i ListResourceACLEntriesRow
		if err := rows.Scan(
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.Effect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockChannelForACLReplacement = `-- name: LockChannelForACLReplacement :one
SELECT channel_id
FROM domain.channels
WHERE tenant_id = $1
  AND channel_id = $2
FOR NO KEY UPDATE
`

type LockChannelForACLReplacementParams struct {
	TenantID   string
	ResourceID string
}

func (q *Queries) LockChannelForACLReplacement(ctx context.Context, arg LockChannelForACLReplacementParams) (string, error) {
	row := q.db.QueryRow(ctx, lockChannelForACLReplacement, arg.TenantID, arg.ResourceID)
	var channel_id string
	err := row.Scan(&channel_id)
	return channel_id, err
}

const lockSpaceForACLReplacement = `-- name: LockSpaceForACLReplacement :one
SELECT space_id
FROM domain.spaces
WHERE tenant_id = $1
  AND space_id = $2
FOR NO KEY UPDATE
`

type LockSpaceForACLReplacementParams struct {
	TenantID   string
	ResourceID string
}

func (q *Queries) LockSpaceForACLReplacement(ctx context.Context, arg LockSpaceForACLReplacementParams) (string, error) {
	row := q.db.QueryRow(ctx, lockSpaceForACLReplacement, arg.TenantID, arg.ResourceID)
	var space_id string
	err := row.Scan(&space_id)
	return space_id, err
}

const sealResourceACLSnapshot = `-- name: SealResourceACLSnapshot :one
UPDATE domain.resource_acl_snapshots
SET entries_sealed = TRUE
WHERE tenant_id = $1
  AND acl_version = $2
  AND NOT entries_sealed
RETURNING acl_version
`

type SealResourceACLSnapshotParams struct {
	TenantID   string
	AclVersion int64
}

func (q *Queries) SealResourceACLSnapshot(ctx context.Context, arg SealResourceACLSnapshotParams) (int64, error) {
	row := q.db.QueryRow(ctx, sealResourceACLSnapshot, arg.TenantID, arg.AclVersion)
	var acl_version int64
	err := row.Scan(&acl_version)
	return acl_version, err
}

const setCurrentResourceACL = `-- name: SetCurrentResourceACL :exec
INSERT INTO domain.resource_acl_heads (
  tenant_id,
  resource_kind,
  resource_id,
  space_id,
  channel_id,
  current_acl_version
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
ON CONFLICT (tenant_id, resource_kind, resource_id) DO UPDATE
SET current_acl_version = EXCLUDED.current_acl_version
`

type SetCurrentResourceACLParams struct {
	TenantID     string
	ResourceKind int16
	ResourceID   string
	SpaceID      *string
	ChannelID    *string
	AclVersion   int64
}

func (q *Queries) SetCurrentResourceACL(ctx context.Context, arg SetCurrentResourceACLParams) error {
	_, err := q.db.Exec(ctx, setCurrentResourceACL,
		arg.TenantID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.SpaceID,
		arg.ChannelID,
		arg.AclVersion,
	)
	return err
}
