// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/realtime/v1/frame.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.threadline.proto.threadline.realtime.v1;

@kotlin.jvm.JvmName("-initializetypingUpdate")
public inline fun typingUpdate(block: com.threadline.proto.threadline.realtime.v1.TypingUpdateKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.realtime.v1.TypingUpdate =
  com.threadline.proto.threadline.realtime.v1.TypingUpdateKt.Dsl._create(com.threadline.proto.threadline.realtime.v1.TypingUpdate.newBuilder()).apply { block() }._build()
/**
 * ```
 * TypingUpdate reports composing activity. Ephemeral, never persisted.
 * ```
 *
 * Protobuf type `threadline.realtime.v1.TypingUpdate`
 */
public object TypingUpdateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.threadline.proto.threadline.realtime.v1.TypingUpdate.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.threadline.proto.threadline.realtime.v1.TypingUpdate.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.threadline.proto.threadline.realtime.v1.TypingUpdate = _builder.build()

    /**
     * `string channel_id = 1 [json_name = "channelId"];`
     */
    public var channelId: kotlin.String
      @kotlin.jvm.JvmName("getChannelId")
        get() = _builder.channelId
      @kotlin.jvm.JvmName("setChannelId")
        set(value) {
        _builder.channelId = value
      }
    /**
     * `string channel_id = 1 [json_name = "channelId"];`
     */
    public fun clearChannelId() {
      _builder.clearChannelId()
    }
    /**
     * `string channel_id = 1 [json_name = "channelId"];`
     * @return Whether the channelId field is set.
     */
    public fun hasChannelId(): kotlin.Boolean {
      return _builder.hasChannelId()
    }

    /**
     * `string dm_id = 2 [json_name = "dmId"];`
     */
    public var dmId: kotlin.String
      @kotlin.jvm.JvmName("getDmId")
        get() = _builder.dmId
      @kotlin.jvm.JvmName("setDmId")
        set(value) {
        _builder.dmId = value
      }
    /**
     * `string dm_id = 2 [json_name = "dmId"];`
     */
    public fun clearDmId() {
      _builder.clearDmId()
    }
    /**
     * `string dm_id = 2 [json_name = "dmId"];`
     * @return Whether the dmId field is set.
     */
    public fun hasDmId(): kotlin.Boolean {
      return _builder.hasDmId()
    }

    /**
     * `string actor_id = 3 [json_name = "actorId"];`
     */
    public var actorId: kotlin.String
      @kotlin.jvm.JvmName("getActorId")
        get() = _builder.actorId
      @kotlin.jvm.JvmName("setActorId")
        set(value) {
        _builder.actorId = value
      }
    /**
     * `string actor_id = 3 [json_name = "actorId"];`
     */
    public fun clearActorId() {
      _builder.clearActorId()
    }

    /**
     * `bool typing = 4 [json_name = "typing"];`
     */
    public var typing: kotlin.Boolean
      @kotlin.jvm.JvmName("getTyping")
        get() = _builder.typing
      @kotlin.jvm.JvmName("setTyping")
        set(value) {
        _builder.typing = value
      }
    /**
     * `bool typing = 4 [json_name = "typing"];`
     */
    public fun clearTyping() {
      _builder.clearTyping()
    }
    public val conversationCase: com.threadline.proto.threadline.realtime.v1.TypingUpdate.ConversationCase
    @kotlin.jvm.JvmName("getConversationCase")
      get() = _builder.getConversationCase()

    public fun clearConversation() {
      _builder.clearConversation()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.threadline.proto.threadline.realtime.v1.TypingUpdate.copy(block: `com.threadline.proto.threadline.realtime.v1`.TypingUpdateKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.realtime.v1.TypingUpdate =
  `com.threadline.proto.threadline.realtime.v1`.TypingUpdateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

