// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/task/v1/task_service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.threadline.proto.threadline.task.v1;

@kotlin.jvm.JvmName("-initializelistArtifactsRequest")
public inline fun listArtifactsRequest(block: com.threadline.proto.threadline.task.v1.ListArtifactsRequestKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.task.v1.ListArtifactsRequest =
  com.threadline.proto.threadline.task.v1.ListArtifactsRequestKt.Dsl._create(com.threadline.proto.threadline.task.v1.ListArtifactsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `threadline.task.v1.ListArtifactsRequest`
 */
public object ListArtifactsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.threadline.proto.threadline.task.v1.ListArtifactsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.threadline.proto.threadline.task.v1.ListArtifactsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.threadline.proto.threadline.task.v1.ListArtifactsRequest = _builder.build()

    /**
     * `string run_id = 1 [json_name = "runId"];`
     */
    public var runId: kotlin.String
      @kotlin.jvm.JvmName("getRunId")
        get() = _builder.runId
      @kotlin.jvm.JvmName("setRunId")
        set(value) {
        _builder.runId = value
      }
    /**
     * `string run_id = 1 [json_name = "runId"];`
     */
    public fun clearRunId() {
      _builder.clearRunId()
    }

    /**
     * `.threadline.type.v1.PageRequest page = 2 [json_name = "page"];`
     */
    public var page: com.threadline.proto.threadline.type.v1.PageRequest
      @kotlin.jvm.JvmName("getPage")
        get() = _builder.page
      @kotlin.jvm.JvmName("setPage")
        set(value) {
        _builder.page = value
      }
    /**
     * `.threadline.type.v1.PageRequest page = 2 [json_name = "page"];`
     */
    public fun clearPage() {
      _builder.clearPage()
    }
    /**
     * `.threadline.type.v1.PageRequest page = 2 [json_name = "page"];`
     * @return Whether the page field is set.
     */
    public fun hasPage(): kotlin.Boolean {
      return _builder.hasPage()
    }

    public val ListArtifactsRequestKt.Dsl.pageOrNull: com.threadline.proto.threadline.type.v1.PageRequest?
      get() = _builder.pageOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.threadline.proto.threadline.task.v1.ListArtifactsRequest.copy(block: `com.threadline.proto.threadline.task.v1`.ListArtifactsRequestKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.task.v1.ListArtifactsRequest =
  `com.threadline.proto.threadline.task.v1`.ListArtifactsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.threadline.proto.threadline.task.v1.ListArtifactsRequestOrBuilder.pageOrNull: com.threadline.proto.threadline.type.v1.PageRequest?
  get() = if (hasPage()) getPage() else null

