// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/task/v1/task_service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.threadline.proto.threadline.task.v1;

@kotlin.jvm.JvmName("-initializetransferRunRequest")
public inline fun transferRunRequest(block: com.threadline.proto.threadline.task.v1.TransferRunRequestKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.task.v1.TransferRunRequest =
  com.threadline.proto.threadline.task.v1.TransferRunRequestKt.Dsl._create(com.threadline.proto.threadline.task.v1.TransferRunRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `threadline.task.v1.TransferRunRequest`
 */
public object TransferRunRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.threadline.proto.threadline.task.v1.TransferRunRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.threadline.proto.threadline.task.v1.TransferRunRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.threadline.proto.threadline.task.v1.TransferRunRequest = _builder.build()

    /**
     * `string run_id = 1 [json_name = "runId"];`
     */
    public var runId: kotlin.String
      @kotlin.jvm.JvmName("getRunId")
        get() = _builder.runId
      @kotlin.jvm.JvmName("setRunId")
        set(value) {
        _builder.runId = value
      }
    /**
     * `string run_id = 1 [json_name = "runId"];`
     */
    public fun clearRunId() {
      _builder.clearRunId()
    }

    /**
     * `string target_runtime_id = 2 [json_name = "targetRuntimeId"];`
     */
    public var targetRuntimeId: kotlin.String
      @kotlin.jvm.JvmName("getTargetRuntimeId")
        get() = _builder.targetRuntimeId
      @kotlin.jvm.JvmName("setTargetRuntimeId")
        set(value) {
        _builder.targetRuntimeId = value
      }
    /**
     * `string target_runtime_id = 2 [json_name = "targetRuntimeId"];`
     */
    public fun clearTargetRuntimeId() {
      _builder.clearTargetRuntimeId()
    }

    /**
     * `string workspace_binding_id = 3 [json_name = "workspaceBindingId"];`
     */
    public var workspaceBindingId: kotlin.String
      @kotlin.jvm.JvmName("getWorkspaceBindingId")
        get() = _builder.workspaceBindingId
      @kotlin.jvm.JvmName("setWorkspaceBindingId")
        set(value) {
        _builder.workspaceBindingId = value
      }
    /**
     * `string workspace_binding_id = 3 [json_name = "workspaceBindingId"];`
     */
    public fun clearWorkspaceBindingId() {
      _builder.clearWorkspaceBindingId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.threadline.proto.threadline.task.v1.TransferRunRequest.copy(block: `com.threadline.proto.threadline.task.v1`.TransferRunRequestKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.task.v1.TransferRunRequest =
  `com.threadline.proto.threadline.task.v1`.TransferRunRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

