// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/type/v1/common.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.threadline.proto.threadline.type.v1;

@kotlin.jvm.JvmName("-initializeactorRef")
public inline fun actorRef(block: com.threadline.proto.threadline.type.v1.ActorRefKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.type.v1.ActorRef =
  com.threadline.proto.threadline.type.v1.ActorRefKt.Dsl._create(com.threadline.proto.threadline.type.v1.ActorRef.newBuilder()).apply { block() }._build()
/**
 * ```
 * ActorRef identifies a participant inside one tenant.
 *
 * Data class C2. Never carries a display name: names are tenant directory data
 * resolved through the identity service, not copied into every envelope.
 * ```
 *
 * Protobuf type `threadline.type.v1.ActorRef`
 */
public object ActorRefKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.threadline.proto.threadline.type.v1.ActorRef.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.threadline.proto.threadline.type.v1.ActorRef.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.threadline.proto.threadline.type.v1.ActorRef = _builder.build()

    /**
     * ```
     * Opaque tenant-scoped identifier. Stable for the lifetime of the Actor.
     * ```
     *
     * `string actor_id = 1 [json_name = "actorId"];`
     */
    public var actorId: kotlin.String
      @kotlin.jvm.JvmName("getActorId")
        get() = _builder.actorId
      @kotlin.jvm.JvmName("setActorId")
        set(value) {
        _builder.actorId = value
      }
    /**
     * ```
     * Opaque tenant-scoped identifier. Stable for the lifetime of the Actor.
     * ```
     *
     * `string actor_id = 1 [json_name = "actorId"];`
     */
    public fun clearActorId() {
      _builder.clearActorId()
    }

    /**
     * `.threadline.type.v1.ActorType actor_type = 2 [json_name = "actorType"];`
     */
    public var actorType: com.threadline.proto.threadline.type.v1.ActorType
      @kotlin.jvm.JvmName("getActorType")
        get() = _builder.actorType
      @kotlin.jvm.JvmName("setActorType")
        set(value) {
        _builder.actorType = value
      }
    public var actorTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getActorTypeValue")
        get() = _builder.actorTypeValue
      @kotlin.jvm.JvmName("setActorTypeValue")
        set(value) {
        _builder.actorTypeValue = value
      }
    /**
     * `.threadline.type.v1.ActorType actor_type = 2 [json_name = "actorType"];`
     */
    public fun clearActorType() {
      _builder.clearActorType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.threadline.proto.threadline.type.v1.ActorRef.copy(block: `com.threadline.proto.threadline.type.v1`.ActorRefKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.type.v1.ActorRef =
  `com.threadline.proto.threadline.type.v1`.ActorRefKt.Dsl._create(this.toBuilder()).apply { block() }._build()

