// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/runtime/v1/runtime_service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.threadline.proto.threadline.runtime.v1;

@kotlin.jvm.JvmName("-initializecompleteRunResponse")
public inline fun completeRunResponse(block: com.threadline.proto.threadline.runtime.v1.CompleteRunResponseKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.runtime.v1.CompleteRunResponse =
  com.threadline.proto.threadline.runtime.v1.CompleteRunResponseKt.Dsl._create(com.threadline.proto.threadline.runtime.v1.CompleteRunResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `threadline.runtime.v1.CompleteRunResponse`
 */
public object CompleteRunResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.threadline.proto.threadline.runtime.v1.CompleteRunResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.threadline.proto.threadline.runtime.v1.CompleteRunResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.threadline.proto.threadline.runtime.v1.CompleteRunResponse = _builder.build()

    /**
     * `.threadline.task.v1.Run run = 1 [json_name = "run"];`
     */
    public var run: com.threadline.proto.threadline.task.v1.Run
      @kotlin.jvm.JvmName("getRun")
        get() = _builder.run
      @kotlin.jvm.JvmName("setRun")
        set(value) {
        _builder.run = value
      }
    /**
     * `.threadline.task.v1.Run run = 1 [json_name = "run"];`
     */
    public fun clearRun() {
      _builder.clearRun()
    }
    /**
     * `.threadline.task.v1.Run run = 1 [json_name = "run"];`
     * @return Whether the run field is set.
     */
    public fun hasRun(): kotlin.Boolean {
      return _builder.hasRun()
    }

    public val CompleteRunResponseKt.Dsl.runOrNull: com.threadline.proto.threadline.task.v1.Run?
      get() = _builder.runOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.threadline.proto.threadline.runtime.v1.CompleteRunResponse.copy(block: `com.threadline.proto.threadline.runtime.v1`.CompleteRunResponseKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.runtime.v1.CompleteRunResponse =
  `com.threadline.proto.threadline.runtime.v1`.CompleteRunResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.threadline.proto.threadline.runtime.v1.CompleteRunResponseOrBuilder.runOrNull: com.threadline.proto.threadline.task.v1.Run?
  get() = if (hasRun()) getRun() else null

