// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threadline/runtime/v1/runtime_service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.threadline.proto.threadline.runtime.v1;

@kotlin.jvm.JvmName("-initializerevokeRuntimeRequest")
public inline fun revokeRuntimeRequest(block: com.threadline.proto.threadline.runtime.v1.RevokeRuntimeRequestKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.runtime.v1.RevokeRuntimeRequest =
  com.threadline.proto.threadline.runtime.v1.RevokeRuntimeRequestKt.Dsl._create(com.threadline.proto.threadline.runtime.v1.RevokeRuntimeRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `threadline.runtime.v1.RevokeRuntimeRequest`
 */
public object RevokeRuntimeRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.threadline.proto.threadline.runtime.v1.RevokeRuntimeRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.threadline.proto.threadline.runtime.v1.RevokeRuntimeRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.threadline.proto.threadline.runtime.v1.RevokeRuntimeRequest = _builder.build()

    /**
     * `string runtime_id = 1 [json_name = "runtimeId"];`
     */
    public var runtimeId: kotlin.String
      @kotlin.jvm.JvmName("getRuntimeId")
        get() = _builder.runtimeId
      @kotlin.jvm.JvmName("setRuntimeId")
        set(value) {
        _builder.runtimeId = value
      }
    /**
     * `string runtime_id = 1 [json_name = "runtimeId"];`
     */
    public fun clearRuntimeId() {
      _builder.clearRuntimeId()
    }

    /**
     * `string reason = 2 [json_name = "reason"];`
     */
    public var reason: kotlin.String
      @kotlin.jvm.JvmName("getReason")
        get() = _builder.reason
      @kotlin.jvm.JvmName("setReason")
        set(value) {
        _builder.reason = value
      }
    /**
     * `string reason = 2 [json_name = "reason"];`
     */
    public fun clearReason() {
      _builder.clearReason()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.threadline.proto.threadline.runtime.v1.RevokeRuntimeRequest.copy(block: `com.threadline.proto.threadline.runtime.v1`.RevokeRuntimeRequestKt.Dsl.() -> kotlin.Unit): com.threadline.proto.threadline.runtime.v1.RevokeRuntimeRequest =
  `com.threadline.proto.threadline.runtime.v1`.RevokeRuntimeRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

